### ISSUE TITLE
XIV Launcher Bug Report 1

### ISSUE THREAD

**Issue by LeeBunnie** [goatcorp/FFXIVQuickLauncher#1001]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

i started XIV Launcher as i normally would 

### Platform

Windows

### Relevant log output

```shell
XIVLauncher.Common.Dalamud.DalamudRunnerException: An internal Dalamud error has occured
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 62
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 268
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 601

Version: 6.2.37.0
Git Hash: 6.2.37-0-g3eb94ef
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by reiichi001** [comment]
Hello! Could you please provide the full `output.log` and `dalamud.log` files from `%APPDATA%\XIVLauncher` please?

We've been seeing this error arise mostly from users who previous enabled Dalamud Staging (aka Dalamud Testing). If this is something you might have done, I'd recommend putting back the original values. See <https://goatcorp.github.io/faq/dalamud_troubleshooting#q-how-do-i-turn-dalamud-staging-on-or-off> for more details there. After setting those fields to `null` (or remove the entire config file if you don't care about other settings in it), you'll also want to reset Dalamud.

To reset Dalamud, head back to the `%APPDATA%\XIVLauncher` folder and remove the `addon`, `dalamudAssets`, and `runtime` folders. XIVLauncher will redownload these when you open it.

**Comment by NotNite** [comment]
Closing due to inactivity. If you're still having issues, please reopen this issue.
