### ISSUE TITLE
Issue When XIVLauncher Needs To Patch FFXIV On Non-Admin Windows Account In Steam Big Picture Mode

### ISSUE THREAD

**Issue by gfactor** [goatcorp/FFXIVQuickLauncher#1030]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I run Steam in Big Picture mode to use with a Steam Link app. I also changed the FFXIV launch option in Steam to call XIVLauncher directly. When XIVLauncher needs to patch FFXIV, it calls up a UAC prompt since my Windows account is not an admin account. However, when Steam is in Big Picture mode, XIVLauncher instead seems to be pressing CTRL+ALT+DEL instead of calling for a UAC prompt. When I press Escape to leave that screen, XIVLauncher said I cancelled the update operation. In order to get XIVLauncher to actually call the UAC prompt and start updating, I need to exit Steam Big Picture mode. Is there a way to get XIVLauncher to call the UAC prompt even when Steam is in Big Picture mode?

I believe these are the steps to reproduce:
1. Set up XIVLauncher with a Steam copy of FFXIV on a non-admin Windows account.
2. In Steam, change the launch options for FFXIV to launch XIVLauncher ("path\to\XIVLauncher.exe" %command%)
3. Start Steam's Big Picture Mode.
4. In Steam, start FFXIV (which should launch XIVLauncher) when FFXIV needs to be patched.
Expected result: a UAC prompt should show up
Actual result: the screen that usually shows up when CTRL+ALT+DEL is pressed shows up instead
Workaround: exit Steam Big Picture Mode before starting XIVLauncher

### Platform

Windows

### Relevant log output

```shell
LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xMVQyMjo1MDowNS43ODM3NDAyLTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5Db21wb25lbnRNb2RlbC5XaW4zMkV4Y2VwdGlvbiAoMHg4MDAwNDAwNSk6IFRoZSBvcGVyYXRpb24gd2FzIGNhbmNlbGVkIGJ5IHRoZSB1c2VyXHJcbiAgIGF0IFN5c3RlbS5EaWFnbm9zdGljcy5Qcm9jZXNzLlN0YXJ0V2l0aFNoZWxsRXhlY3V0ZUV4KFByb2Nlc3NTdGFydEluZm8gc3RhcnRJbmZvKVxyXG4gICBhdCBTeXN0ZW0uRGlhZ25vc3RpY3MuUHJvY2Vzcy5TdGFydChQcm9jZXNzU3RhcnRJbmZvIHN0YXJ0SW5mbylcclxuICAgYXQgWElWTGF1bmNoZXIuQ29tbW9uLkdhbWUuUGF0Y2guUGF0Y2hJbnN0YWxsZXIuU3RhcnRJZk5lZWRlZChCb29sZWFuIGV4dGVybmFsKSBpbiBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXEdhbWVcXFBhdGNoXFxQYXRjaEluc3RhbGxlci5jczpsaW5lIDY2IiwiQ29udGV4dCI6IkNvdWxkIG5vdCBsYXVuY2ggUGF0Y2ggSW5zdGFsbGVyIn0=
2022-06-11 22:50:21.195 -04:00 [ERR] patchSuccess != true
2022-06-11 22:50:36.806 -04:00 [INF] Trying to set up Loc for language code en
2022-06-11 22:50:36.835 -04:00 [INF] XIVLauncher started as xivlauncher-6.2.40.0-6.2.40-0-gdb12d85
2022-06-11 22:50:36.837 -04:00 [INF] Starting update check...
2022-06-11 22:50:37.938 -04:00 [INF] Engaging Autologin...
2022-06-11 22:50:37.948 -04:00 [INF] [DUPDATE] Starting...
2022-06-11 22:50:38.063 -04:00 [INF] [DUPDATE] Using release version (6.4.0.18)
2022-06-11 22:50:38.222 -04:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.17
2022-06-11 22:50:38.775 -04:00 [INF] XivGame::Login(steamServiceAccount:true, cache:false)
2022-06-11 22:50:39.046 -04:00 [INF] [DUPDATE] All set for 2022.05.27.0000.0000
2022-06-11 22:50:39.200 -04:00 [INF] FFFF8CC3
2022-06-11 22:50:39.200 -04:00 [INF] [STEAM] time: 1654987800, bfKey: 62a51c18#un@e=x>, rawTicket.Length: 565, ticketSum: 36035, fuckedSum: 875662629, seed: -1655009061, numRandomBytes: 1
2022-06-11 22:50:41.107 -04:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-06-11 22:50:44.461 -04:00 [INF] [PATCHERIPC] Starting patcher with 'XLPatcher211e2e1b-e77a-437e-9c8e-62746fb2cd05'
2022-06-11 22:50:45.810 -04:00 [ERR] Could not launch Patch Installer
System.ComponentModel.Win32Exception (0x80004005): The operation was canceled by the user
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at XIVLauncher.Common.Game.Patch.PatchInstaller.StartIfNeeded(Boolean external) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchInstaller.cs:line 66
2022-06-11 22:50:45.831 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xMVQyMjo1MDo0NS44MTY3NTc1LTA0OjAwIiwiSW5mbyI6IlN5c3RlbS5Db21wb25lbnRNb2RlbC5XaW4zMkV4Y2VwdGlvbiAoMHg4MDAwNDAwNSk6IFRoZSBvcGVyYXRpb24gd2FzIGNhbmNlbGVkIGJ5IHRoZSB1c2VyXHJcbiAgIGF0IFN5c3RlbS5EaWFnbm9zdGljcy5Qcm9jZXNzLlN0YXJ0V2l0aFNoZWxsRXhlY3V0ZUV4KFByb2Nlc3NTdGFydEluZm8gc3RhcnRJbmZvKVxyXG4gICBhdCBTeXN0ZW0uRGlhZ25vc3RpY3MuUHJvY2Vzcy5TdGFydChQcm9jZXNzU3RhcnRJbmZvIHN0YXJ0SW5mbylcclxuICAgYXQgWElWTGF1bmNoZXIuQ29tbW9uLkdhbWUuUGF0Y2guUGF0Y2hJbnN0YWxsZXIuU3RhcnRJZk5lZWRlZChCb29sZWFuIGV4dGVybmFsKSBpbiBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXEdhbWVcXFBhdGNoXFxQYXRjaEluc3RhbGxlci5jczpsaW5lIDY2IiwiQ29udGV4dCI6IkNvdWxkIG5vdCBsYXVuY2ggUGF0Y2ggSW5zdGFsbGVyIn0=
```

**Comment by NotNite** [comment]
This sounds like a Big Picture bug - or perhaps just a Windows "feature". Some applications that capture desktop freeze when UAC prompts are open - maybe it's instead just freezing?
