### ISSUE TITLE
Failed to load DalamudConfiguration

### ISSUE THREAD

**Issue by SodaLee** [goatcorp/FFXIVQuickLauncher#1032]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Failed to load DalamudConfiguration
Is it caused by old version plugins?

### Platform

Windows

### Relevant log output

```shell
2022-06-13 18:29:18.435 +08:00 [INF] [SimpleTweaksPlugin] Dispose: Timer on Duty Waiting
2022-06-13 18:29:18.474 +08:00 [INF] Framework::Destroy OK!
2022-06-13 18:29:18.524 +08:00 [FTL] Unhandled exception on AppDomain
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Dalamud.Interface.Internal.Windows.PluginImageCache.DownloadTask() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginImageCache.cs:line 237
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2022-06-13 18:29:18.529 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xM1QxODoyOToxOC41MjkzMDgzKzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5PYmplY3REaXNwb3NlZEV4Y2VwdGlvbjogVGhlIENhbmNlbGxhdGlvblRva2VuU291cmNlIGhhcyBiZWVuIGRpc3Bvc2VkLlxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkNhbmNlbGxhdGlvblRva2VuU291cmNlLlRocm93T2JqZWN0RGlzcG9zZWRFeGNlcHRpb24oKVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlBsdWdpbkltYWdlQ2FjaGUuRG93bmxvYWRUYXNrKCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxJbnRlcm5hbFxcV2luZG93c1xcUGx1Z2luSW1hZ2VDYWNoZS5jczpsaW5lIDIzN1xyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suPD5jLjxUaHJvd0FzeW5jPmJfXzE0MF8xKE9iamVjdCBzdGF0ZSlcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5RdWV1ZVVzZXJXb3JrSXRlbUNhbGxiYWNrRGVmYXVsdENvbnRleHQuRXhlY3V0ZSgpXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuVGhyZWFkUG9vbFdvcmtRdWV1ZS5EaXNwYXRjaCgpIiwiQ29udGV4dCI6IlVuaGFuZGxlZCBleGNlcHRpb24gb24gQXBwRG9tYWluIn0=
2022-06-13 18:29:18.529 +08:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xM1QxODoyOToxOC41MjkzNzY4KzA4OjAwIiwiSW5mbyI6IlN5c3RlbS5PYmplY3REaXNwb3NlZEV4Y2VwdGlvbjogVGhlIENhbmNlbGxhdGlvblRva2VuU291cmNlIGhhcyBiZWVuIGRpc3Bvc2VkLlxyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLkNhbmNlbGxhdGlvblRva2VuU291cmNlLlRocm93T2JqZWN0RGlzcG9zZWRFeGNlcHRpb24oKVxyXG4gICBhdCBEYWxhbXVkLkludGVyZmFjZS5JbnRlcm5hbC5XaW5kb3dzLlBsdWdpbkltYWdlQ2FjaGUuRG93bmxvYWRUYXNrKCkgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcSW50ZXJmYWNlXFxJbnRlcm5hbFxcV2luZG93c1xcUGx1Z2luSW1hZ2VDYWNoZS5jczpsaW5lIDIzN1xyXG4gICBhdCBTeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlRhc2suPD5jLjxUaHJvd0FzeW5jPmJfXzE0MF8xKE9iamVjdCBzdGF0ZSlcclxuICAgYXQgU3lzdGVtLlRocmVhZGluZy5RdWV1ZVVzZXJXb3JrSXRlbUNhbGxiYWNrRGVmYXVsdENvbnRleHQuRXhlY3V0ZSgpXHJcbiAgIGF0IFN5c3RlbS5UaHJlYWRpbmcuVGhyZWFkUG9vbFdvcmtRdWV1ZS5EaXNwYXRjaCgpIiwiQ29udGV4dCI6IkRhbGFtdWRVbmhhbmRsZWQifQ==
2022-06-13 18:29:28.502 +08:00 [INF] Framework::Free!
2022-06-13 18:29:28.502 +08:00 [INF] Trigger unload
2022-06-13 18:29:29.020 +08:00 [INF] Debug check was not overwritten?
2022-06-13 18:29:29.026 +08:00 [INF] Session has ended.
2022-06-13 18:30:06.542 +08:00 [WRN] Failed to load DalamudConfiguration at C:\Users\SodaL\AppData\Roaming\XIVLauncher\dalamudConfig.json
Newtonsoft.Json.JsonSerializationException: Type specified in JSON 'System.Collections.Generic.List`1[[Dalamud.Configuration.ThirdPartyRepoSettings, Dalamud, Version=6.3.0.13, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e' is not compatible with 'System.Collections.Generic.List`1[[Dalamud.Configuration.ThirdPartyRepoSettings, Dalamud, Version=6.4.0.18, Culture=neutral, PublicKeyToken=null]], System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Path 'ThirdRepoList.$type', line 13, position 129.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, String qualifiedTypeName)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(JsonReader reader, Type& objectType, JsonContract& contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue, Object& newValue, String& id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Dalamud.Configuration.Internal.DalamudConfiguration.Load(String path) in C:\goatsoft\companysecrets\dalamud\Configuration\Internal\DalamudConfiguration.cs:line 361
2022-06-13 18:30:06.559 +08:00 [INF] Waiting for 4000ms before starting a session.
2022-06-13 18:30:10.560 +08:00 [INF] --------------------------------------------------------------------------------
2022-06-13 18:30:10.560 +08:00 [INF] Initializing a session..
2022-06-13 18:30:10.776 +08:00 [INF] [SVC] Registered Dalamud.Dalamud into service locator privately
2022-06-13 18:30:10.776 +08:00 [INF] [SVC] Registered Dalamud.DalamudStartInfo into service locator privately
2022-06-13 18:30:10.776 +08:00 [INF] [SVC] Registered Dalamud.Configuration.Internal.DalamudConfiguration into service locator privately
2022-06-13 18:30:10.776 +08:00 [INF] Starting a session..
2022-06-13 18:30:10.777 +08:00 [INF] [SVC] Registered Dalamud.IoC.Internal.ServiceContainer into service locator privately
2022-06-13 18:30:10.784 +08:00 [INF] [SVC] Registered Dalamud.Game.SigScanner into service locator and exposed to plugins
2022-06-13 18:30:10.784 +08:00 [INF] [SVC] Registered Dalamud.Hooking.Internal.HookManager into service locator privately
2022-06-13 18:30:10.784 +08:00 [INF] [SVC] Registered Dalamud.Fixes.GameFixes into service locator privately
2022-06-13 18:30:10.788 +08:00 [INF] Applying WndProcNullRefFix at 7FF74F1A7270 with o1 7FF75108C5B8, o2 7FF751070AB0
2022-06-13 18:30:13.134 +08:00 [INF] [T1] FFXIVClientStructs initialized!
2022-06-13 18:30:13.142 +08:00 [INF] [SVC] Registered Dalamud.Game.Framework into service locator and exposed to plugins
2022-06-13 18:30:13.142 +08:00 [INF] [T1] Framework OK!
```

**Comment by NotNite** [comment]
(For future reference - this is the wrong repository. Please report future Dalamud issues in [goatcorp/Dalamud](https://github.com/goatcorp/Dalamud).)

Your config file definitely is messed up - try removing or renaming it at `%AppData%/XIVLauncher/dalamudConfig.json`.
