### ISSUE TITLE
XIVLauncher unable to launch

### ISSUE THREAD

**Issue by creeganmi** [goatcorp/FFXIVQuickLauncher#1033]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Cannot launch game in XIVLauncher but can without launcher. There are no errors or updating showing, but it shows up in task manager without anything popping up.

Tried troubleshooting doing this following:

Closed FFXIV / XIVLauncher

1. Went to %appdata%\xivlauncher (appdata\roaming\xivlauncher)
2. Deleted the addon and dalamudAssets folders
3. Opened XIVLauncher
4. Try to launch
5. Was unable to launch

Putting output file in relevant log output

Operating System: Windows 11
Launching as admin?: NO
Using Steam?: NO
Addons/Plugins enabled: yes

### Platform

Windows

### Relevant log output

```shell
2022-06-17 12:17:14.102 -04:00 [INF] [HOOKS] DelayInitializeMs: 0
2022-06-17 12:20:20.997 -04:00 [INF] Trying to set up Loc for language code en
2022-06-17 12:20:21.015 -04:00 [INF] XIVLauncher started as xivlauncher-6.2.40.0-6.2.40-0-gdb12d85
2022-06-17 12:20:21.015 -04:00 [INF] Starting update check...
2022-06-17 12:20:22.018 -04:00 [INF] Engaging Autologin...
2022-06-17 12:20:22.027 -04:00 [INF] [DUPDATE] Starting...
2022-06-17 12:20:22.205 -04:00 [INF] [DUPDATE] Using release version (6.4.0.26)
2022-06-17 12:20:22.311 -04:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.17
2022-06-17 12:20:22.818 -04:00 [INF] XivGame::Login(steamServiceAccount:false, cache:false)
2022-06-17 12:20:22.990 -04:00 [INF] [DUPDATE] All set for 2022.05.27.0000.0000
2022-06-17 12:20:23.958 -04:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-06-17 12:20:25.220 -04:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-06-17 12:20:25.222 -04:00 [INF] XivGame::LaunchGame(steamServiceAccount:False, args:)
2022-06-17 12:20:25.223 -04:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:1299968 ticks:1299968 key:1245184
2022-06-17 12:20:25.228 -04:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"p"
2022-06-17 12:20:25.230 -04:00 [INF] [HOOKS] DalamudLauncher::Run(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English")
2022-06-17 12:20:25.230 -04:00 [INF] [HOOKS] DelayInitializeMs: 0
2022-06-17 12:20:46.832 -04:00 [ERR] StartGameAndError resulted in an exception.
XIVLauncher.Common.Dalamud.DalamudRunnerException: Error trying to start Dalamud. ---> XIVLauncher.Common.Dalamud.DalamudRunnerException: An internal Dalamud error has occured
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 17
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 105
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 268
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext()
2022-06-17 12:20:46.841 -04:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xN1QxMjoyMDo0Ni44Mzc3NjM4LTA0OjAwIiwiSW5mbyI6IlhJVkxhdW5jaGVyLkNvbW1vbi5EYWxhbXVkLkRhbGFtdWRSdW5uZXJFeGNlcHRpb246IEVycm9yIHRyeWluZyB0byBzdGFydCBEYWxhbXVkLiAtLS0+IFhJVkxhdW5jaGVyLkNvbW1vbi5EYWxhbXVkLkRhbGFtdWRSdW5uZXJFeGNlcHRpb246IEFuIGludGVybmFsIERhbGFtdWQgZXJyb3IgaGFzIG9jY3VyZWRcclxuICAgYXQgWElWTGF1bmNoZXIuQ29tbW9uLldpbmRvd3MuV2luZG93c0RhbGFtdWRSdW5uZXIuUnVuKEZpbGVJbmZvIHJ1bm5lciwgQm9vbGVhbiBmYWtlTG9naW4sIEZpbGVJbmZvIGdhbWVFeGUsIFN0cmluZyBnYW1lQXJncywgSURpY3Rpb25hcnlgMiBlbnZpcm9ubWVudCwgRGFsYW11ZExvYWRNZXRob2QgbG9hZE1ldGhvZCwgRGFsYW11ZFN0YXJ0SW5mbyBzdGFydEluZm8pIGluIEM6XFxnb2F0c29mdFxceGxcXFhJVkxhdW5jaGVyLkNvbW1vbi5XaW5kb3dzXFxXaW5kb3dzRGFsYW11ZFJ1bm5lci5jczpsaW5lIDE3XHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBYSVZMYXVuY2hlci5Db21tb24uV2luZG93cy5XaW5kb3dzRGFsYW11ZFJ1bm5lci5SdW4oRmlsZUluZm8gcnVubmVyLCBCb29sZWFuIGZha2VMb2dpbiwgRmlsZUluZm8gZ2FtZUV4ZSwgU3RyaW5nIGdhbWVBcmdzLCBJRGljdGlvbmFyeWAyIGVudmlyb25tZW50LCBEYWxhbXVkTG9hZE1ldGhvZCBsb2FkTWV0aG9kLCBEYWxhbXVkU3RhcnRJbmZvIHN0YXJ0SW5mbykgaW4gQzpcXGdvYXRzb2Z0XFx4bFxcWElWTGF1bmNoZXIuQ29tbW9uLldpbmRvd3NcXFdpbmRvd3NEYWxhbXVkUnVubmVyLmNzOmxpbmUgMTA1XHJcbiAgIGF0IFhJVkxhdW5jaGVyLkNvbW1vbi5EYWxhbXVkLkRhbGFtdWRMYXVuY2hlci5SdW4oRmlsZUluZm8gZ2FtZUV4ZSwgU3RyaW5nIGdhbWVBcmdzLCBJRGljdGlvbmFyeWAyIGVudmlyb25tZW50KSBpbiBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXERhbGFtdWRcXERhbGFtdWRMYXVuY2hlci5jczpsaW5lIDg1XHJcbiAgIGF0IFhJVkxhdW5jaGVyLkNvbW1vbi5HYW1lLkxhdW5jaGVyLkxhdW5jaEdhbWUoSUdhbWVSdW5uZXIgcnVubmVyLCBTdHJpbmcgc2Vzc2lvbklkLCBJbnQzMiByZWdpb24sIEludDMyIGV4cGFuc2lvbkxldmVsLCBCb29sZWFuIGlzU3RlYW1TZXJ2aWNlQWNjb3VudCwgU3RyaW5nIGFkZGl0aW9uYWxBcmd1bWVudHMsIERpcmVjdG9yeUluZm8gZ2FtZVBhdGgsIEJvb2xlYW4gaXNEeDExLCBDbGllbnRMYW5ndWFnZSBsYW5ndWFnZSwgQm9vbGVhbiBlbmNyeXB0QXJndW1lbnRzLCBEcGlBd2FyZW5lc3MgZHBpQXdhcmVuZXNzKSBpbiBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXEdhbWVcXExhdW5jaGVyLmNzOmxpbmUgMjY4XHJcbiAgIGF0IFhJVkxhdW5jaGVyLldpbmRvd3MuVmlld01vZGVsLk1haW5XaW5kb3dWaWV3TW9kZWwuPFN0YXJ0R2FtZUFuZEFkZG9uPmRfXzMwLk1vdmVOZXh0KClcclxuLS0tIEVuZCBvZiBzdGFjayB0cmFjZSBmcm9tIHByZXZpb3VzIGxvY2F0aW9uIHdoZXJlIGV4Y2VwdGlvbiB3YXMgdGhyb3duIC0tLVxyXG4gICBhdCBTeXN0ZW0uUnVudGltZS5FeGNlcHRpb25TZXJ2aWNlcy5FeGNlcHRpb25EaXNwYXRjaEluZm8uVGhyb3coKVxyXG4gICBhdCBYSVZMYXVuY2hlci5XaW5kb3dzLlZpZXdNb2RlbC5NYWluV2luZG93Vmlld01vZGVsLjxUcnlQcm9jZXNzTG9naW5SZXN1bHQ+ZF9fMjUuTW92ZU5leHQoKSBpbiBEOlxcYVxcRkZYSVZRdWlja0xhdW5jaGVyXFxGRlhJVlF1aWNrTGF1bmNoZXJcXHNyY1xcWElWTGF1bmNoZXJcXFdpbmRvd3NcXFZpZXdNb2RlbFxcTWFpbldpbmRvd1ZpZXdNb2RlbC5jczpsaW5lIDYwMSIsIkNvbnRleHQiOiJTdGFydEdhbWVBbmRFcnJvciByZXN1bHRlZCBpbiBhbiBleGNlcHRpb24uIn0=
```

**Comment by creeganmi** [comment]
resolved - had to update xivalexander
