### ISSUE TITLE
dalamudUI.ini not being created / written into.

### ISSUE THREAD

**Issue by Rooois** [goatcorp/FFXIVQuickLauncher#1036]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

XIVlauncher refuses to create dalamudUI.ini or overwrite one created manually. I believe it's due to my Windows username having an " ł " special character. 
I tried making a new admin account named "  testł " downloading XIVlauncher running it without plugins and same behavior was observed eg. dalamudUI.ini not being created.
Then to further exclude a problem with my setup I made a third windows admin account named "testui" without any special characters. Installed launcher, launched the game and dalamudUI.ini was created and successfully written into.

There's an error that appears in dalamud.log when the file is missing, but after manually creating it disappears.

Let me know if you need any more info.

### Platform

Windows

### Relevant log output

```shell
2022-06-18 08:58:50.859 +02:00 [ERR] Could not delete dalamudUI.ini
System.IO.FileNotFoundException: Could not find file 'C:\Users\Michał\AppData\Roaming\XIVLauncher\dalamudUI.ini'.
File name: 'C:\Users\Michał\AppData\Roaming\XIVLauncher\dalamudUI.ini'
   at System.IO.FileInfo.get_Length()
   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr swapChain, UInt32 syncInterval, UInt32 presentFlags) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 514
2022-06-18 08:58:50.896 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wNi0xOFQwODo1ODo1MC44OTIzMTE3KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5JTy5GaWxlTm90Rm91bmRFeGNlcHRpb246IENvdWxkIG5vdCBmaW5kIGZpbGUgJ0M6XFxVc2Vyc1xcTWljaGHFglxcQXBwRGF0YVxcUm9hbWluZ1xcWElWTGF1bmNoZXJcXGRhbGFtdWRVSS5pbmknLlxyXG5GaWxlIG5hbWU6ICdDOlxcVXNlcnNcXE1pY2hhxYJcXEFwcERhdGFcXFJvYW1pbmdcXFhJVkxhdW5jaGVyXFxkYWxhbXVkVUkuaW5pJ1xyXG4gICBhdCBTeXN0ZW0uSU8uRmlsZUluZm8uZ2V0X0xlbmd0aCgpXHJcbiAgIGF0IERhbGFtdWQuSW50ZXJmYWNlLkludGVybmFsLkludGVyZmFjZU1hbmFnZXIuUHJlc2VudERldG91cihJbnRQdHIgc3dhcENoYWluLCBVSW50MzIgc3luY0ludGVydmFsLCBVSW50MzIgcHJlc2VudEZsYWdzKSBpbiBDOlxcZ29hdHNvZnRcXGNvbXBhbnlzZWNyZXRzXFxkYWxhbXVkXFxJbnRlcmZhY2VcXEludGVybmFsXFxJbnRlcmZhY2VNYW5hZ2VyLmNzOmxpbmUgNTE0IiwiQ29udGV4dCI6IkNvdWxkIG5vdCBkZWxldGUgZGFsYW11ZFVJLmluaSJ9
```

**Comment by KazWolfe** [comment]
T/N: This appears to be an upstream ImGui issue, as it's not correctly passing the path:

![image](https://github.com/user-attachments/assets/87097b0e-b148-4617-b354-bff79ee6e065)
