### ISSUE TITLE
FFXIV Repair Error

### ISSUE THREAD

**Issue by ImaginaryFox** [goatcorp/FFXIVQuickLauncher#1038]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

ok, so my game came up with an error frequently (An unexpected error has occurred. Exiting FINAL FANTASY XIV 17) I checked around. There were no fixed solutions to this everyone suggested different ways I tried most of them. Sadly, I can't afford to uninstall and download the game again, especially since some folks said this doesn't solve the problem for sure. since I got the community launcher it started to hold on more till crash but I still do crash a lot. I tried for repair but got the following error that I wrote on the log output. if there is any other solution than uninstall I will look forward to it I hope downloading it again would be the last solution.

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 174
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 398
---> (Inner Exception #0) System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 174
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()<---

   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 370

Version: 6.2.40.0
Git Hash: 6.2.40-0-gdb12d85
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: F:\SteamLibrary 2\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment]
Could you please attach `%AppData/XIVLauncher/output.log` (and `patcher.log` if it exists)?

Also, does running an integrity check in the XIVLauncher settings work, or are both integrity check + repair broken?

**Comment by ImaginaryFox** [comment]
Running integrity works fine and suggests to me that some files are modified or corrupted and the game needs to be repaired via the launcher. and that error is when I try to repair it kinda gets broken halfway.


[patcher.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8938088/patcher.log)


[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8938084/output.log)

**Comment by Soreepeong** [comment]
This really is a case of game data files that are corrupt on the filesystem/disk level. While XL should be improved to display which file exactly is causing problems, meanwhile, you can try figuring out which file you have to delete, by trying to make copies of every file (or one at a time and then delete) and see which file is causing errors.

**Comment by ImaginaryFox** [comment]
> It's possible one of your patches that were downloaded got corrupted. While the launcher is closed, try renaming `%AppData%/XIVLauncher/patches` to `patches_bak`, and try a repair again.

There is no "Patches" file in the AppData, I can't find it.

**Comment by ImaginaryFox** [comment]
Guys since my character have traveled to a new region of the map the game constantly crashes when I try to log in with it. it would be great if you can help. I would prefer faster communication through discord or other platforms since this game is a subscription base and I am losing my since I got the game.

Thanks for all your effort, everyone.
@Soreepeong
@NotNite

**Comment by NotNite** [comment]
You can join our Discord server at [https://goat.place/](https://goat.place/).

**Comment by ImaginaryFox** [comment]
> You can join our Discord server at https://goat.place/.

I joined the channel ✨ 
@NotNite
