### ISSUE TITLE
Can not install Launcher

### ISSUE THREAD

**Issue by NikLNips** [goatcorp/FFXIVQuickLauncher#1048]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Trying to reinstall the Launcher, it shows I have nothing in the file and when I go to install this is what the Codelog says..... 

2022-06-28 01:25:56> Program: Starting Squirrel Updater: --install .
2022-06-28 01:25:56> Program: Starting install, writing to C:\Users\nikna\AppData\Local\SquirrelTemp
2022-06-28 01:25:56> Program: About to install to: C:\Users\nikna\AppData\Local\XIVLauncher
2022-06-28 01:25:56> IEnableLogger: Failed to copy Update.exe to C:\Users\nikna\AppData\Local\XIVLauncher\Update.exe: System.UnauthorizedAccessException: Access to the path 'C:\Users\nikna\AppData\Local\XIVLauncher\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
2022-06-28 01:25:56> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Users\nikna\AppData\Local\XIVLauncher\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Users\nikna\AppData\Local\XIVLauncher\Update.exe' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Squirrel.Update.Program.<>c__DisplayClass4_1.<Install>b__4()
   at Squirrel.Utility.LogIfThrows(IFullLogger This, LogLevel level, String message, Action block)
   at Squirrel.Utility.ErrorIfThrows(IEnableLogger This, Action block, String message)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---

### Platform

Windows

**Comment by reiichi001** [comment]
This looks like XIVLauncher's installation may be getting blocked by an overprotective antivirus.

It may help to whitelist/pre-emptively whitelist the files and folders listed in <https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone>

The current version of XIVLauncher is 6.2.43 and Dalamud is 6.4.0.31

**Comment by NotNite** [comment]
Closing due to inactivity. If you're still having issues, please reopen this issue.
