### ISSUE TITLE
XIV Launcher Crash on Startup

### ISSUE THREAD

**Issue by dc8585** [goatcorp/FFXIVQuickLauncher#1056]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Opened the program from the desktop shortcut and entered my OTP once prompted to do so.

### Platform

Windows

### Relevant log output

```shell
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 19
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 268
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 612

Version: 6.2.43.0
Git Hash: 6.2.43-0-ga2131bf
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\Games\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment]
Is this still happening? Can you upload `%AppData%/XIVLauncher/output.log`?

**Comment by PazTapas** [comment]
Hello, I am getting a similar crashing error. my output log shows the following:

2022-12-27 21:10:16.333 -05:00 [INF] ========================================================
2022-12-27 21:10:16.338 -05:00 [INF] Starting a session(v6.3.1.0 - 6.3.1-0-g989c891)
2022-12-27 21:10:16.677 -05:00 [INF] Trying to set up Loc for language code en
2022-12-27 21:10:31.804 -05:00 [INF] Starting update check...
2022-12-27 21:10:34.515 -05:00 [INF] Engaging Autologin...
2022-12-27 21:10:34.524 -05:00 [INF] [DUPDATE] Starting...
2022-12-27 21:10:34.792 -05:00 [INF] [DUPDATE] Using release version (7.3.4.0)
2022-12-27 21:10:39.657 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 6.0.6
2022-12-27 21:10:41.868 -05:00 [INF] [DUPDATE] All set for 2022.11.09.0000.0000
2022-12-27 21:10:46.142 -05:00 [INF] XivGame::Login(steamServiceAccount:true, cache:false)
2022-12-27 21:10:48.789 -05:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-12-27 21:10:51.600 -05:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-12-27 21:10:51.603 -05:00 [INF] XivGame::LaunchGame(steamServiceAccount:True, args:)
2022-12-27 21:10:51.604 -05:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:84203 ticks:84203 key:65536
2022-12-27 21:10:51.609 -05:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"X"
2022-12-27 21:10:51.611 -05:00 [INF] [HOOKS] DalamudLauncher::Run(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English")
2022-12-27 21:10:51.611 -05:00 [INF] [HOOKS] DelayInitializeMs: 0
2022-12-27 21:10:53.511 -05:00 [INF] [HOOKS] Started dalamud!
2022-12-27 21:10:53.631 -05:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMi0xMi0yN1QyMToxMDo1My42MzA2MDMxLTA1OjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6dHJ1ZSwiSXNVaWRDYWNoZSI6ZmFsc2UsIkRhbGFtdWRFbmFibGVkIjp0cnVlLCJEYWxhbXVkTG9hZE1ldGhvZCI6MCwiRGFsYW11ZEluamVjdGlvbkRlbGF5IjowLjAsIlN0ZWFtSW50ZWdyYXRpb24iOmZhbHNlLCJFbmNyeXB0QXJndW1lbnRzIjp0cnVlLCJMYXVuY2hlclZlcnNpb24iOiI2LjMuMS4wIiwiTGF1bmNoZXJIYXNoIjoiNi4zLjEtMC1nOTg5Yzg5MSIsIk9mZmljaWFsIjp0cnVlLCJEcGlBd2FyZW5lc3MiOjEsIlBsYXRmb3JtIjowLCJPYnNlcnZlZEdhbWVWZXJzaW9uIjoiMjAyMi4xMS4wOS4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MVZlcnNpb24iOiIyMDIyLjA5LjI5LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgyVmVyc2lvbiI6IjIwMjIuMDguMTYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDNWZXJzaW9uIjoiMjAyMi4wOC4xNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4NFZlcnNpb24iOiIyMDIyLjExLjA4LjAwMDAuMDAwMCIsIkJja01hdGNoIjp0cnVlLCJJbmRleEludGVncml0eSI6NX0=
2022-12-27 21:11:15.030 -05:00 [INF] Stopping addons...

**Comment by NotNite** [comment]
This issue isn't related to the snippet you posted of your log. Also, since OP hasn't responded, I'll be closing this issue.

If you need help, open a separate issue or join our Discord server.
