### ISSUE TITLE
"The patch installer ran into an error. Please report this error."

### ISSUE THREAD

**Issue by LastExceed** [goatcorp/FFXIVQuickLauncher#1057]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Tried to install the 6.18 patch

i know the announcement on discord said that this patch might be problematic, but it is explicitly telling me to report this error so i'm doing so anyway just in case

### Platform

Windows

### Relevant log output

output.log
```shell
2022-07-05 09:52:17.660 +02:00 [INF] Trying to set up Loc for language code en
2022-07-05 09:52:17.676 +02:00 [INF] XIVLauncher started as xivlauncher-6.2.43.0-6.2.43-0-ga2131bf
2022-07-05 09:52:17.677 +02:00 [INF] Starting update check...
2022-07-05 09:52:18.472 +02:00 [INF] Engaging Autologin...
2022-07-05 09:52:18.479 +02:00 [INF] [DUPDATE] Starting...
2022-07-05 09:52:18.622 +02:00 [INF] [DUPDATE] Using release version (6.4.0.31)
2022-07-05 09:52:18.739 +02:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.17
2022-07-05 09:52:19.484 +02:00 [INF] [DUPDATE] All set for 2022.05.27.0000.0000
2022-07-05 09:52:19.529 +02:00 [INF] XivGame::Login(steamServiceAccount:true, cache:false)
2022-07-05 09:52:20.974 +02:00 [INF] FFFF8694
2022-07-05 09:52:20.975 +02:00 [INF] [STEAM] time: 1657007520, bfKey: 62c3eda0#un@e=x>, rawTicket.Length: 541, ticketSum: 34452, fuckedSum: 875661030, seed: -1656984780, numRandomBytes: 1
2022-07-05 09:52:23.331 +02:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:4
2022-07-05 09:52:28.589 +02:00 [INF] [PATCHERIPC] Starting patcher with 'XLPatchercb2b8bf3-e82c-42a9-ad7b-9de0e7621204'
2022-07-05 09:52:28.828 +02:00 [INF] [SHMEMRPC] IPC(1): {"$type":"XIVLauncher.Common.PatcherIpc.PatcherIpcEnvelope, XIVLauncher.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","OpCode":0,"Data":"2022-07-05T09:52:28.7245209+02:00"}
2022-07-05 09:52:28.833 +02:00 [INF] [PATCHERIPC] GOT HELLO
2022-07-05 09:52:30.166 +02:00 [INF] Downloading patch 2022.06.16.0000.0001 at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.16.0000.0001.patch to C:\Users\LastExceed\AppData\Roaming\XIVLauncher\patches\game\4e9a232b\D2022.06.16.0000.0001.patch
2022-07-05 09:52:30.166 +02:00 [INF] Downloading patch 2022.06.21.0000.0000 at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.21.0000.0000.patch to C:\Users\LastExceed\AppData\Roaming\XIVLauncher\patches\game\4e9a232b\D2022.06.21.0000.0000.patch
2022-07-05 09:52:30.166 +02:00 [INF] Downloading patch 2022.06.17.0000.0000 at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.17.0000.0000.patch to C:\Users\LastExceed\AppData\Roaming\XIVLauncher\patches\game\4e9a232b\D2022.06.17.0000.0000.patch
2022-07-05 09:52:59.372 +02:00 [INF] Patch at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.17.0000.0000.patch downloaded completely
2022-07-05 09:52:59.372 +02:00 [INF] CheckIsDone!!
2022-07-05 09:53:00.869 +02:00 [INF] Patch at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.21.0000.0000.patch downloaded completely
2022-07-05 09:53:00.869 +02:00 [INF] CheckIsDone!!
2022-07-05 09:53:03.397 +02:00 [INF] Patch at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.16.0000.0001.patch downloaded completely
2022-07-05 09:53:03.397 +02:00 [INF] CheckIsDone!!
2022-07-05 09:53:03.397 +02:00 [INF] All patches downloaded.
2022-07-05 09:53:03.690 +02:00 [INF] Starting patch install for 2022.06.16.0000.0001 at http://patch-dl.ffxiv.com/game/4e9a232b/D2022.06.16.0000.0001.patch(0)
2022-07-05 09:53:09.369 +02:00 [INF] [SHMEMRPC] IPC(3): {"$type":"XIVLauncher.Common.PatcherIpc.PatcherIpcEnvelope, XIVLauncher.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","OpCode":5,"Data":null}
```

patcher.log
```
2022-07-05 09:52:28.703 +02:00 [INF] [PATCHER] IPC connected
2022-07-05 09:52:28.839 +02:00 [INF] [PATCHER] sent hello
2022-07-05 09:53:03.704 +02:00 [INF] [SHMEMRPC] IPC(2): {"$type":"XIVLauncher.Common.PatcherIpc.PatcherIpcEnvelope, XIVLauncher.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","OpCode":2,"Data":{"$type":"XIVLauncher.Common.PatcherIpc.PatcherIpcStartInstall, XIVLauncher.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null","PatchFile":{"$type":"System.IO.FileInfo, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","OriginalPath":"C:\\Users\\LastExceed\\AppData\\Roaming\\XIVLauncher\\patches\\game\\4e9a232b\\D2022.06.16.0000.0001.patch","FullPath":"C:\\Users\\LastExceed\\AppData\\Roaming\\XIVLauncher\\patches\\game\\4e9a232b\\D2022.06.16.0000.0001.patch"},"Repo":1,"VersionId":"2022.06.16.0000.0001","GameDirectory":{"$type":"System.IO.DirectoryInfo, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089","OriginalPath":"C:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XIV Online","FullPath":"C:\\SteamLibrary\\steamapps\\common\\FINAL FANTASY XIV Online"},"KeepPatch":false}}
2022-07-05 09:53:04.132 +02:00 [INF] [PATCHER] Installing C:\Users\LastExceed\AppData\Roaming\XIVLauncher\patches\game\4e9a232b\D2022.06.16.0000.0001.patch to C:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game
2022-07-05 09:53:09.356 +02:00 [ERR] [PATCHER] Patch install failed
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Patching.ZiPatch.Util.SqexFileStreamStore.Dispose() in C:\goatsoft\xl\XIVLauncher.Common\Patching\ZiPatch\Util\SqexFileStreamStore.cs:line 27
   at XIVLauncher.Common.Patching.RemotePatchInstaller.InstallPatch(String patchPath, String gamePath) in C:\goatsoft\xl\XIVLauncher.Common\Patching\RemotePatchInstaller.cs:line 186
   at XIVLauncher.Common.Patching.RemotePatchInstaller.RunInstallQueue() in C:\goatsoft\xl\XIVLauncher.Common\Patching\RemotePatchInstaller.cs:line 128
2022-07-05 09:53:39.663 +02:00 [INF] Exited due to failure
```

**Comment by LastExceed** [comment]
i forgot to universal #1 rule of debugging. restarting my pc fixed the problem. sry to waste your time
