### ISSUE TITLE
Crashing at the character select screen

### ISSUE THREAD

**Issue by LunarGarden** [goatcorp/FFXIVQuickLauncher#1061]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I went to another data center using data center travel, it crashed my game after I did an alliance raid. I tried to log in and it worked up to the character select screen. I tried to fix it by removing every plug in I had and nothing. I removed it and reinstalled it but same issue. It works when Quicklauncher isnt being run or any plug ins are being run. 

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 485
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<MoveFile>d__35.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<MoveUnnecessaryFiles>d__81.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 434

Version: 6.2.43.0
Git Hash: 6.2.43-0-ga2131bf
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\Steam\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by LunarGarden** [comment]
I'm running it on windows 10 and I'm not too sure. That's what the repair
tool says and I'm as confused as you.

**Comment by NotNite** [comment]
Please attach `%AppData%/XIVLauncher/dalamud.log`.

**Comment by NotNite** [comment]
Closing due to inactivity. If you're still having issues, please reopen this issue.
