### ISSUE TITLE
Not sure what is happening

### ISSUE THREAD

**Issue by Dehlmost** [goatcorp/FFXIVQuickLauncher#1072]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried to log in. Something wanted to update got an Error. Unsure what caused it

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.UnauthorizedAccessException: Access to the path 'D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game\game\4e9a232b' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at XIVLauncher.Common.Game.Patch.PatchManager.GetPatchFile(PatchListEntry patch) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 498
   at XIVLauncher.Common.Game.Patch.PatchManager.<DownloadPatchAsync>d__40.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Patch.PatchManager.<>c__DisplayClass42_0.<<RunDownloadQueue>b__2>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 365
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game\game\4e9a232b' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at XIVLauncher.Common.Game.Patch.PatchManager.GetPatchFile(PatchListEntry patch) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 498
   at XIVLauncher.Common.Game.Patch.PatchManager.<DownloadPatchAsync>d__40.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Patch.PatchManager.<>c__DisplayClass42_0.<<RunDownloadQueue>b__2>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 365<---


Version: 6.2.43.0
Git Hash: 6.2.43-0-ga2131bf
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment]
This is a permissions issue - not an issue on our side.

P.S. - This looks like you've set the patch download dir to your actual game install - this isn't how it's supposed to work. This folder is where patches get temporarily downloaded to update the game. See the "Patching" tab in the XIVLauncher settings.
