### ISSUE TITLE
xivlauncher CTD and crash

### ISSUE THREAD

**Issue by Torbenbear** [goatcorp/FFXIVQuickLauncher#1081]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Had to reset my laptop, now every time the game opens I get a C000005 error. Suspecting its an integrity issue, I used integrity checker in XIVlauncher, but then it seems to have stopped and crashed?

### Platform

Windows

### Relevant log output

```shell
An error in XIVLauncher occurred. Please consult the FAQ. If this issue persists, please report
it on GitHub by clicking the button below, describing the issue and copying the text in the box.

Error during early initialization. Please report this error.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Steam\steamapps\common\FINAL FANTASY XIV Online\game\gshade-shaders'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 107
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 270
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Steam\steamapps\common\FINAL FANTASY XIV Online\game\gshade-shaders'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 107
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 270
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.DirectoryNotFoundException: Could not find a part of the path 'D:\Steam\steamapps\common\FINAL FANTASY XIV Online\game\gshade-shaders'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 107
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 142
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 94
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268<---
<---
```

**Comment by Torbenbear** [comment]
done, then I opened the game and it asked me to allow it to change GShade install to work better, then this happened. 
![image](https://user-images.githubusercontent.com/109984746/180849554-8a17b677-406c-44ec-b4b8-9480d1226ac1.png)
trying to retrieve the dump file it said was there but my Roaming folder only had Intel in it..

**Comment by NotNite** [comment]
Please try a repair by right clicking Login in XIVLauncher > Repair game.

**Comment by Torbenbear** [comment]
![image](https://user-images.githubusercontent.com/109984746/180864810-eb9ee3e6-bc68-424a-9082-4034731c4f30.png)
finally verified everything, and Gshade seems to be a trouble, I wonder how to proceed from here?

**Comment by NotNite** [comment]
Repair automatically moves files that don't come with the game - you can get them back from that folder, or reinstall GShade again.

**Comment by Torbenbear** [comment]
so i've ran the Gshade uninstaller, then reinstalled, then trying to open the game
![image](https://user-images.githubusercontent.com/109984746/181249735-7e5b7d8e-febe-4d0b-bbe8-8836bdf9ba06.png)
I clicked yes
and we're back
![image](https://user-images.githubusercontent.com/109984746/181249937-f168d9ec-05b0-489f-8362-6f5ae3d9b42a.png)

**Comment by Torbenbear** [comment]
it just occured to me I just never reinstalled textools after resetting, trying to do that first..

**Comment by NotNite** [comment]
Just checking - does this happen on the official launcher?

**Comment by Torbenbear** [comment]
![image](https://user-images.githubusercontent.com/109984746/181251691-c23db797-226a-4b13-bf56-d9f8306bc6d7.png)
![image](https://user-images.githubusercontent.com/109984746/181252491-1e9dad10-34b4-4657-b7c3-a66dba51821b.png)
![image](https://user-images.githubusercontent.com/109984746/181252524-5d9855c5-c50e-45eb-b517-eb6cbf8626a6.png)

at this stage I'm betting the game itself is corrupted and i might do better if I reinstall the thing, but then again i've no idea

**Comment by NotNite** [comment]
You might want to try a reinstall, yeah. Given that this is happening on the official launcher, it's not an XIVLauncher bug, so I'll be closing this issue. Good luck with your issue - make sure to also update your GPU drivers.
