### ISSUE TITLE
XIV Launcher Error

### ISSUE THREAD

**Issue by astaraaa** [goatcorp/FFXIVQuickLauncher#1082]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I did the integrity test and tried to repair the game like instructed and the issue keeps popping up

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.IO.IOException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\gshade-shaders\Textures' is denied.
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound, WIN32_FIND_DATA& data)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 486
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<MoveFile>d__35.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<MoveUnnecessaryFiles>d__81.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 276
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 434

Version: 6.2.43.0
Git Hash: 6.2.43-0-ga2131bf
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment]
Your GShade install seems to be messed up, which is tripping up XIVLauncher. Maybe a reinstall of GShade?
