### ISSUE TITLE
Item already added apparently

### ISSUE THREAD

**Issue by TyroThunderdrone** [goatcorp/FFXIVQuickLauncher#1089]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Updated the launcher

### Platform

Windows

### Relevant log output

```shell
System.ArgumentException: Item has already been added. Key in dictionary: 'Path'  Key being added: 'PATH'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 52
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 85
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 268
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 616

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by TyroThunderdrone** [comment]
Tyro#0281 on discord
