### ISSUE TITLE
Error while applying GameFix

### ISSUE THREAD

**Issue by hendy643** [goatcorp/FFXIVQuickLauncher#1102]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Install game using the Cross-Platofrm launcher.

Run as normal.
   
happens on Manjaro Linux using the AUR version, and on Ubuntu 22.04.1 using the flatpak version.

Manually downloaded and applied the fixes, it still tries to apply the fixes.

### Platform

Linux (native)

### Wine/Proton runner version

wine-xiv-staging-fsync-git-7.7.r14.gd7507fbe

### Relevant log output

```shell
[11:49:47 INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:/home/<USERNAME>/.xlcore/ffxiv)
[11:49:47 VRB] Running in prefix: /home/<USERNAME>/.xlcore/compatibilitytool/beta/wine-xiv-staging-fsync-git-7.7.r14.gd7507fbe/bin/wine64 cmd /c dir %userprofile%/Documents > nul
[11:49:59 ERR] Couldn't ensure compatibility tool
System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at XIVLauncher.Common.Util.HttpClientDownloadWithProgress.DownloadFileFromHttpResponseMessage(HttpResponseMessage response) in C:/goatsoft/xl/XIVLauncher.Common/Util/HttpClientWithProgress.cs:line 36
   at XIVLauncher.Common.Util.HttpClientDownloadWithProgress.Download(Nullable`1 timeout) in C:/goatsoft/xl/XIVLauncher.Common/Util/HttpClientWithProgress.cs:line 31
   at XIVLauncher.Common.Unix.Compatibility.GameFixes.Implementations.MacVideoFix.Apply() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/GameFixes/Implementations/MacVideoFix.cs:line 37
   at XIVLauncher.Common.Unix.Compatibility.GameFixes.GameFixApply.Run() in C:/goatsoft/xl/XIVLauncher.Common.Unix/Compatibility/GameFixes/GameFixApply.cs:line 30
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass21_0.<<StartGameAndAddon>b__1>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 726
   --- End of inner exception stack trace ---
[11:49:59 ERR] StartGameAndError resulted in an exception.
System.Exception: Could not obtain Process Handle
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 392
[11:49:59 ERR] Task failed
System.AggregateException: One or more errors occurred. (Could not obtain Process Handle)
 ---> System.Exception: Could not obtain Process Handle
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 392
   at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 195
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 138
   --- End of inner exception stack trace ---
```

**Comment by NotNite** [comment]
I believe this URL is now outdated - we have a workaround pinned in our Discord server (sorry for making you join it - https://goat.place/). Keeping this open to track a fix.

**Comment by srhb** [comment]
I can't find any pinned messages with a workaround -- any chance of a copy/paste? :)

**Comment by NotNite** [comment]
Sure: *ahem*

Note: Terminal commands assume default paths and settings. Please adjust accordingly.

1. Go to where your FFXIV install is and then enter the game/movie/ffxiv folder.
```bash
cd ~/.xlcore/ffxiv/game/movie/ffxiv
```
2. Download <https://mac-dl.ffxiv.com/cw/finalfantasyxiv-1.0.8.zip>
```bash
curl https://mac-dl.ffxiv.com/cw/finalfantasyxiv-1.0.8.zip -o finalfantasyxiv-1.0.8.zip
```
3. Extract the 4 `bk2` files from `finalfantasyxiv-1.0.8.zip/FINAL FANTASY XIV ONLINE.app/Contents/SharedSupport/finalfantasyxiv/support/published_Final_Fantasy/drive_c/Program Files (x86)/SquareEnix/FINAL FANTASY XIV - A Realm Reborn/game/movie/ffxiv` using your choice of unzip utilities
```bash
unzip -j finalfantasyxiv-1.0.8.zip  "FINAL FANTASY XIV ONLINE.app/Contents/SharedSupport/finalfantasyxiv/support/published_Final_Fantasy/drive_c/Program Files (x86)/SquareEnix/FINAL
FANTASY XIV - A Realm Reborn/game/movie/ffxiv/*.bk2"
```
4. Place these files into `<ffxiv gamepath>/game/movie/ffxiv/`. There should be a bink video video file for each wmv-encoded dat file.
```bash
mv *.bk2 ffxivgamepath/game/movies/ffxiv/
```
5. Make a blank file called `.fixed` in the `<ffxiv gamepath>/game/movie/ffxiv/` folder. (Only needed for xlcore 1.0.0.9 and earlier)
```bash
touch .fixed
```
6. Cleanup anything you don't need
```bash
rm finalfantasyxiv-1.0.8.zip
```

**Comment by srhb** [comment]
@NotNite Works like a charm, thank you. I had gotten the .bk2 files but missed the .fixed marker.

**Comment by darkralts** [comment]
![Image](https://github.com/user-attachments/assets/d4c42bf0-c06c-498e-8c06-1b5ce782795c)

hello im getting an error like this,
