### ISSUE TITLE
"Could not get STORED." while trying to launch with Steam account

### ISSUE THREAD

**Issue by sirkhancision** [goatcorp/FFXIVQuickLauncher#1104]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Distro: Arch Linux
Kernel: 5.19.1.zen1-1

Steps to reproduce error:

- Step 1: Open XIVLauncher
- Step 2: Try to launch the game, using Steam service along with XIVLauncher.
- Step 3: Error is thrown while waiting for it to log in.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

wine-xiv-staging-fsync-git-7.10.r3.g560db77d

### Relevant log output

```shell
2022-08-14 11:33:14.979 -03:00 [ERR] Could not login to game
XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
   at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 476
   at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 529
   at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
   at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 255
2022-08-14 11:33:14.989 -03:00 [ERR] Task failed
System.AggregateException: One or more errors occurred. (Could not get STORED.)
 ---> XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
   at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 476
   at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 529
   at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
   at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 255
   at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 193
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 138
   --- End of inner exception stack trace ---
```

**Comment by tommadness** [comment]
There is an issue currently between Square Enix and Valve. All Steam Service accounts are affected on both XIVLauncher and the official launcher.

**Comment by sirkhancision** [comment]
> There is an issue currently between Square Enix and Valve. All Steam Service accounts are affected on both XIVLauncher and the official launcher.

Damn, that sucks. Hope it gets fixed soon.
