### ISSUE TITLE
Error on XIVLauncher

### ISSUE THREAD

**Issue by Senichita** [goatcorp/FFXIVQuickLauncher#1123]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I clicked the check integrity of files and I got this error.

### Platform

Windows

### Relevant log output

```shell
An error in XIVLauncher occurred. Please consult the FAQ. If this issue persists, please report
it on GitHub by clicking the button below, describing the issue and copying the text in the box.

Error during early initialization. Please report this error.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'D:\Games\mmc-stable-win32\MultiMC\instances\Enigmatica 6 - E6 - 1.16.5\minecraft\mods' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 112
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 270
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'D:\Games\mmc-stable-win32\MultiMC\instances\Enigmatica 6 - E6 - 1.16.5\minecraft\mods' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 112
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 270
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'D:\Games\mmc-stable-win32\MultiMC\instances\Enigmatica 6 - E6 - 1.16.5\minecraft\mods' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 112
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 157
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 99
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 268<---
<---
```

**Comment by shanemwebster** [comment]
Looking through your dump, it appears to be a path access issue. 
> System.UnauthorizedAccessException: Access to the path 'D:\Games\mmc-stable-win32\MultiMC\instances\Enigmatica 6 - E6 - 1.16.5\minecraft\mods' is denied.

Are permissions properly set to access said location referenced above?

**Comment by NotNite** [comment]
...What is that path? You clearly have something in XIVLauncher misconfigured if *any* directory is pointed to the mods folder of a MultiMC instance.
