### ISSUE TITLE
Attempted to Repair Game, stuck in loop

### ISSUE THREAD

**Issue by CravenRavenUS** [goatcorp/FFXIVQuickLauncher#1125]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Attempted to repair FFXIV through XIVLauncher, pressing try again results in same error popping back up. 

### Platform

Windows

### Relevant log output

```shell
System.OverflowException: Array dimensions exceeded supported range.
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchTargetFile.ReadFrom(BinaryReader reader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchTargetFile.cs:line 225
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchTargetFile..ctor(BinaryReader reader, Boolean disposeReader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchTargetFile.cs:line 27
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndex..ctor(BinaryReader reader, Boolean disposeReader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndex.cs:line 43
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 329

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by NotNite** [comment]
This seems like an invalid patch file - does this happen if you clear/move the `%AppData%/XIVLauncher/patches` directory?

**Comment by CravenRavenUS** [comment]
That appears to have done the trick, thank you.
