### ISSUE TITLE
FFXIV isn't working well since 6.2 and now XIVLauncher is giving me an error as well

### ISSUE THREAD

**Issue by cakemusume** [goatcorp/FFXIVQuickLauncher#1130]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hi, I realize this is probably an error with my game and not with xivlauncher, but it was working with the xivlauncher previously, and I already reinstalled the game twice and can't make it work so I thought maybe I could get some help here.

Since 6.2 launch, I'd login at the normal launcher, and when I'd press play, the game window would be black, not loading for no matter how long I waited, and if I clicked it, it would appear as not responding, so I'd need to close it.
I tried using the launcher options at the Advanced Settings, "Reset System Settings" and "Restore Game Date". It didn't work. So I tried reinstalling the game. Since I'd be getting the "Unable to download patch files [30413][25008][10009]" every 1,5GB I downloaded, I tried a free VPN, chancing DNS, checking Internet Explorer permissions, but nothing would make the error disappear, so I downloaded XIVLauncher. 
Once the download completed, I tried to launch by the normal launcher, and the same black screen error kept occurring. But launching the game through xivlauncher made it open. I did that several times.
Fast-forward to this Tuesday, we had a new update. I downloaded it through xivlauncher. And then the black screen error started occurring in it too, together with the errors I'm pasting at the "log output".
I reinstalled the game once again, deleted all the files from my computer so I'd have a clean start. Reinstalled xivlauncher as well. The error kept happening with the normal launcher, but I managed to get it open through xivlauncher once, yesterday. Today, nothing, black screen and not responding, and the two errors. 
I don't know what else to do.

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): O identificador da janela é inválido
em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32
uMsgFilterMin, Int32 uMsgFilterMax)
em System.Windows.Threading. Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32
minMessage, Int32 maxMessage)
em System.Windows.Threading. Dispatcher.PushFramelmpl(DispatcherFrame frame)
em System.Windows.Application.RunDispatcher(Object ignore)
em System.Windows.Application.RunInternal(Window window)
em XIVLauncher.App.Main()

AND ALSO

System.ComponentModel.Win32Exception (0x80004005): 0 identificador da janela é inválido
em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32
uMsgFilterMin, Int32 uMsgFilterMax)
em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32
minMessage, Int32 maxMessage)
em System.Windows.Threading.Dispatcher.PushFramelmpl(DispatcherFrame frame)
em XIVLauncher.App.DalamudOverlayThreadStart() na D:\a\FFXIVQuickLauncher
\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:linha 270
em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext,
ContextCallback callback, Object state, Boolean preserveSyncCtx)
em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
callback, Object state, Boolean preserveSyncCtx)
em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback
callback, Object state)
em System.Threading.ThreadHelper.ThreadStart()
```

**Comment by tedosuji** [comment]
Similarly for me, XIVLauncher is kind of working...

If I attempt to click anywhere on the launcher, it crashes and closes. If I don't click anywhere on it, I can enter my OTP and successfully get to the game.

However, my problems continue with Dalamud not loading or working. I tried removing cache problems by removing the XIVLauncher in Roaming, but no dalamud.log is made, I think it fails on injection for me.

output.log
`2022-08-31 14:41:10.707 -07:00 [INF] Trying to set up Loc for language code en
2022-08-31 14:41:10.772 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-08-31 14:41:10.774 -07:00 [INF] Starting update check...
2022-08-31 14:41:19.620 -07:00 [INF] Trying to set up Loc for language code en
2022-08-31 14:41:19.688 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-08-31 14:41:19.690 -07:00 [INF] Starting update check...
2022-08-31 14:41:50.501 -07:00 [INF] MainWindow initialized.
2022-08-31 14:41:50.630 -07:00 [INF] [DUPDATE] Starting...
2022-08-31 14:41:50.947 -07:00 [INF] [DUPDATE] Using release version (7.0.0.1)
2022-08-31 14:41:50.957 -07:00 [INF] [DUPDATE] Not found, redownloading
2022-08-31 14:41:51.144 -07:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMi0wOC0zMVQxNDo0MTo1MS4xMzY3MTE3LTA3OjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6ZmFsc2UsIklzVWlkQ2FjaGUiOmZhbHNlLCJEYWxhbXVkRW5hYmxlZCI6dHJ1ZSwiRGFsYW11ZExvYWRNZXRob2QiOjEsIkRhbGFtdWRJbmplY3Rpb25EZWxheSI6MC4wLCJTdGVhbUludGVncmF0aW9uIjpmYWxzZSwiRW5jcnlwdEFyZ3VtZW50cyI6dHJ1ZSwiTGF1bmNoZXJWZXJzaW9uIjoiNi4yLjQ0LjAiLCJMYXVuY2hlckhhc2giOiI2LjIuNDQtMC1nOWYwYjhkZCIsIk9mZmljaWFsIjp0cnVlLCJEcGlBd2FyZW5lc3MiOjEsIlBsYXRmb3JtIjoxLCJPYnNlcnZlZEdhbWVWZXJzaW9uIjoiMjAyMi4wOC4yNS4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MVZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgyVmVyc2lvbiI6IjIwMjIuMDguMTYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDNWZXJzaW9uIjoiMjAyMi4wOC4xNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4NFZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIkJja01hdGNoIjp0cnVlLCJJbmRleEludGVncml0eSI6NX0=
2022-08-31 14:41:51.884 -07:00 [INF] [DUPDATE] Now starting for .NET Runtime 6.0.6
2022-08-31 14:41:52.434 -07:00 [ERR] [DUPDATE] Integrity check failed
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\users\scoot\AppData\Roaming\XIVLauncher\runtime\host\fxr\5.0.17\hostfxr.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at XIVLauncher.Common.Dalamud.DalamudUpdater.CheckIntegrity(DirectoryInfo directory, String hashesJson) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudUpdater.cs:line 339
2022-08-31 14:41:52.440 -07:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOC0zMVQxNDo0MTo1Mi40Mzg5NzEyLTA3OjAwIiwiSW5mbyI6IlN5c3RlbS5JTy5EaXJlY3RvcnlOb3RGb3VuZEV4Y2VwdGlvbjogQ291bGQgbm90IGZpbmQgYSBwYXJ0IG9mIHRoZSBwYXRoICdDOlxcdXNlcnNcXHNjb290XFxBcHBEYXRhXFxSb2FtaW5nXFxYSVZMYXVuY2hlclxccnVudGltZVxcaG9zdFxcZnhyXFw1LjAuMTdcXGhvc3RmeHIuZGxsJy5cclxuICAgYXQgU3lzdGVtLklPLl9fRXJyb3IuV2luSU9FcnJvcihJbnQzMiBlcnJvckNvZGUsIFN0cmluZyBtYXliZUZ1bGxQYXRoKVxyXG4gICBhdCBTeXN0ZW0uSU8uRmlsZVN0cmVhbS5Jbml0KFN0cmluZyBwYXRoLCBGaWxlTW9kZSBtb2RlLCBGaWxlQWNjZXNzIGFjY2VzcywgSW50MzIgcmlnaHRzLCBCb29sZWFuIHVzZVJpZ2h0cywgRmlsZVNoYXJlIHNoYXJlLCBJbnQzMiBidWZmZXJTaXplLCBGaWxlT3B0aW9ucyBvcHRpb25zLCBTRUNVUklUWV9BVFRSSUJVVEVTIHNlY0F0dHJzLCBTdHJpbmcgbXNnUGF0aCwgQm9vbGVhbiBiRnJvbVByb3h5LCBCb29sZWFuIHVzZUxvbmdQYXRoLCBCb29sZWFuIGNoZWNrSG9zdClcclxuICAgYXQgU3lzdGVtLklPLkZpbGVTdHJlYW0uLmN0b3IoU3RyaW5nIHBhdGgsIEZpbGVNb2RlIG1vZGUsIEZpbGVBY2Nlc3MgYWNjZXNzLCBGaWxlU2hhcmUgc2hhcmUpXHJcbiAgIGF0IFhJVkxhdW5jaGVyLkNvbW1vbi5EYWxhbXVkLkRhbGFtdWRVcGRhdGVyLkNoZWNrSW50ZWdyaXR5KERpcmVjdG9yeUluZm8gZGlyZWN0b3J5LCBTdHJpbmcgaGFzaGVzSnNvbikgaW4gQzpcXGdvYXRzb2Z0XFx4bFxcWElWTGF1bmNoZXIuQ29tbW9uXFxEYWxhbXVkXFxEYWxhbXVkVXBkYXRlci5jczpsaW5lIDMzOSIsIkNvbnRleHQiOiJbRFVQREFURV0gSW50ZWdyaXR5IGNoZWNrIGZhaWxlZCJ9
2022-08-31 14:41:52.440 -07:00 [INF] [DUPDATE] Not found, outdated or no integrity: 5.0.6 - 6.0.6
2022-08-31 14:41:59.781 -07:00 [INF] [DUPDATE] All set for 2022.08.25.0000.0000
2022-08-31 14:42:03.443 -07:00 [INF] XivGame::Login(steamServiceAccount:false, cache:false)
2022-08-31 14:42:04.292 -07:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-08-31 14:42:05.272 -07:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-08-31 14:42:05.275 -07:00 [INF] XivGame::LaunchGame(steamServiceAccount:False, args:)
2022-08-31 14:42:05.276 -07:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:22334498 ticks:22334498 key:22282240
2022-08-31 14:42:05.280 -07:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"G"
2022-08-31 14:42:05.282 -07:00 [INF] [HOOKS] DalamudLauncher::Run(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English")
2022-08-31 14:42:05.283 -07:00 [INF] [HOOKS] DelayInitializeMs: 0
2022-08-31 14:43:02.580 -07:00 [INF] Trying to set up Loc for language code en
2022-08-31 14:43:02.596 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-08-31 14:43:02.597 -07:00 [INF] Starting update check...
2022-08-31 14:43:07.988 -07:00 [INF] Trying to set up Loc for language code en
2022-08-31 14:43:08.003 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-08-31 14:43:08.005 -07:00 [INF] Starting update check...
2022-08-31 14:43:09.309 -07:00 [INF] Engaging Autologin...
2022-08-31 14:43:09.317 -07:00 [INF] [DUPDATE] Starting...
2022-08-31 14:43:09.665 -07:00 [INF] [DUPDATE] Using release version (7.0.0.1)
2022-08-31 14:43:09.764 -07:00 [INF] [DUPDATE] Now starting for .NET Runtime 6.0.6
2022-08-31 14:43:10.742 -07:00 [INF] [DUPDATE] All set for 2022.08.25.0000.0000
2022-08-31 14:43:15.611 -07:00 [INF] XivGame::Login(steamServiceAccount:false, cache:false)
2022-08-31 14:43:16.441 -07:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-08-31 14:43:17.509 -07:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-08-31 14:43:17.512 -07:00 [INF] XivGame::LaunchGame(steamServiceAccount:False, args:)
2022-08-31 14:43:17.514 -07:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:22406736 ticks:22406736 key:22347776
2022-08-31 14:43:17.521 -07:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"t"
2022-08-31 14:43:17.523 -07:00 [INF] [HOOKS] DalamudLauncher::Run(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English")
2022-08-31 14:43:17.524 -07:00 [INF] [HOOKS] DelayInitializeMs: 0`

dalamud.injector.log
`2022-08-31 14:43:18.227 -07:00 [INF] Using start info: {"WorkingDirectory":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\addon\\Hooks\\7.0.0.1","ConfigurationPath":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\dalamudConfig.json","PluginDirectory":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\installedPlugins","DefaultPluginDirectory":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\devPlugins","AssetDirectory":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\dalamudAssets\\119","Language":1,"GameVersion":"2022.08.25.0000.0000","DelayInitializeMs":0,"NoLoadPlugins":false,"NoLoadThirdPartyPlugins":false,"BootLogPath":"C:\\users\\scoot\\AppData\\Roaming\\XIVLauncher\\addon\\Hooks\\7.0.0.1\\..\\..\\..\\dalamud.boot.log","BootShowConsole":false,"BootDisableFallbackConsole":false,"BootWaitMessageBox":0,"BootWaitDebugger":false,"BootVehEnabled":true,"BootVehFull":false,"BootEnableEtw":false,"BootDotnetOpenProcessHookMode":0,"BootEnabledGameFixes":["prevent_devicechange_crashes","disable_game_openprocess_access_check","redirect_openprocess","backup_userdata_save","clr_failfast_hijack"],"BootUnhookDlls":null}`

**Comment by tedosuji** [comment]
An update to the process from output.log, I found another issue where they suggest to delete the runtime folder. I did that and restarted XIVLauncher, and this output came out

```
2022-09-01 23:53:22.920 -07:00 [INF] Trying to set up Loc for language code en
2022-09-01 23:53:22.935 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-09-01 23:53:22.937 -07:00 [INF] Starting update check...
2022-09-01 23:53:24.497 -07:00 [INF] MainWindow initialized.
2022-09-01 23:53:24.656 -07:00 [INF] [DUPDATE] Starting...
2022-09-01 23:53:28.084 -07:00 [INF] Trying to set up Loc for language code en
2022-09-01 23:53:28.100 -07:00 [INF] XIVLauncher started as xivlauncher-6.2.44.0-6.2.44-0-g9f0b8dd
2022-09-01 23:53:28.101 -07:00 [INF] Starting update check...
2022-09-01 23:53:29.503 -07:00 [INF] MainWindow initialized.
2022-09-01 23:53:29.676 -07:00 [INF] [DUPDATE] Starting...
2022-09-01 23:53:29.982 -07:00 [INF] [DUPDATE] Using release version (7.0.0.2)
2022-09-01 23:53:30.064 -07:00 [INF] [DUPDATE] Now starting for .NET Runtime 6.0.6
2022-09-01 23:53:30.787 -07:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMi0wOS0wMVQyMzo1MzozMC43NzkyNDk1LTA3OjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6ZmFsc2UsIklzVWlkQ2FjaGUiOmZhbHNlLCJEYWxhbXVkRW5hYmxlZCI6dHJ1ZSwiRGFsYW11ZExvYWRNZXRob2QiOjEsIkRhbGFtdWRJbmplY3Rpb25EZWxheSI6MC4wLCJTdGVhbUludGVncmF0aW9uIjpmYWxzZSwiRW5jcnlwdEFyZ3VtZW50cyI6dHJ1ZSwiTGF1bmNoZXJWZXJzaW9uIjoiNi4yLjQ0LjAiLCJMYXVuY2hlckhhc2giOiI2LjIuNDQtMC1nOWYwYjhkZCIsIk9mZmljaWFsIjp0cnVlLCJEcGlBd2FyZW5lc3MiOjEsIlBsYXRmb3JtIjoxLCJPYnNlcnZlZEdhbWVWZXJzaW9uIjoiMjAyMi4wOC4yNS4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MVZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgyVmVyc2lvbiI6IjIwMjIuMDguMTYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDNWZXJzaW9uIjoiMjAyMi4wOC4xNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4NFZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIkJja01hdGNoIjp0cnVlLCJJbmRleEludGVncml0eSI6NX0=
2022-09-01 23:53:31.003 -07:00 [ERR] [DUPDATE] Integrity check failed
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\users\scoot\AppData\Roaming\XIVLauncher\runtime\host\fxr\5.0.17\hostfxr.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at XIVLauncher.Common.Dalamud.DalamudUpdater.CheckIntegrity(DirectoryInfo directory, String hashesJson) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudUpdater.cs:line 339
2022-09-01 23:53:31.010 -07:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMi0wOS0wMVQyMzo1MzozMS4wMDkzNDMyLTA3OjAwIiwiSW5mbyI6IlN5c3RlbS5JTy5EaXJlY3RvcnlOb3RGb3VuZEV4Y2VwdGlvbjogQ291bGQgbm90IGZpbmQgYSBwYXJ0IG9mIHRoZSBwYXRoICdDOlxcdXNlcnNcXHNjb290XFxBcHBEYXRhXFxSb2FtaW5nXFxYSVZMYXVuY2hlclxccnVudGltZVxcaG9zdFxcZnhyXFw1LjAuMTdcXGhvc3RmeHIuZGxsJy5cclxuICAgYXQgU3lzdGVtLklPLl9fRXJyb3IuV2luSU9FcnJvcihJbnQzMiBlcnJvckNvZGUsIFN0cmluZyBtYXliZUZ1bGxQYXRoKVxyXG4gICBhdCBTeXN0ZW0uSU8uRmlsZVN0cmVhbS5Jbml0KFN0cmluZyBwYXRoLCBGaWxlTW9kZSBtb2RlLCBGaWxlQWNjZXNzIGFjY2VzcywgSW50MzIgcmlnaHRzLCBCb29sZWFuIHVzZVJpZ2h0cywgRmlsZVNoYXJlIHNoYXJlLCBJbnQzMiBidWZmZXJTaXplLCBGaWxlT3B0aW9ucyBvcHRpb25zLCBTRUNVUklUWV9BVFRSSUJVVEVTIHNlY0F0dHJzLCBTdHJpbmcgbXNnUGF0aCwgQm9vbGVhbiBiRnJvbVByb3h5LCBCb29sZWFuIHVzZUxvbmdQYXRoLCBCb29sZWFuIGNoZWNrSG9zdClcclxuICAgYXQgU3lzdGVtLklPLkZpbGVTdHJlYW0uLmN0b3IoU3RyaW5nIHBhdGgsIEZpbGVNb2RlIG1vZGUsIEZpbGVBY2Nlc3MgYWNjZXNzLCBGaWxlU2hhcmUgc2hhcmUpXHJcbiAgIGF0IFhJVkxhdW5jaGVyLkNvbW1vbi5EYWxhbXVkLkRhbGFtdWRVcGRhdGVyLkNoZWNrSW50ZWdyaXR5KERpcmVjdG9yeUluZm8gZGlyZWN0b3J5LCBTdHJpbmcgaGFzaGVzSnNvbikgaW4gQzpcXGdvYXRzb2Z0XFx4bFxcWElWTGF1bmNoZXIuQ29tbW9uXFxEYWxhbXVkXFxEYWxhbXVkVXBkYXRlci5jczpsaW5lIDMzOSIsIkNvbnRleHQiOiJbRFVQREFURV0gSW50ZWdyaXR5IGNoZWNrIGZhaWxlZCJ9
2022-09-01 23:53:31.011 -07:00 [INF] [DUPDATE] Not found, outdated or no integrity: 5.0.6 - 6.0.6
2022-09-01 23:53:33.997 -07:00 [INF] [DUPDATE] All set for 2022.08.25.0000.0000
2022-09-01 23:53:51.968 -07:00 [INF] XivGame::Login(steamServiceAccount:false, cache:false)
2022-09-01 23:53:52.930 -07:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2022-09-01 23:53:53.980 -07:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn)
2022-09-01 23:53:53.982 -07:00 [INF] XivGame::LaunchGame(steamServiceAccount:False, args:)
2022-09-01 23:53:53.983 -07:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:59530202 ticks:59530202 key:59506688
2022-09-01 23:53:53.987 -07:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"4"
2022-09-01 23:53:53.989 -07:00 [INF] [HOOKS] DalamudLauncher::Run(gp:C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English")
2022-09-01 23:53:53.989 -07:00 [INF] [HOOKS] DelayInitializeMs: 0
```

I believe the issue is with 
`System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\users\scoot\AppData\Roaming\XIVLauncher\runtime\host\fxr\5.0.17\hostfxr.dll'.`

Upon recreation of the runtime folder and creating these caches, it creates ...\fxr\6.0.6\... instead of 5.0.17 that it's looking for

**Comment by reiichi001** [comment]
@cakemusume Hello! Are you still encountering the issue? The current version of XIVLauncher should not be looking for .Net 5 at all, as we've moved to .Net 6. 

On Windows, we've seen this get stuck for some users. What's worked previously is to go into XIVLauncher's settings -> Dalamud tab, and then switch the injection method being used. (Ideally, everyone should be on the new endpoint method, but switching to legacy and back will also work).

----
@tedosuji 
If you're using Lutris, you would want to have stated you're on Linux, as that does change how we troubleshoot this issue.  Lutris is not a program you can run on Windows or macOS. The issue you're experiencing is separate from the one by the original poster.

Starting with FFXIV Patch 6.2, Dalamud has moved to .Net 6, which is not compatible with Wine 7.1 or 7.2. You'll need to switch to a newer wine runner in Lutris such as `lutris-GE-Proton7-24-x86_64`. If using a custom wine runner or system wine, please make sure it's based on Wine 7.10 or later, or all .Net 6 programs will crash.

**Comment by tedosuji** [comment]
> @cakemusume Hello! Are you still encountering the issue? The current version of XIVLauncher should not be looking for .Net 5 at all, as we've moved to .Net 6.
> 
> On Windows, we've seen this get stuck for some users. What's worked previously is to go into XIVLauncher's settings -> Dalamud tab, and then switch the injection method being used. (Ideally, everyone should be on the new endpoint method, but switching to legacy and back will also work).
> 
> @tedosuji If you're using Lutris, you would want to have stated you're on Linux, as that does change how we troubleshoot this issue. Lutris is not a program you can run on Windows or macOS. The issue you're experiencing is separate from the one by the original poster.
> 
> Starting with FFXIV Patch 6.2, Dalamud has moved to .Net 6, which is not compatible with Wine 7.1 or 7.2. You'll need to switch to a newer wine runner in Lutris such as `lutris-GE-Proton7-24-x86_64`. If using a custom wine runner or system wine, please make sure it's based on Wine 7.10 or later, or all .Net 6 programs will crash.

I am terribly sorry for mixing up threads, would you like me to create a new issue or remove my reply? I was super tired when posting my replies so definitely poor decision on my end. I will give your advice a shot and see what happens

**Comment by cakemusume** [comment]
> @cakemusume Hello! Are you still encountering the issue? The current version of XIVLauncher should not be looking for .Net 5 at all, as we've moved to .Net 6.
> 
> On Windows, we've seen this get stuck for some users. What's worked previously is to go into XIVLauncher's settings -> Dalamud tab, and then switch the injection method being used. (Ideally, everyone should be on the new endpoint method, but switching to legacy and back will also work).
> 
> @tedosuji If you're using Lutris, you would want to have stated you're on Linux, as that does change how we troubleshoot this issue. Lutris is not a program you can run on Windows or macOS. The issue you're experiencing is separate from the one by the original poster.
> 
> Starting with FFXIV Patch 6.2, Dalamud has moved to .Net 6, which is not compatible with Wine 7.1 or 7.2. You'll need to switch to a newer wine runner in Lutris such as `lutris-GE-Proton7-24-x86_64`. If using a custom wine runner or system wine, please make sure it's based on Wine 7.10 or later, or all .Net 6 programs will crash.

Thanks for the reply! I'm not sure since when but the error did stop happening! I'm still having the black screen error on the game, but usually only the first time I try to open it, and it does open fine on the second try. I'm happy as long as it opens so... lol

**Comment by tedosuji** [comment]
> 
> @tedosuji If you're using Lutris, you would want to have stated you're on Linux, as that does change how we troubleshoot this issue. Lutris is not a program you can run on Windows or macOS. The issue you're experiencing is separate from the one by the original poster.
> 
> Starting with FFXIV Patch 6.2, Dalamud has moved to .Net 6, which is not compatible with Wine 7.1 or 7.2. You'll need to switch to a newer wine runner in Lutris such as `lutris-GE-Proton7-24-x86_64`. If using a custom wine runner or system wine, please make sure it's based on Wine 7.10 or later, or all .Net 6 programs will crash.

This was the solution - downloading a new runner in lutris and switching to lutris-GE-Proton7-27-x86_64 worked for me. Thank you so much
