### ISSUE TITLE
Crash after updating to 6.2 update of textools mods

### ISSUE THREAD

**Issue by rioberto14** [goatcorp/FFXIVQuickLauncher#1131]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

XIVLauncher decided to randomly not work when I had enabled my textool mods after 6.2 patch. 

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.IO.IOException: The process cannot access the file because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileInfo.MoveTo(String destFileName)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 485
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<MoveFile>d__35.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 325
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<MoveUnnecessaryFiles>d__81.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 279
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 437

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by reiichi001** [comment]
XIVLauncher is unable to patch the game if another program has locked the game files in use (Textools, ACT, and TeamCraft do this).

That said, Textools will corrupt your FFXIV install by its very design and usage. You may like to consider moving over to Penumbra, which is a plugin-based mod loader that doesn't touch the game files. That makes it safer during updates as you no long have to play the "backup, start over, ~~sacrifice a virgin goat to the pagan gods~~, pray to your diety of choice, and cross your fingers that all is well" game to remove mods safely before updating FFXIV. ...only to reapply them have to to repeat that process every update.

**Comment by reiichi001** [comment]
Hello! Wanted to check if you're all sorted, or if you still need assistance. Please let us know.

**Comment by rioberto14** [comment]
sorry, been a bit busy but yeah i got it worked and decided to use penumbra rather than tt. your info helped a lot, ty
