### ISSUE TITLE
Error while attempting to verify/repair files using the XIVlauncher

### ISSUE THREAD

**Issue by vbarreiro** [goatcorp/FFXIVQuickLauncher#1132]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I has having issues with Mare Synchrinios. 

I attempted to repair files via the XIVlauncher to get rid of anything textools-related, and got this bug after verification was at 2/5

I then went into the ordinary launcher and re-downlaoded all patch files. Same error. 

### Platform

Windows

### Relevant log output

```shell
System.IO.InvalidDataException: Found invalid data while decoding.
   at System.IO.Compression.InflaterZlib.Inflate(FlushCode flushCode)
   at System.IO.Compression.InflaterZlib.ReadInflateOutput(Byte[] outputBuffer, Int32 offset, Int32 length, FlushCode flushCode, Int32& bytesRead)
   at System.IO.Compression.InflaterZlib.Inflate(Byte[] bytes, Int32 offset, Int32 length)
   at System.IO.Compression.DeflateStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndex..ctor(BinaryReader reader, Boolean disposeReader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndex.cs:line 35
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 329

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment]
Try deleting `%AppData%/XIVLauncher/patches`.

**Comment by vbarreiro** [comment]
I can’t find such a folder. Do you mean “packages”?

**Comment by NotNite** [comment]
Roaming, not Local.

**Comment by Soreepeong** [comment]
Try clearing the folder `%appdata%\XIVLauncher\patchMeta` instead. It looks like the verify reference data has been corrupted.

**Comment by reiichi001** [comment]
Hello! Wanted to check if you're all sorted, or if you still need assistance. Please let us know.
