### ISSUE TITLE
dalamud-tspack-b64 is not a command line argument

### ISSUE THREAD

**Issue by ChaosInfinited** [goatcorp/FFXIVQuickLauncher#1147]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hello, 
I've updated my QuickLauncher yesterday, now it refuses to launch the game due to incorrect command line argument with `--dalamud-tspack-b64`
Using Garuda(Arch) Linux, with Fish shell
I'm using this AUR: https://aur.archlinux.org/packages/xivlauncher-git

Censored that SE auth token (I think) - `-- //**sqex00xxxx4YeQ**A**//`

It does work on stable build https://aur.archlinux.org/packages/xivlauncher which is not using `dalamud-tspack-b64` arg

### Launcher version

1.0.1.0-4-gda2de825

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

wine-xiv-staging-fsync-git-7.10.r3.g560db77d

### Relevant log output

```shell
[21:41:34 VRB] Running in prefix: /home/chaos/.xlcore/compatibilitytool/beta/wine-xiv-staging-fsync-git-7.10.r3.g560db77d/bin/wine64 "/home/chaos/.xlcore/dalamud/Hooks/7.0.0.7/Dalamud.Injector.exe" launch --mode=inject --game="Z:\home\chaos\.xlcore\ffxiv\game\ffxiv_dx11.exe" --dalamud-working-directory="Z:\home\chaos\.xlcore\dalamud\Hooks\7.0.0.7" --dalamud-configuration-path="Z:\home\chaos\.xlcore\dalamudConfig.json" --dalamud-plugin-directory="Z:\home\chaos\.xlcore\installedPlugins" --dalamud-dev-plugin-directory="Z:\home\chaos\.xlcore\devPlugins" --dalamud-asset-directory="Z:\home\chaos\.xlcore\dalamudAssets\122" --dalamud-client-language=1 --dalamud-delay-initialize=0 --dalamud-tspack-b64=eyJXaGVuIjoiMjAyMi0wOS0xNVQyMTo0MTozMy4zMDI5NTA3KzAyOjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6dHJ1ZSwiSXNVaWRDYWNoZSI6ZmFsc2UsIkRhbGFtdWRFbmFibGVkIjp0cnVlLCJEYWxhbXVkTG9hZE1ldGhvZCI6MSwiRGFsYW11ZEluamVjdGlvbkRlbGF5IjowLjAsIlN0ZWFtSW50ZWdyYXRpb24iOmZhbHNlLCJFbmNyeXB0QXJndW1lbnRzIjp0cnVlLCJMYXVuY2hlclZlcnNpb24iOiIxLjAuMS4wIiwiTGF1bmNoZXJIYXNoIjoiMS4wLjEuMC00LWdkYTJkZTgyNSIsIk9mZmljaWFsIjpmYWxzZSwiRHBpQXdhcmVuZXNzIjoxLCJQbGF0Zm9ybSI6MCwiT2JzZXJ2ZWRHYW1lVmVyc2lvbiI6IjIwMjIuMDkuMDcuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDFWZXJzaW9uIjoiMjAyMi4wOS4wNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MlZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgzVmVyc2lvbiI6IjIwMjIuMDguMTYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDRWZXJzaW9uIjoiMjAyMi4wOS4wNi4wMDAwLjAwMDAiLCJCY2tNYXRjaCI6dHJ1ZSwiSW5kZXhJbnRlZ3JpdHkiOjV9 -- //**sqex00xxxx4YeQ**A**//
gamemodeauto: 

Command line error: "--dalamud-tspack-b64=eyJXaGVuIjoiMjAyMi0wOS0xNVQyMTo0MTozMy4zMDI5NTA3KzAyOjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6dHJ1ZSwiSXNVaWRDYWNoZSI6ZmFsc2UsIkRhbGFtdWRFbmFibGVkIjp0cnVlLCJEYWxhbXVkTG9hZE1ldGhvZCI6MSwiRGFsYW11ZEluamVjdGlvbkRlbGF5IjowLjAsIlN0ZWFtSW50ZWdyYXRpb24iOmZhbHNlLCJFbmNyeXB0QXJndW1lbnRzIjp0cnVlLCJMYXVuY2hlclZlcnNpb24iOiIxLjAuMS4wIiwiTGF1bmNoZXJIYXNoIjoiMS4wLjEuMC00LWdkYTJkZTgyNSIsIk9mZmljaWFsIjpmYWxzZSwiRHBpQXdhcmVuZXNzIjoxLCJQbGF0Zm9ybSI6MCwiT2JzZXJ2ZWRHYW1lVmVyc2lvbiI6IjIwMjIuMDkuMDcuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDFWZXJzaW9uIjoiMjAyMi4wOS4wNi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MlZlcnNpb24iOiIyMDIyLjA4LjE2LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgzVmVyc2lvbiI6IjIwMjIuMDguMTYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDRWZXJzaW9uIjoiMjAyMi4wOS4wNi4wMDAwLjAwMDAiLCJCY2tNYXRjaCI6dHJ1ZSwiSW5kZXhJbnRlZ3JpdHkiOjV9" is not a command line argument.

[21:41:34 ERR] StartGameAndError resulted in an exception.
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Unix.UnixDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, Boolean noPlugins, Boolean noThirdPlugins, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixDalamudRunner.cs:line 98
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/DalamudLauncher.cs:line 130
   at XIVLauncher.Common.Unix.UnixGameRunner.Start(String path, String workingDirectory, String arguments, IDictionary`2 environment, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixGameRunner.cs:line 27
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 268
   at XIVLauncher.Core.Components.MainPage.MainPage.StartGameAndAddon(LoginResult loginResult, Boolean isSteam, Boolean forceNoDalamud, Boolean noThird) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 764
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 376
[21:41:34 ERR] Task failed
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Common.Unix.UnixDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, Boolean noPlugins, Boolean noThirdPlugins, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixDalamudRunner.cs:line 98
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/DalamudLauncher.cs:line 130
   at XIVLauncher.Common.Unix.UnixGameRunner.Start(String path, String workingDirectory, String arguments, IDictionary`2 environment, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixGameRunner.cs:line 27
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 268
   at XIVLauncher.Core.Components.MainPage.MainPage.StartGameAndAddon(LoginResult loginResult, Boolean isSteam, Boolean forceNoDalamud, Boolean noThird) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 764
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 376
   at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 197
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 140
   --- End of inner exception stack trace ---
```

**Comment by reiichi001** [comment]
It's due to https://github.com/goatcorp/FFXIVQuickLauncher/pull/1144 being merged. The AUR is going to pull the latest source, but this launcher change needs to be accompanied by a Dalamud change that's not live yet. 

You either need to target an older commit and redo the PKGBUILD or you could use the flatpak in the meantime until Dalamud is updated.

**Comment by ChaosInfinited** [comment]
I see! Thank you, for now I've switched to stable AUR and it works as a charm, closing!
