### ISSUE TITLE
Could Not Get Stored

### ISSUE THREAD

**Issue by cookiejar5081** [goatcorp/FFXIVQuickLauncher#1151]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I've got my XIVLauncher running on my Steam Deck. I installed it on a super fast SD card. 
Followed the instructions step by step. Installed Flatseal, set that up to refer to the installation.
Started up the launcher. Set up the patch and other locations.

It keeps telling me 'Could Not Get Stored' after it downloaded patches and I'm trying to install.

### Platform

Linux (native)

**Comment by NotNite** [comment]
Can you please attach `~/.xlcore/logs/launcher.log`?

**Comment by michaelbutler** [comment]
I think this was a temporary Square Enix problem. I looked in my `launcher.log` for when this happened to me yesterday, and found an HTML dump and then right after the InvalidResponseException `Could not get STORED`. 

snippet:

```
...more HTML above this...
<div id="contents">
	<table class="mainContent topSpace1" style="width:256px">
		<tr>
			<td><div class="error1 fontsize1">エラーが発生しました。しばらくしてから再度お試しください。</div></td>
		</tr>
		<tr>
			<td><div class="error1 fontsize1">Es ist ein Fehler aufgetreten. Bitte versuche es später erneut.</div></td>
		</tr>
		<tr>
			<td><div class="error1 fontsize1">An error has occurred. Please try again later.</div></td>
		</tr>
		<tr>
			<td><div class="error1 fontsize1">Une erreur s'est produite. Veuillez réessayer ultérieurement.</div></td>
		</tr>
	</table>
	<div class="fontsize1">
		A technical issue has occurred.<br />Try accessing the site again. If the issue still has not been resolved, please contact the SQUARE ENIX Support Center.
		
	</div>

</div>

</body>
</html>

2022-09-21 17:13:20.628 -04:00 [ERR] Could not login to game
XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
   at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 477
   at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 530
   at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
   at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 259
2022-09-21 17:13:20.641 -04:00 [ERR] Task failed
System.AggregateException: One or more errors occurred. (Could not get STORED.)
 ---> XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
   at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 477
   at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 530
   at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
   at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 259
   at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 197
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 142
   --- End of inner exception stack trace ---
```

so likely SE returned an error page thus preventing login. It hasn't happened to me since.

**Comment by Guiltyblood** [comment]
> I think this was a temporary Square Enix problem. I looked in my `launcher.log` for when this happened to me yesterday, and found an HTML dump and then right after the InvalidResponseException `Could not get STORED`.
> 
> snippet:
> 
> ```
> ...more HTML above this...
> <div id="contents">
> 	<table class="mainContent topSpace1" style="width:256px">
> 		<tr>
> 			<td><div class="error1 fontsize1">エラーが発生しました。しばらくしてから再度お試しください。</div></td>
> 		</tr>
> 		<tr>
> 			<td><div class="error1 fontsize1">Es ist ein Fehler aufgetreten. Bitte versuche es später erneut.</div></td>
> 		</tr>
> 		<tr>
> 			<td><div class="error1 fontsize1">An error has occurred. Please try again later.</div></td>
> 		</tr>
> 		<tr>
> 			<td><div class="error1 fontsize1">Une erreur s'est produite. Veuillez réessayer ultérieurement.</div></td>
> 		</tr>
> 	</table>
> 	<div class="fontsize1">
> 		A technical issue has occurred.<br />Try accessing the site again. If the issue still has not been resolved, please contact the SQUARE ENIX Support Center.
> 		
> 	</div>
> 
> </div>
> 
> </body>
> </html>
> 
> 2022-09-21 17:13:20.628 -04:00 [ERR] Could not login to game
> XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
>    at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 477
>    at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 530
>    at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
>    at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 259
> 2022-09-21 17:13:20.641 -04:00 [ERR] Task failed
> System.AggregateException: One or more errors occurred. (Could not get STORED.)
>  ---> XIVLauncher.Common.Game.Exceptions.InvalidResponseException: Could not get STORED.
>    at XIVLauncher.Common.Game.Launcher.GetOauthTop(String url, Boolean isSteam) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 477
>    at XIVLauncher.Common.Game.Launcher.OauthLogin(String userName, String password, String otp, Boolean isFreeTrial, Boolean isSteam, Int32 region, Ticket steamTicket) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 530
>    at XIVLauncher.Common.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteam, Boolean useCache, DirectoryInfo gamePath, Boolean forceBaseVersion, Boolean isFreeTrial) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 171
>    at XIVLauncher.Core.Components.MainPage.MainPage.TryLoginToGame(String username, String password, String otp, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 259
>    at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 197
>    at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 142
>    --- End of inner exception stack trace ---
> ```
> 
> so likely SE returned an error page thus preventing login. It hasn't happened to me since.

So what do I do when this happens? Does this fix itself or do I need to remove the HTML dump? Sorry if this is a basic question as I do not know much about this stuff.

**Comment by Mentioum** [comment]
This is happening to me at the moment as well.

**Comment by reiichi001** [comment]
The "could not get stored" error is from SE's side of things, and not quite an issue on XIVLauncher's side so much as it's relaying the bad response from SE's servers to you.

It usually happens for a couple of reasons:
- your network is blocked from the official login service (try using the official launcher)
- your machine is not handling SSL connections properly (try using the official launcher)
- something about your computer's environment has broken XIVLauncher (confirm by seeing if the official launcher works)
- **For Steam Service Account Users Only**, your Steam session has expired. Please log out and login to Steam again.
- **For Steam Service Account Users Only**, it's Tuesday. Steam always does maintenance without notice on Tuesdays. (Occasionally, they may have downtimes during other times or day or days of the week. Try the step above to see if that works).

**Comment by SamiKalliomaki** [comment]
For me, I had to check "Free Trial Account" in the launcher settings.

**Comment by Nytrouz-official** [comment]
So the fix is just to wait and hope for the best? I could play a minute ago normaly but after a restart of the game i get this error Massage. When trying to verify the install i get the same error.

**Comment by BadMiscuit** [comment]
Same issue here. From XIVLauncher's logs, it gets 403 after XivGame::Login

**Comment by nathanctech** [comment]
This was an issue on SE's end and nothing that Dalamud could do to fix. [News post.](https://na.finalfantasyxiv.com/lodestone/news/detail/cb9a6e93cb91432b948068d24ad58643d9fabc03)
