### ISSUE TITLE
Dalamud not updating/working (Steam Deck)

### ISSUE THREAD

**Issue by Purple4789** [goatcorp/FFXIVQuickLauncher#1170]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

After following the guide and proceeding of launching the game via XivLauncher, The app get stuck in "Waiting for Dalamud to be ready."
After leaving it in that state for couple of hours, I decided to run the game without dalamud and it works fine.
![unknown](https://user-images.githubusercontent.com/7303728/194778227-b2bcfea7-29d6-4962-b32c-0c45f011908b.png)

### Platform

Linux (native)

### Wine/Proton runner version

Proton-GE-7.0

### Relevant log output

```shell
2022-10-09 21:59:55.487 +03:00 [INF] ========================================================
2022-10-09 21:59:55.587 +03:00 [INF] Starting a session(v1.0.1.0 - 6246fde)
2022-10-09 21:59:55.976 +03:00 [ERR] Could not init the keychain
KeySharp.KeyringException: The name org.freedesktop.secrets was not provided by any .service files (GenericError)
   at KeySharp.Keyring.ThrowLastError()
   at KeySharp.Keyring.SetPassword(String package, String service, String username, String password)
   at XIVLauncher.Core.Accounts.Secrets.Providers.KeychainSecretProvider.SetDummyAndCheck() in C:/goatsoft/xl/XIVLauncher.Core/Accounts/Secrets/Providers/KeychainSecretProvider.cs:line 30
2022-10-09 21:59:56.000 +03:00 [ERR] An org.freedesktop.secrets provider is not available - no secrets will be stored
2022-10-09 21:59:56.344 +03:00 [INF] [DUPDATE] Starting...
2022-10-09 21:59:56.350 +03:00 [DBG] Creating Veldrid devices...
2022-10-09 21:59:56.657 +03:00 [DBG] Veldrid OK!
2022-10-09 21:59:57.058 +03:00 [DBG] Fonts OK!
2022-10-09 21:59:57.110 +03:00 [DBG] ImGui OK!
2022-10-09 22:00:02.140 +03:00 [ERR] Could not check version
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at XIVLauncher.Core.UpdateCheck.CheckForUpdate() in C:/goatsoft/xl/XIVLauncher.Core/UpdateCheck.cs:line 16
2022-10-09 22:00:52.835 +03:00 [VRB] ShowGamepadTextInput: true
2022-10-09 22:00:59.503 +03:00 [VRB] Received OTP: 534674
2022-10-09 22:00:59.811 +03:00 [INF] XivGame::Login(steamServiceAccount:false, cache:true)
2022-10-09 22:00:59.814 +03:00 [INF] Cached UID found, using instead
2022-10-09 22:00:59.828 +03:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:/home/deck/.xlcore/ffxiv)
```

**Comment by Purple4789** [comment]
Probelm was due to Netgear routers having conflict with the steam deck.

Problem was solved by using ethernet from a docked USB C.
