### ISSUE TITLE
[Linux] Fatal assert; stalled cross-thread pipe (XIVLauncher does not start)

### ISSUE THREAD

**Issue by LianBg** [goatcorp/FFXIVQuickLauncher#1180]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hello there,

I have been successfully using XIVLauncher for **Artix Linux** for the past months, which is Arch without systemd, and never had any issues until now.

It was installed natively using the AUR, but both the _xivlauncher_ and the _xivlauncher-git_ packages have this issue.

After a recent update (unfortunately I do not remember which version it worked on last) however, I can no longer open XIVLauncher; it simply does not start.
Attempting to start it using a terminal emulator lets the keychain error roll by as usual, then it hangs for some ~10 seconds after initializing the SteamAPI, and finally prints the FatalAssert error messages and exits.

### Platform

Linux (native)

### Wine/Proton runner version

GE-Proton-7-37

### Relevant log output

```shell
[18:33:49 INF] ========================================================
[18:33:49 INF] Starting a session(v1.0.1.0 - 6.2.44-5-g6246fde6)
[18:33:49 ERR] Could not init the keychain
KeySharp.KeyringException: The name org.freedesktop.secrets was not provided by any .service files (GenericError)
   at KeySharp.Keyring.ThrowLastError()
   at KeySharp.Keyring.SetPassword(String package, String service, String username, String password)
   at XIVLauncher.Core.Accounts.Secrets.Providers.KeychainSecretProvider.SetDummyAndCheck() in C:/goatsoft/xl/XIVLauncher.Core/Accounts/Secrets/Providers/KeychainSecretProvider.cs:line 30
[18:33:49 ERR] An org.freedesktop.secrets provider is not available - no secrets will be stored
[S_API] SteamAPI_Init(): Loaded '/home/pilot/.local/share/Steam/linux64/steamclient.so' OK.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : fatal stalled cross-thread pipe.
src/common/pipes.cpp (883) : Fatal assert; application exiting
src/common/pipes.cpp (883) : Fatal assert; application exiting
No minidump written, nothing to upload.
_ExitOnFatalAssert
```

**Comment by LianBg** [comment]
Nevermind, I fixed it!

It is apparently an error message not of XIVLauncher, but of the SteamAPI/Steamworks itself. I simply restarted Steam and it worked again. The mistake was updating the system after starting Steam and expecting it to work without a restart.

Duh...
