### ISSUE TITLE
Game cannot start: Says drive is not ready or mapped

### ISSUE THREAD

**Issue by valoeaera** [goatcorp/FFXIVQuickLauncher#1194]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I installed the Launcher through Flathub and opened it when the installation finished. I tried to log in and start installing the game and I was informed my drive did not have enough space. I expected this, as my main drive is rather full. I think went into the settings to change it to my other, larger drive. I have ensured that the launcher should have permissions on this drive (777), however, when I press login,I get an error. "System.IO.DriveNotFoundException". When I tried to free up some space on my current drive and restart the download, I received the same error, but now applied to the original drive. I have not had issues writing and reading files form this drive in the past. I have also been using XIVlauncher on my windows machine for a few months without issues. The attached log is from the "Generate Troubleshooting Pack" option in the Settings. Please let me know if I need to submit anything else.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

wine-6.0.3 (Ubuntu 6.0.3~repack-1)

### Relevant log output

```shell
2022-11-11 18:04:41.263 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:05:36.526 -05:00 [ERR] Error during patching
System.IO.IOException: Not a directory
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:11:37.614 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:13:25.657 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:15:01.003 -05:00 [ERR] Error during patching
System.IO.IOException: Not a directory
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:16:14.606 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:16:40.903 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:17:41.482 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:17:45.512 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi/ffxiv'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
2022-11-11 18:18:23.295 -05:00 [ERR] Error during patching
System.IO.DriveNotFoundException: Could not find the drive '/media/valoeaera/linux-bigboi'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:/goatsoft/xl/XIVLauncher.Common/Util/PlatformHelpers.cs:line 145
   at XIVLauncher.Common.Game.Patch.PatchManager.PatchAsync(FileInfo aria2LogFile, Boolean external) in C:/goatsoft/xl/XIVLauncher.Common/Game/Patch/PatchManager.cs:line 125
   at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePatchAsync(Repository repository, PatchListEntry[] pendingPatches, String sid) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 984
```

**Comment by NotNite** [comment]
This is not a bug, this is a Flatpak permissions issue. Use something like Flatseal to grant permissions to your other drive.

**Comment by valoeaera** [comment]
Thank you so much. I'm a bit of a newbie when it comes to this kind of thing

**Comment by valoeaera** [comment]
I don't mean to be a bother, but I've given XIVlaucher all of the permissions Flatseal has (not intended to keep it that way, just as a sanity check) and I'm still getting the same error. Is there anything else that could cause this error?

**Comment by reiichi001** [comment]
Just to make sure, does that folder currently, exist on your drive? XIVLauncher.Core will not attempt to create the folder when it's manually specified.

**Comment by valoeaera** [comment]
@reiichi001 That seems to have been the issue. Thank you for your help!
