### ISSUE TITLE
Can't run with discrete card 

### ISSUE THREAD

**Issue by metincetin** [goatcorp/FFXIVQuickLauncher#1220]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Stopped working after I switch nvidia proprietary drivers. Performance is unbearable with nouveau.

### Platform

Linux (native)

### Relevant log output

```shell
Unhandled exception. Veldrid.VeldridException: Unable to create OpenGL Context: "Invalid window". This may indicate that the system does not support the requested OpenGL profile, version, or Swapchain format.
   at Veldrid.StartupUtilities.VeldridStartup.CreateDefaultOpenGLGraphicsDevice(GraphicsDeviceOptions options, Sdl2Window window, GraphicsBackend backend)
   at Veldrid.StartupUtilities.VeldridStartup.CreateGraphicsDevice(Sdl2Window window, GraphicsDeviceOptions options, GraphicsBackend preferredBackend)
   at XIVLauncher.Core.Program.Main(String[] args) in C:/goatsoft/xl/XIVLauncher.Core/Program.cs:line 182
```

**Comment by NotNite** [comment]
Is this on the flatpak? Have you ran `flatpak update` recently if so?

**Comment by metincetin** [comment]
> 

Yes, it is on the flatpak and wow, flatpak update was what's needed. That was unexpectedly fast. All works perfect now, thanks!
