### ISSUE TITLE
Can't Login / Start

### ISSUE THREAD

**Issue by Bleager** [goatcorp/FFXIVQuickLauncher#1258]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I opened the launcher, tried signing in, pressed log in and got this message

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: 'CredWrite' call throw an error (Error code: 8)
   at AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   at XIVLauncher.Accounts.XivAccount.set_Password(String value) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\XivAccount.cs:line 86
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1190
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 255
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass20_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 144
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): 'CredWrite' call throw an error (Error code: 8)
   at AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   at XIVLauncher.Accounts.XivAccount.set_Password(String value) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\XivAccount.cs:line 86
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1190
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 255<---


Version: 6.3.1.0
Git Hash: 6.3.1-0-g989c891
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by PusaiKozu** [comment]
I got the same issue and after launching in Admin Mode it works :)

**Comment by reiichi001** [comment]
> I got the same issue and after launching in Admin Mode it works :)

You should **NEVER** run XIVLauncher in admin mode. It will even warn you about this the first time. 

That will lead to anything it runs also being launched in Admin Mode and FFXIV has several file permissions related bugs that will lead to write-locking your config (system and character) and basically disabling your screenshots folder. 

There is no easy way to repair it aside from deleting everything. 

We stopped letting everything run as admin after Windows XP. There's a reason for that.
