### ISSUE TITLE
Xivlauncher error

### ISSUE THREAD

**Issue by Solomonseed** [goatcorp/FFXIVQuickLauncher#1264]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I tried reinstalling and this happened

### Platform

Windows

### Relevant log output

```shell
An error in XIVLauncher occurred. Please consult the FAQ. If this issue persists, please report
it on GitHub by clicking the button below, describing the issue and copying the text in the box.

Error during early initialization. Please report this error.

System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

**Comment by Solomonseed** [comment]
--------------------------------
02:22:38.915 | INF [IME] Enabled!
--------------------------------
02:22:38.915 | DBG [SVC] Service<"DalamudIME">: Construction complete
--------------------------------
02:22:38.916 | DBG [SVC] Service<"DalamudAtkTweaks">: Construction complete
--------------------------------
02:22:38.916 | DBG [SVC] Service<"DalamudInterface">: Construction complete
--------------------------------
02:22:38.916 | DBG [SVC] Service<"InterfaceManagerWithScene">: Provided
--------------------------------
02:22:38.980 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) START =============
--------------------------------
02:22:38.980 | INF [PLUGINM] ============= LoadPluginsSync(DrawAvailableSync) END =============
--------------------------------
02:22:38.980 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) START =============
--------------------------------
02:22:38.980 | INF [PLUGINM] ============= LoadPluginsAsync(DrawAvailableAsync) END =============
--------------------------------
02:22:38.980 | INF [PLUGINM] Loaded plugins on boot
--------------------------------
02:22:38.988 | INF Saved cache to "C:\Users\Jared.S\AppData\Roaming\XIVLauncher\addon\Hooks\7.4.3.0\cachedSigs\2023.01.17.0000.0000.json"
--------------------------------
02:22:39.330 | INF [GameFontManager] NewFontRef: Queueing RebuildFonts because "GameFontStyle(Axis18, 18pt, skew=0, weight=0)" has been requested.
--------------------------------
02:22:48.997 | ERR [PLUGINR] PluginMaster failed: https://kamori.goats.dev/Plugin/PluginMaster
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 20 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\PluginRepository.cs:line 94
--------------------------------
02:22:49.028 | INF [PLUGINM] PluginMasters reloaded, now refiltering...
--------------------------------
02:24:56.271 | DBG TerritoryType changed: 339
--------------------------------
02:24:56.546 | DBG Is login
--------------------------------
02:25:34.084 | DBG TerritoryType changed: 129
--------------------------------
02:25:58.542 | INF [PLUGINM] Now reloading all PluginMasters...
--------------------------------
02:25:58.542 | INF [PLUGINR] Fetching repo: https://kamori.goats.dev/Plugin/PluginMaster
--------------------------------
02:26:18.544 | ERR [PLUGINR] PluginMaster failed: https://kamori.goats.dev/Plugin/PluginMaster
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 20 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Dalamud.Plugin.Internal.Types.PluginRepository.ReloadPluginMasterAsync() in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\Types\PluginRepository.cs:line 94
--------------------------------
02:26:18.547 | INF [PLUGINM] PluginMasters reloaded, now refiltering...
--------------------------------
02:28:54.129 | DBG Handled RMT ad: NWG0LD.C0M -- Buy FFXIV Gil Cheapest,100% Handwork Guaranteed,24/7 online service !! && -6
--------------------------------
02:29:19.139 | DBG TerritoryType changed: 129
--------------------------------
02:29:36.588 | DBG TerritoryType changed: 418
--------------------------------
02:29:57.765 | DBG TerritoryType changed: 979
--------------------------------
02:30:29.861 | DBG TerritoryType changed: 982
--------------------------------
02:34:10.047 | DBG TerritoryType changed: 1116
--------------------------------
02:40:53.511 | DBG TerritoryType changed: 979
--------------------------------
02:41:53.142 | DBG TerritoryType changed: 982
{ } [ Send ]
