### ISSUE TITLE
Unhandled Native Exception - VehCallback()

### ISSUE THREAD

**Issue by Revokt** [goatcorp/FFXIVQuickLauncher#1281]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Was playing the game, have run into this exception now a couple of times which crashes the game.  Has happened transition zones in raids or just entering a new area.

### Platform

Windows

### Relevant log output

```shell
Unhandled native exception occurred at ffxiv_dx11.exe+988544	(sub_140988500+0x44)
Code: C0000005
Dump at: C:\Users\Name\AppData\Roaming\XIVLauncher\addon\Hooks\7.4.4.1\..\..\..\dalamud_appcrash_20230214_200649_375_11268.dmp
Time: 2023-02-14 20:06:51.9543482 CST

   at System.Environment.get_StackTrace()

   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70

   at Dalamud.Game.Network.GameNetwork.ProcessZonePacketDownDetour(IntPtr a, UInt32 targetId, IntPtr dataPtr) in C:\goatsoft\companysecrets\dalamud\Game\Network\GameNetwork.cs:line 111

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 458

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF695228544
Parameters: 0, 2A
Call Stack
{
  [0]	ffxiv_dx11.exe+988544	(sub_140988500+0x44)
  [1]	ffxiv_dx11.exe+988544	(sub_140988500+0x44)
  [2]	ffxiv_dx11.exe+98C09C	(sub_14098C070+0x2C)
  [3]	ffxiv_dx11.exe+983A4A	(sub_140983A00+0x4A)
  [4]	ffxiv_dx11.exe+98B5B0	(sub_14098B580+0x30)
  [5]	ffxiv_dx11.exe+9839BA	(sub_140983970+0x4A)
  [6]	ffxiv_dx11.exe+93B21C	(sub_14093AE50+0x3CC)
  [7]	ffxiv_dx11.exe+96EF51	(sub_14096EDD0+0x181)
  [8]	ffxiv_dx11.exe+4C1AAE	(sub_1404C19E0+0xCE)
  [9]	ffxiv_dx11.exe+6ED9B6	(sub_1406ED770+0x246)
  [10]	ffxiv_dx11.exe+755EBA	(sub_140755DC0+0xFA)
  [11]	ffxiv_dx11.exe+12636E0	(Client::Network::PacketDispatcher.OnReceivePacket:::def_141262EC6+0x6D2)
  [12]	7FF8C425FFB3
  [13]	1E754C85848
  [14]	525F14D2C0
  [15]	10733AC7
  [16]	ffxiv_dx11.exe+160F90C	(free_base+0x1C)
  [17]	525F14D220
  [18]	7FF8C425FFB3
  [19]	525F14D2C0
  [20]	1E779AA9240
  [21]	2282AAAC300
  [22]	1E779CC92C8
  [23]	10733AC7
  [24]	20390
}

Registers
{
  RAX:	4101
  RBX:	11
  RCX:	228
  RDX:	2
  R8:	ffxiv_dx11.exe+0	(_ImageBase)
  R9:	22814A28C00 [2280E647080]
  R10:	ffxiv_dx11.exe+1940F50	(vtbl_Client::UI::UIModule)
  R11:	ffxiv_dx11.exe+20E9790	(g_Client::Game::UI::UIState_Instance+0x110)
  R12:	0
  R13:	10733AC7
  R14:	ffxiv_dx11.exe+20F8088	(g_Client::Game::UI::AreaInstance_Instance+0xBF10)
  R15:	0
  RSI:	2280E69BF80 [11]
  RDI:	22814DA0A68 [22814A28C00]
  RBP:	228149E07A8 [22814A7BD80]
  RSP:	525F14BF70 [2280E69BF80]
  RIP:	ffxiv_dx11.exe+988544	(sub_140988500+0x44)
}

Stack
{
  [RSP+0]	2280E69BF80 [11]
  [RSP+8]	2280E69BF80 [11]
  [RSP+10]	ffxiv_dx11.exe+20F8088	(g_Client::Game::UI::AreaInstance_Instance+0xBF10)
  [RSP+18]	525F14C068 [22815159200]
  [RSP+20]	525F14C008 [22814E06D00]
  [RSP+28]	ffxiv_dx11.exe+98C09C	(sub_14098C070+0x2C)
  [RSP+30]	22814DA0A68 [22814A28C00]
  [RSP+38]	22814A7BD80 [22814DA0A40]
  [RSP+40]	228149E07A8 [22814A7BD80]
  [RSP+48]	22814BB3A00 [22814BB3A00]
  [RSP+50]	525F14C068 [22815159200]
  [RSP+58]	ffxiv_dx11.exe+983A4A	(sub_140983A00+0x4A)
  [RSP+60]	22814E86000 [22814DA0A40]
  [RSP+68]	22814DA0A40 [22814A7BD80]
  [RSP+70]	2280E647080 [80]
  [RSP+78]	22814A28C00 [2280E647080]
}
```

**Comment by Revokt** [comment]
Another error, same exception with same function:

Unhandled native exception occurred at cimgui.dll+532E3	(igTreeNodeBehavior+0x4F0B6)
Code: C0000005
Dump at: C:\Users\Name\AppData\Roaming\XIVLauncher\addon\Hooks\7.4.4.1\..\..\..\dalamud_appcrash_20230213_175742_120_25256.dmp
Time: 2023-02-13 17:57:42.7592813 CST

   at System.Environment.get_StackTrace()

   at Dalamud.EntryPoint.VehCallback() in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 70

   at ImGuiNET.ImGuiNative.ImFont_BuildLookupTable(ImFont* self)

   at ImGuiNET.ImGuiNative.ImFont_BuildLookupTable(ImFont* self)

   at Dalamud.Interface.Internal.InterfaceManager.SetupFonts() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 937

   at Dalamud.Interface.Internal.InterfaceManager.InitScene(IntPtr swapChain) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 534

   at Dalamud.Interface.Internal.InterfaceManager.PresentDetour(IntPtr swapChain, UInt32 syncInterval, UInt32 presentFlags) in C:\goatsoft\companysecrets\dalamud\Interface\Internal\InterfaceManager.cs:line 579

   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 458

Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF9417432E3
Parameters: 0, 238480C1728
Call Stack
{
  [0]	cimgui.dll+532E3	(igTreeNodeBehavior+0x4F0B6)
  [1]	cimgui.dll+532E3	(igTreeNodeBehavior+0x4F0B6)
  [2]	7FF8E70FB27B
  [3]	5
  [4]	1F710D1FD08
  [5]	2C4E6FE3A0
  [6]	238256B6750
  [7]	7FF8E706E258
  [8]	845560FCF1A7
  [9]	coreclr.dll+40ABB8	(coreclr_shutdown+0x4B478)
  [10]	2C4E6FF118
  [11]	7FF8E706E0D8
}

Registers
{
  RAX:	238480C1728
  RBX:	2384FC2D020 [4180000007800002]
  RCX:	238256B6750 [F9000000F900]
  RDX:	FFFF
  R8:	20
  R9:	1617
  R10:	2384FD8B010 [2384FD49090]
  R11:	46C
  R12:	1F710C0F240 [7FF8E5C75478]
  R13:	F8FF
  R14:	1F710D1FD08 [7FF8E612D888]
  R15:	0
  RSI:	238256B6750 [F9000000F900]
  RDI:	1621
  RBP:	20
  RSP:	2C4E6FE260 [2C4E6FE3A0]
  RIP:	cimgui.dll+532E3	(igTreeNodeBehavior+0x4F0B6)
}

Stack
{
  [RSP+0]	2C4E6FE3A0 [2C4E6FEA20]
  [RSP+8]	238256B6750 [F9000000F900]
  [RSP+10]	1F710D1FD08 [7FF8E612D888]
  [RSP+18]	3F70F0F1E70F9173
  [RSP+20]	F8FF00000000
  [RSP+28]	0
  [RSP+30]	0
  [RSP+38]	20003FFFFD
  [RSP+40]	C092E7C2BCC1
  [RSP+48]	coreclr.dll+15F765	(coreclr_shutdown_2+0xBC65)
  [RSP+50]	3FB33333
  [RSP+58]	0
  [RSP+60]	1F711536E80 [7FF8E71B0FB0]
  [RSP+68]	1F710D1FD08 [7FF8E612D888]
  [RSP+70]	1F713BF6688 [7FF8E5CA72B0]
  [RSP+78]	1F710C0F240 [7FF8E5C75478]
}
