### ISSUE TITLE
Mods making game crash

### ISSUE THREAD

**Issue by ArielGainsborough** [goatcorp/FFXIVQuickLauncher#1305]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I did everything penumbra's mods asked me to do 

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.IO.IOException: The process cannot access the file 'C:\Users\crist\AppData\Roaming\XIVLauncher\patches\game\4e9a232b\D2021.11.17.0000.0000.patch' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.QueueInstall(Int32 sourceIndex, FileInfo file, Int32 splitBy) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 702
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 434
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<QueueInstall>d__29.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 267
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 425

Version: 6.3.4.0
Git Hash: 6.3.4-0-gec64648
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Users\crist\OneDrive\Documents\Dalmud
```

**Comment by NotNite** [comment]
This is the repository for the launcher, not for Dalamud. Furthermore, please do not report bugs about custom repository plugins to Dalamud.
