### ISSUE TITLE
Unable to start game, with Dalamud enabled on Linux.

### ISSUE THREAD

**Issue by ksgk1** [goatcorp/FFXIVQuickLauncher#1320]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I hade FFXIVQuickLauncher installed for a long time and never really tried out the plugins. Today I decided to enable the "Dalamud" and got the error show below. Trying to use the legacy mode did not change the error. 
I am using KDE X11 on ArchLinux, with a RX580 GPU. Mesa 23.0.3-1, xf86-video-amdgpu 23.0.0-1 and have three monitors. I also rebooted my system and that did not change anything. I also turned off my other monitors. The game launches just fine without Dalamud enabled.

My error is quite similar to: https://github.com/goatcorp/FFXIVQuickLauncher/issues/1259 so the cause might be related.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

lutris-7.1-x86_64

### Relevant log output

```shell
System.ArgumentException: Item has already been added. Key in dictionary: 'DISPLAY'  Key being added: 'display'
   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)
   at System.Diagnostics.ProcessStartInfo.get_EnvironmentVariables()
   at XIVLauncher.Common.Windows.WindowsDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, Boolean noPlugins, Boolean noThirdPlugins, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsDalamudRunner.cs:line 59
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:\goatsoft\xl\XIVLauncher.Common\Dalamud\DalamudLauncher.cs:line 84
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 282
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 629

Version: 6.3.4.0
Git Hash: 6.3.4-0-gec64648
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by tommadness** [comment]
Lutris is no longer a supported install method for using Dalamud since the move to .NET 7. I would recommend migrating to the native XIVLauncher package available through Flathub or the community package available on the AUR.
