### ISSUE TITLE
Launcher crashing during game startup

### ISSUE THREAD

**Issue by kividiot** [goatcorp/FFXIVQuickLauncher#1351]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Game worked, updated to latest Nobara kernel 6.3.9-200.fsync.fc38.x86_64 and it stopped working.

### Platform

Linux (native)

### Relevant log output

```shell
2023-06-26 19:18:56.538 +02:00 [INF] ========================================================
2023-06-26 19:18:56.550 +02:00 [INF] Starting a session(v1.0.4.0 - f9a40ed)
2023-06-26 19:18:56.877 +02:00 [INF] [DUPDATE] Starting...
2023-06-26 19:18:57.269 +02:00 [INF] [DUPDATE] Using release version (7.7.4.0)
2023-06-26 19:18:57.386 +02:00 [INF] [DUPDATE] Now starting for .NET Runtime 7.0.0
2023-06-26 19:18:57.830 +02:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMy0wNi0yNlQxOToxODo1Ny44MTgzNjU1KzAyOjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6ZmFsc2UsIklzVWlkQ2FjaGUiOmZhbHNlLCJEYWxhbXVkRW5hYmxlZCI6dHJ1ZSwiRGFsYW11ZExvYWRNZXRob2QiOjEsIkRhbGFtdWRJbmplY3Rpb25EZWxheSI6MC4wLCJTdGVhbUludGVncmF0aW9uIjpmYWxzZSwiRW5jcnlwdEFyZ3VtZW50cyI6dHJ1ZSwiTGF1bmNoZXJWZXJzaW9uIjoiMS4wLjQuMCIsIkxhdW5jaGVySGFzaCI6ImY5YTQwZWQiLCJPZmZpY2lhbCI6ZmFsc2UsIkRwaUF3YXJlbmVzcyI6MSwiUGxhdGZvcm0iOjIsIk9ic2VydmVkR2FtZVZlcnNpb24iOiIyMDIzLjA2LjE0LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgxVmVyc2lvbiI6IjIwMjMuMDUuMTIuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDJWZXJzaW9uIjoiMjAyMy4wNS4xOC4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4M1ZlcnNpb24iOiIyMDIzLjA1LjEyLjAwMDAuMDAwMCIsIk9ic2VydmVkRXg0VmVyc2lvbiI6IjIwMjMuMDYuMTMuMDAwMC4wMDAwIiwiQmNrTWF0Y2giOnRydWUsIkluZGV4SW50ZWdyaXR5Ijo1fQ==
2023-06-26 19:18:57.913 +02:00 [INF] [DUPDATE] All set for 2023.06.14.0000.0000 with 7.7.4.0(7.0.0, 207)
2023-06-26 19:19:07.875 +02:00 [INF] XivGame::Login(steamServiceAccount:false, cache:false)
2023-06-26 19:19:09.210 +02:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:4
2023-06-26 19:19:10.412 +02:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyMy0wNi0yNlQxOToxOToxMC40MTE5ODQ2KzAyOjAwIiwiSXNEeDExIjp0cnVlLCJJc0F1dG9Mb2dpbiI6ZmFsc2UsIklzVWlkQ2FjaGUiOmZhbHNlLCJEYWxhbXVkRW5hYmxlZCI6dHJ1ZSwiRGFsYW11ZExvYWRNZXRob2QiOjEsIkRhbGFtdWRJbmplY3Rpb25EZWxheSI6MC4wLCJTdGVhbUludGVncmF0aW9uIjpmYWxzZSwiRW5jcnlwdEFyZ3VtZW50cyI6dHJ1ZSwiTGF1bmNoZXJWZXJzaW9uIjoiMS4wLjQuMCIsIkxhdW5jaGVySGFzaCI6ImY5YTQwZWQiLCJPZmZpY2lhbCI6ZmFsc2UsIkRwaUF3YXJlbmVzcyI6MSwiUGxhdGZvcm0iOjIsIk9ic2VydmVkR2FtZVZlcnNpb24iOiIyMDIzLjA2LjE0LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgxVmVyc2lvbiI6IjIwMjMuMDUuMTIuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDJWZXJzaW9uIjoiMjAyMy4wNS4xOC4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4M1ZlcnNpb24iOiIyMDIzLjA1LjEyLjAwMDAuMDAwMCIsIk9ic2VydmVkRXg0VmVyc2lvbiI6IjIwMjMuMDYuMTMuMDAwMC4wMDAwIiwiQmNrTWF0Y2giOnRydWUsIkluZGV4SW50ZWdyaXR5Ijo1fQ==
2023-06-26 19:19:10.495 +02:00 [INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:/games/ffxiv)
2023-06-26 19:19:11.416 +02:00 [INF] XivGame::LaunchGame(steamServiceAccount:False, args:UserPath=Z:\games\ffxivConfig)
2023-06-26 19:19:11.431 +02:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:5834843 ticks:5834843 key:5832704
2023-06-26 19:19:11.436 +02:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"C"
2023-06-26 19:19:11.437 +02:00 [INF] [HOOKS] DalamudLauncher::Run(gp:/games/ffxiv, cl:"English")
2023-06-26 19:19:11.437 +02:00 [INF] [HOOKS] DelayInitializeMs: 0
2023-06-26 19:19:12.115 +02:00 [ERR] StartGameAndError resulted in an exception.
XIVLauncher.Common.Dalamud.DalamudRunnerException: An internal Dalamud error has occured
   at XIVLauncher.Common.Unix.UnixDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, Boolean noPlugins, Boolean noThirdPlugins, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixDalamudRunner.cs:line 80
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/DalamudLauncher.cs:line 123
   at XIVLauncher.Common.Unix.UnixGameRunner.Start(String path, String workingDirectory, String arguments, IDictionary`2 environment, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixGameRunner.cs:line 27
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 282
   at XIVLauncher.Core.Components.MainPage.MainPage.StartGameAndAddon(LoginResult loginResult, Boolean isSteam, Boolean forceNoDalamud, Boolean noThird)
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 377
2023-06-26 19:19:12.125 +02:00 [ERR] Task failed
System.AggregateException: One or more errors occurred. (An internal Dalamud error has occured)
 ---> XIVLauncher.Common.Dalamud.DalamudRunnerException: An internal Dalamud error has occured
   at XIVLauncher.Common.Unix.UnixDalamudRunner.Run(FileInfo runner, Boolean fakeLogin, Boolean noPlugins, Boolean noThirdPlugins, FileInfo gameExe, String gameArgs, IDictionary`2 environment, DalamudLoadMethod loadMethod, DalamudStartInfo startInfo) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixDalamudRunner.cs:line 80
   at XIVLauncher.Common.Dalamud.DalamudLauncher.Run(FileInfo gameExe, String gameArgs, IDictionary`2 environment) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/DalamudLauncher.cs:line 123
   at XIVLauncher.Common.Unix.UnixGameRunner.Start(String path, String workingDirectory, String arguments, IDictionary`2 environment, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixGameRunner.cs:line 27
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:/goatsoft/xl/XIVLauncher.Common/Game/Launcher.cs:line 282
   at XIVLauncher.Core.Components.MainPage.MainPage.StartGameAndAddon(LoginResult loginResult, Boolean isSteam, Boolean forceNoDalamud, Boolean noThird)
   at XIVLauncher.Core.Components.MainPage.MainPage.TryProcessLoginResult(LoginResult loginResult, Boolean isSteam, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 377
   at XIVLauncher.Core.Components.MainPage.MainPage.Login(String username, String password, Boolean isOtp, Boolean isSteam, Boolean doingAutoLogin, LoginAction action) in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 200
   at XIVLauncher.Core.Components.MainPage.MainPage.<>c__DisplayClass17_0.<<ProcessLogin>b__0>d.MoveNext() in C:/goatsoft/xl/XIVLauncher.Core/Components/MainPage/MainPage.cs:line 143
   --- End of inner exception stack trace ---
```

**Comment by kividiot** [comment]
Tried previous kernel, same issue with that.

**Comment by kividiot** [comment]
Placed in wrong queue, sorry..
