### ISSUE TITLE
The Launcher Keeps crashing and will rarely open

### ISSUE THREAD

**Issue by satheevrin** [goatcorp/FFXIVQuickLauncher#1363]
I use Arch Linux and run FFXIV through WINE (using steam service). The launcher used to work so flawlessly, but recently, whenever I try and boot it up, tt will go to the login section, where I'll enter my password and then I'll connect. A few seconds pass, the wheel where the game is showing to login spins for a bit and then it just crashes. 

Every time it crashes. It crashes, it crashes, it crashes. SOMETIMES it will let me in, but most of the times, it just crashes. 

Why has this started happening? I am completely unable to login now and I do not what sort of debugging info I need to bring up here to solve this issue. What is causing this? Is there a log anywhere that you guys need for me to post so you can see what is going on??

Please help me.

**Comment by satheevrin** [comment]
<code>Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Steamworks.SteamUtils.get_DoesOverlayNeedPresent()
   at XIVLauncher.Common.Unix.UnixSteam.get_BOverlayNeedsPresent() in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixSteam.cs:line 31
   at XIVLauncher.Core.Program.Main(String[] args) in C:/goatsoft/xl/XIVLauncher.Core/Program.cs:line 274
fish: Job 1, 'XIVLauncher.Core' terminated by signal SIGABRT (Abort)</code>

I found something by launching the program through a terminal, but I don't understand what it means.

**Comment by satheevrin** [comment]
I have tried resetting everything using the troubleshooting tab in the quicklauncher. However, when I configure my settings to my liking again, the problems start over again....

**Comment by satheevrin** [comment]
Another thing I've noticed today: If the game DOES end up launching, it CRASHES alot. Is this due to this steam api thing? Is it having trouble communicating with something? I don't understand...

**Comment by satheevrin** [comment]
This is apparently on the wrong one. I need to go XIVLauncher.Core. Closing, will reopen there
