### ISSUE TITLE
Error occuring when trying to repair game files

### ISSUE THREAD

**Issue by laredhel1** [goatcorp/FFXIVQuickLauncher#1368]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

My game has been crashing only when launching through XIVLauncher, launching through the official client doesn't cause crashes. It's only happening at certain points in certain dungeons and raids (for a time, I couldn't even load into Final Coil of Bahamut, turns 2 and 3 without a crash) and is not replicated at the same point when launched via the normal client. I've reinstalled the game and run a restore through the official client too and the same issue occurs only through XIVLauncher.

The error I get is an error code 17 whent he game does crash in-game, hence my reason to try repairing via XIVLauncher.
I hope that even if I can't fix my isue that this can somehow help in development to avoid issues for others,

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 165
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 398
---> (Inner Exception #0) System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 165
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()<---

   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 394

Version: 6.3.6.0
Git Hash: 6.3.6-0-g74e3142
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by laredhel1** [comment]
Update on this, I found out my issue, it was trying to access my old FFXIV install (that I wasn't aware existed) redirecting it to my current install fixed the issue. My apologies for not looking into it further (I discovered this was the case after a friend brought up noticing my old install).
