### ISSUE TITLE
Can't login using XIVLauncher (Steam)

### ISSUE THREAD

**Issue by agentgerbil** [goatcorp/FFXIVQuickLauncher#1384]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried to login.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.ComponentModel.Win32Exception: 'CredWrite' call throw an error (Error code: 8)
   at AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   at XIVLauncher.Accounts.XivAccount.set_Password(String value) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\XivAccount.cs:line 86
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1186
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 255
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass20_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 146
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): 'CredWrite' call throw an error (Error code: 8)
   at AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   at XIVLauncher.Accounts.XivAccount.set_Password(String value) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\XivAccount.cs:line 86
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.PersistAccount(String username, String password) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1186
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 255<---


Version: 6.3.6.0
Git Hash: 6.3.6-0-g74e3142
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by agentgerbil** [comment]
> based on a few other discussions, it looks like the Windows Credential Manager has an [undocumented limit](https://stackoverflow.com/questions/75051284/does-the-credential-manager-have-a-limit-for-the-number-of-credentials-stored#comment132533562_75073454). And you can get this error if your cred manager [has been filled](https://stackoverflow.com/a/69886592)

clearing some room in my credential manager fixed it, thanks!
