### ISSUE TITLE
Repair error on 6.3.8

### ISSUE THREAD

**Issue by LTS-FFXIV** [goatcorp/FFXIVQuickLauncher#1387]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Attempted to repair files (to remove textool mods and such) and got this error

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.OverflowException: Array dimensions exceeded supported range.
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchTargetFile.ReadFrom(BinaryReader reader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchTargetFile.cs:line 225
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchTargetFile..ctor(BinaryReader reader, Boolean disposeReader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchTargetFile.cs:line 27
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndex..ctor(BinaryReader reader, Boolean disposeReader) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndex.cs:line 43
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 383
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<ConstructFromPatchFile>d__19.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 380

Version: 6.3.8.0
Git Hash: 6.3.8-0-g5e10228
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\FF14
```

**Comment by reiichi001** [comment]
This is a known issue. We will need to push another launcher release after we have time to invesitage and fix it. Patching should work, but repair is still broken (and also not updated for 6.5 yet anyways)
