### ISSUE TITLE
Launcher is getting error when trying to update

### ISSUE THREAD

**Issue by Theletha** [goatcorp/FFXIVQuickLauncher#1399]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Opened xiv launcher for it to check update for the launcher and it arent able to update.

I have turned of the Microsoft AV and still getting the error 

### Platform

Windows

### Relevant log output

```shell
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Version: 6.3.9.0
Git Hash: 6.3.9-0-ge6d2ff8
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by Theletha** [comment]
OK after i restarted the app 5 times it kind just updated itself? its now on 6.3.10.0 version. you guys can close it after you review the error to see if it has anything that can help for the future.
