### ISSUE TITLE
launchger error

### ISSUE THREAD

**Issue by Viperfearne** [goatcorp/FFXIVQuickLauncher#1417]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

i logged into the game like i normally would

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): %1 is not a valid Win32 application
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 448
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 282
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 634

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment]
This error would make me suspect your game client executable is corrupted in some way, given it's failing to start it - try right clicking the Login button and repairing your game.

**Comment by Viperfearne** [comment]
i already did tht and got a diffrent error

**Comment by NotNite** [comment]
Saying you got an error and not showing it isn't very helpful. Regardless, repair indexes were out of date until recently, so try it again.

**Comment by Viperfearne** [comment]
im sorry didnt have the log for tht one let me try it again and post the error when it pops up

**Comment by Viperfearne** [comment]
so i did a repair and this was the log that it gave me when i was done
System.Exception: System.IO.IOException: The process cannot access the file 'D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxiv_dx11.exe' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.IO.FileInfo.Open(FileMode mode, FileAccess access)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.SetTargetStreamForWriteFromFile(Int32 targetIndex, FileInfo fileInfo, Boolean useSetFileValidData) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 324
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.SetTargetStreamsFromPathReadWriteForMissingFiles(String rootPath) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 373
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 422
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<SetTargetStreamsFromPathReadWriteForMissingFiles>d__25.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 243
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 409

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by NotNite** [comment]
Close the game/any FFXIV related tools.

**Comment by Viperfearne** [comment]
ok will do

**Comment by Viperfearne** [comment]
ok thanks it worked finally appreciate the help
