### ISSUE TITLE
XIV Launcher

### ISSUE THREAD

**Issue by NekoleRhen** [goatcorp/FFXIVQuickLauncher#1424]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried to launch the game.

Windows caused an error and it crashed.
Restarted my PC. Launcher wont launch now.
Had been playing prior for over 24 hours without any issues.

### Platform

Windows

**Comment by NekoleRhen** [comment]
Am sorry unsure how to do this, correctly.

This was the text in the error:

System.AggregateException: One or more errors occurred. ---> System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at XIVLauncher.Game.ProblemCheck.CheckMyGamesWriteAccess() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\ProblemCheck.cs:line 297
   at XIVLauncher.Game.ProblemCheck.RunCheck(Window parentWindow) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\ProblemCheck.cs:line 81
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 166
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass20_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 146
---> (Inner Exception #0) System.IO.IOException: The file or directory is corrupted and unreadable.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at XIVLauncher.Game.ProblemCheck.CheckMyGamesWriteAccess() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\ProblemCheck.cs:line 297
   at XIVLauncher.Game.ProblemCheck.RunCheck(Window parentWindow) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\ProblemCheck.cs:line 81
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 166<---


Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
