### ISSUE TITLE
[ERR] Could not check version, XIVlauncher crashes upon starting

### ISSUE THREAD

**Issue by REKTingCrew** [goatcorp/FFXIVQuickLauncher#1428]
### Update disclaimer

- [x] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

The launcher was working fine for me a few days ago, but no I can't even get it to boot, forcing me to hard-reboot my computer. I have already tried uninstalling and reinstalling the launcher, disabling my plugins, and making sure I was on the latest version. Any help on fixing this issue would be greatly appreciated.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

GE-Proton7-14

### Relevant log output

```shell
2023-12-20 18:46:24.868 -05:00 [INF] ========================================================
2023-12-20 18:46:24.894 -05:00 [INF] Starting a session(v1.0.6.0 - 072aca4)
2023-12-20 18:46:25.367 -05:00 [INF] [DUPDATE] Starting...
2023-12-20 18:46:31.138 -05:00 [ERR] Could not check version
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at XIVLauncher.Core.UpdateCheck.CheckForUpdate() in C:/goatsoft/xl/XIVLauncher.Core/UpdateCheck.cs:line 16
```

**Comment by reiichi001** [comment]
Does making the adjustment from this link make a difference?
https://weblog.lkiesow.de/20220311-make-linux-prefer-ipv4.html

**Comment by REKTingCrew** [comment]
No, the launcher still crashed and gave me the same error message.

**Comment by reiichi001** [comment]
Do you use a  VPN or proxy of any kind? Or live in a region that might be blocked by GitHub?

The launcher should be trying to load https://raw.githubusercontent.com/goatcorp/xlcore-distrib/main/version.txt

Which Linux distro are you using? There may be a community build you can switch to, as those don't have the version check feature. (Since your package manager is then responsible for it)

**Comment by REKTingCrew** [comment]
I don't use any VPN or proxy and I doubt my region would be blocking GitHub. I'm on Pop OS 22.04 LTS.

**Comment by REKTingCrew** [comment]
Also, I downloaded the launcher off the Pop Store, so it should be the version I need.

**Comment by reiichi001** [comment]
The Pop Shop is primarily a flatpak distributor, although you can select native packages when they're available. Most flatpaks are not designed with Pop-OS in mind because they're distro-agnostic. 

You can give the PPA a shot. https://launchpad.net/~linneris/+archive/ubuntu/xivlauncher-core-stable 

Uninstall the flatpak, install from the PPA. You'll get launcher updates through apt then. No need to reset your wine prefix or anything, since the flatpak builds use the same wine builds as debian anyways.

**Comment by REKTingCrew** [comment]
I tried installing it that way but it's still crashing upon startup.

**Comment by REKTingCrew** [comment]
Well, the launcher seems to have fixed itself and I can play the game just fine again, so I'll go ahead and close this issue.
