### ISSUE TITLE
error repairing files

### ISSUE THREAD

**Issue by samiam82** [goatcorp/FFXIVQuickLauncher#1430]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I was running a game file repair from the launcher button

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 165
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 402
---> (Inner Exception #0) System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 165
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 237
   at System.Threading.Tasks.Task.Execute()<---

   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 206
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 394

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by wolfcomp** [comment]
Your drive is dying. CRC error always indicates that a drive is failing with the launcher.

**Comment by tommadness** [comment]
To be clear, that error is coming from the drive itself, and is bubbling up through the launcher.

**Comment by Harest** [comment]
So i started to have error 17 w/ the game. I wanted to give the repair a try just in case. And iI had a similar error. Thanks for the comments, i opened CrystalDiskInfo and.. it's bad. A SSD bought only in March of this year, and the "Available Spare" is already only at 26% with 2 "Media and Data Integrity Errors". I contacted the manufacturer to see if i can have an exchange. It's supposedly under a 5 years warranty. Note that this SSD (Magix NVMe M.2 1TB X-Pro) didn't even have 1TB in writing yet. I guess that's my first time having a faulty disk, yay.

I'll put my stack trace here too just in case:
```System.Exception: System.AggregateException: Une ou plusieurs erreurs se sont produites. ---> System.IO.IOException: Erreur de données (contrôle de redondance cyclique).

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:ligne 160
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__5() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:ligne 251
   à System.Threading.Tasks.Task.Execute()
   --- Fin de la trace de la pile d'exception interne ---
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:ligne 306
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:ligne 418
---> (Exception interne #0) System.IO.IOException: Erreur de données (contrôle de redondance cyclique).

   à System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   à System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   à System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:ligne 160
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__5() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:ligne 251
   à System.Threading.Tasks.Task.Execute()<---

   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:ligne 168
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   à XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() dans C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:ligne 208
--- Fin de la trace de la pile à partir de l'emplacement précédent au niveau duquel l'exception a été levée ---
   à System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   à XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() dans C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:ligne 400

Version: 6.4.1.0
Git Hash: 6.4.1-0-g21a73f3c
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? False
Auto Login Enabled? False
Language: French
LauncherLanguage: French
Game path: E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online```
