### ISSUE TITLE
I Have No Clue

### ISSUE THREAD

**Issue by Kerryee** [goatcorp/FFXIVQuickLauncher#1440]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

My Reshade stopped working, and I've been having problems with the game erroring when launching, and sending my disk usage to 100%

### Platform

Windows

### Relevant log output

```shell
An error in XIVLauncher occurred. Please consult the FAQ. If this issue persists, please report
it on GitHub by clicking the button below, describing the issue and copying the text in the box.

Error during early initialization. Please report this error.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\DAODB\MSSQL.1\MSSQL' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 108
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass20_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 258
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass20_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 260
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\DAODB\MSSQL.1\MSSQL' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 108
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass20_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 258
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass20_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 260
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\DAODB\MSSQL.1\MSSQL' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 108
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1 sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress, Boolean onlyIndex) in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 148
   at XIVLauncher.Common.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 95
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\IntegrityCheck.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass20_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 258<---
<---
```

**Comment by NotNite** [comment]
Could you please show the selected game path in the XIVLauncher settings?
