### ISSUE TITLE
Error Logging In

### ISSUE THREAD

**Issue by HrrbleDncr** [goatcorp/FFXIVQuickLauncher#1471]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Fresh installed, made sure the file destination was correct, and let it pass through the firewall. The launcher tosses up the error after trying to log in.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Accounts.AccountManager.UpdateLastSuccessfulOtp(XivAccount account, String lastOtp) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\AccountManager.cs:line 49
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 292
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Accounts.AccountManager.UpdateLastSuccessfulOtp(XivAccount account, String lastOtp) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\AccountManager.cs:line 49
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 292<---


Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by HrrbleDncr** [comment]
Had to clear out some out and unused credentials for the launcher to work
