### ISSUE TITLE
Constant Error When Trying to Log In

### ISSUE THREAD

**Issue by Aerynelle** [goatcorp/FFXIVQuickLauncher#1480]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I have my game on an external SSD, it was working great all day. I turned off my pc, unplugged it, and plugged into my laptop. I am now getting error message that access is denied. Everything is on the same drive, nothing has changed. I completely reinstalled the game last night and it was working. Now it says the files are corrupted.

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.UnauthorizedAccessException: Access to the path 'E:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.WriteVersionFiles(String localRootPath) in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 427
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 430
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WriteVersionFiles>d__27.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 252
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 446

Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by Aerynelle** [comment]
For some reason my file was locked. Not sure how or why. It is accessing now.
