### ISSUE TITLE
[ERR] Could not obtain gate status

### ISSUE THREAD

**Issue by KrisSiegel** [goatcorp/FFXIVQuickLauncher#1487]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

The official game launcher works as expected but semi-recently on two different computers I've seen this same error message.

`[ERR] Could not obtain gate status`

Looking at the error log I'm getting this exception:

```
2024-04-30 00:01:42.704 -07:00 [ERR] Could not obtain gate status
System.Exception: Could not get login status ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 119.252.36.135:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Launcher.<DownloadAsLauncher>d__30.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 672
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Launcher.<GetLoginStatus>d__28.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 624
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Game.Launcher.<GetLoginStatus>d__28.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 632
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryLoginToGame>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 379
```

I can't find many references to `119.252.36.135` but I can ping and tracert it just fine and like I said the official launcher never has this issue.

Where is this address coming from? Is it valid?

### Platform

Windows

**Comment by reiichi001** [comment]
That's one of the SE login servers, which are currently being DDOSed. There's nothing we can do about this, as it affects the official launcher too. It's outside of our control.

**Comment by KrisSiegel** [comment]
@reiichi001 this was an issue that started about two weeks ago and was reported last week. SE only confirmed the DDoS attack as of yesterday and like I said the official launcher worked fine while XIVLauncher had this issue (though with the DDoS it might be difficult to debug at the moment).

The error was extremely frequent on one of my machines  (XIVLauncher always failed) but the official launcher never did. I just tried today and it hasn't occurred yet. Perhaps I can see about getting XIVLauncher running through a debugger to see if I can find anything interesting when the DDoS is for sure over.

**Comment by reiichi001** [comment]
DDOS aside, ISP and routing issues will cause this to happen. It's not an issue with XIVLauncher so much as the machine and the route it takes over the internet to get to SE's servers. If the server doesn't respond in a reasonable amount of time (or at all), there's nothing we can do about that.

Alternate DNS or a VPN can sometimes help, but to use the "the internet is a highway" metaphor, no amount of alternate routes will get you through a large traffic jam during rush hour. 

Or if your ISP is doing something dumb like prioritizing a tunneled 4to6 IPv6 address over the actual IPv4 one, you can force your computer to prioritize IPv4, which can help in certain cases. (This is not likely the case)

**Comment by KrisSiegel** [comment]
> DDOS aside, ISP and routing issues will cause this to happen. It's not an issue with XIVLauncher so much as the machine and the route it takes over the internet to get to SE's servers. If the server doesn't respond in a reasonable amount of time (or at all), there's nothing we can do about that.

Like I mentioned the trace route was fine (ping was low across all hops) and the official launcher never had an issue. You could even use XIVLauncher, have this error occur, use the official launcher, have it work fine, go back to XIVLauncher and it continues to fail.

I suspect, especially considering the second machine I have takes longer to connect to the internet properly via WiFi, that something is getting cached improperly as I can reproduce it by disconnecting the internet and then reconnecting it won't work until I force close XIVLauncher. Perhaps the response time has been slower lately so it feels worse in XIVLauncher?

The code looked fine to me but I'm not super familiar with the inner workings of the Windows version of System.Net.Http so if I get around to it, I'll see if I can find anything.
