### ISSUE TITLE
Launcher fails to reinstall

### ISSUE THREAD

**Issue by Cantus-Dilean** [goatcorp/FFXIVQuickLauncher#1503]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I initially tried just launching the program but it kept failing to check for updates, so I thought I'd try reinstalling it. When I did that it said "installation has failed" and told me to look at this log. It also deleted the .exe so I can't even run the program any more. I'm on Windows 10, and I've  tried whitelisting all the files and folders suggested by the help page to no effect.

### Platform

Windows

### Relevant log output

```shell
2024-05-30 18:24:48> Program: Starting Squirrel Updater: --install .
2024-05-30 18:24:48> Program: Starting install, writing to C:\Users\zacha\AppData\Local\SquirrelTemp
2024-05-30 18:24:48> Program: About to install to: C:\Users\zacha\AppData\Local\XIVLauncher
2024-05-30 18:24:48> Program: Install path C:\Users\zacha\AppData\Local\XIVLauncher already exists, burning it to the ground
2024-05-30 18:24:49> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:49> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:49> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:49> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:50> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:50> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:50> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:50> SingleGlobalInstance: Failed to grab lockfile, will retry: C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE: System.UnauthorizedAccessException: Access to the path 'C:\Users\zacha\AppData\Local\Temp\.squirrel-lock-59D6331D54A594504DF8124B2FF2E174B03547FE' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
2024-05-30 18:24:51> Unhandled exception: System.AggregateException: One or more errors occurred. ---> System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
---> (Inner Exception #0) System.Exception: Couldn't acquire lock, is another instance running
   at Squirrel.SingleGlobalInstance..ctor(String key, TimeSpan timeOut)
   at Squirrel.UpdateManager.<acquireUpdateLock>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.Update.Program.<Install>d__4.MoveNext()<---
```

**Comment by Cantus-Dilean** [comment]
Looks like it was a permissions issue with the temp folder. Found out how to reset it on the Dalamud DIscord Server.
