### ISSUE TITLE
XIVLauncher unable to repair files

### ISSUE THREAD

**Issue by FierySnips** [goatcorp/FFXIVQuickLauncher#1505]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

My game keeps crashing at random points and in the past I've been able to repair it just fine. This is the second time I've gotten this error in XIVLauncher and now I'm having to reinstall my game and everything else associated with it too yet again. I had to do it the first time just yesterday. I can't tell if it's an issue with the launcher or something else entirely. This is the error text from the box:

System.Exception: System.IO.IOException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\reshade-presets' is denied.
   at System.IO.Directory.InternalMove(String sourceDirName, String destDirName, Boolean checkHost)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 489
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<MoveFile>d__35.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 329
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<MoveUnnecessaryFiles>d__82.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 460

Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

### Platform

Windows

**Comment by reiichi001** [comment]
Your reshade installation is blocking the repair process for an unknown reason. It's likely a file permission issue, although the patch installer/verifier process should normally run with high enough permissions to handle that.

You should not normally need to repair your game installation unless you've made modifications to client files. (Like applying mods using textools, although installing reshade does count as modifying the game install too, as it places files that did not come with FFXIV into the game folder).

> now I'm having to reinstall my game and everything else associated with it too yet again
Can you please explain your thought process here? Reinstalling the game after a crash is a tad extreme. Even running a repair unprompted can be. (While that should be a nondestructive process, it also reads like jumping to conclusions too early.)

If you're getting the Dalamud Crash Handler window, there will also be an option to save troubleshooting information. Please upload that here, or contact us on our Discord referencing this github issue so we have context.
