### ISSUE TITLE
FFXIV Dalamund Error

### ISSUE THREAD

**Issue by AnonChaotik** [goatcorp/FFXIVQuickLauncher#1512]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I tried to open FFXIV via the XIV launcher, and I got said error

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:\goatsoft\xl\XIVLauncher.Common\Util\PlatformHelpers.cs:line 150
   at XIVLauncher.Common.Game.Patch.PatchManager.<PatchAsync>d__37.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 119
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1389

Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: HandlePatchAsync
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment]
- This is not a ~~Dalamund~~ Dalamud error. This is the launcher.
- This looks like one of the paths set for patching (either the game install or patch download location) is set to an invalid drive. Please make sure the path is correct.
