### ISSUE TITLE
Error upon opening XIVlauncher after installing patch in vanilla launch

### ISSUE THREAD

**Issue by vegastellaris** [goatcorp/FFXIVQuickLauncher#1520]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I had already downloaded the patch via the vanilla game launcher. I saw XIVLauncher was updated, so opened it to initialize the launcher download. After the download completed, instead of opening the launcher, I received this error message.

### Platform

Windows

### Relevant log output

```shell
System.Exception: Update.exe not found, not a Squirrel-installed app?
   at Squirrel.UpdateManager.getUpdateExe()
   at Squirrel.UpdateManager.RestartApp(String exeToStart, String arguments)
   at System.Windows.Window.OnClosed(EventArgs e)
   at System.Windows.Window.WmDestroy()
   at System.Windows.Window.WindowFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.PublicHooksFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by reiichi001** [comment]
Are you using a particular antivirus product? This looks like a portion of XIVLauncher is missing. (You can reinstall the launcher from <https://github.com/goatcorp/FFXIVQuickLauncher/releases/download/6.4.0/Setup.exe>, but this will continue to happen if your AV is eating its files.)
