### ISSUE TITLE
Error in Updating

### ISSUE THREAD

**Issue by katmaria** [goatcorp/FFXIVQuickLauncher#1525]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Trying to update to 7.0 in prep for dawntrail, got this error.

### Platform

Windows

### Relevant log output

```shell
An error in XIVLauncher occurred. Please consult the FAQ. If this issue persists, please report
it on GitHub by clicking the button below, describing the issue and copying the text in the box.

Error during early initialization. Please report this error.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.IO.IOException: The process cannot access the file 'E:\game\4e9a232b\D2024.05.25.0008.0000.patch' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at XIVLauncher.Common.Game.Patch.PatchManager.CheckPatchValidity(PatchListEntry patchListEntry, FileInfo path) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 468
   at XIVLauncher.Common.Game.Patch.PatchManager.<DownloadPatchAsync>d__41.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Patch.PatchManager.<>c__DisplayClass43_0.<<RunDownloadQueue>b__2>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 353
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.IO.IOException: The process cannot access the file 'E:\game\4e9a232b\D2024.05.25.0008.0000.patch' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.FileInfo.OpenRead()
   at XIVLauncher.Common.Game.Patch.PatchManager.CheckPatchValidity(PatchListEntry patchListEntry, FileInfo path) in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 468
   at XIVLauncher.Common.Game.Patch.PatchManager.<DownloadPatchAsync>d__41.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 200
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Game.Patch.PatchManager.<>c__DisplayClass43_0.<<RunDownloadQueue>b__2>d.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 353<---
```

**Comment by katmaria** [comment]
Now I am getting the error:
> XIVLauncher could not establish a connection to the game servers.
> 
> This may be a temporary issue, or a problem with your internet connection. Please try again later.
despite the fact that I am on a wired ethernet connection, and am connecting fine to Firefox.

**Comment by reiichi001** [comment]
You can have an impeccably perfect LAN and still get screwed by WAN connections and/or your ISP. (The same also applies in reverse)

You may want to try restarting your computer before anything else.
