### ISSUE TITLE
Trying to Update for Dawntrail

### ISSUE THREAD

**Issue by azujaque** [goatcorp/FFXIVQuickLauncher#1526]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I just launched the launcher in order to download Dawntrail, and I kept getting this error over and over.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by nathanctech** [comment]
Appears to be similar to #1522 - do you have an active subscription? The developer is aware of the crash, at least.

**Comment by azujaque** [comment]
I do now! Thank you for helping out! It's updating perfectly fine now.
