### ISSUE TITLE
XIV Launcher not Preloading

### ISSUE THREAD

**Issue by Justinm8n** [goatcorp/FFXIVQuickLauncher#1532]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I updated the Launcher to 6.4.0 and I'm a little stumped on how to update the game from here. Maybe I'm doing something wrong or made a mistake. Some help in the right direction would be nice right now. Respond whenever you can.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by tommadness** [comment]
Is your FFXIV subscription paid and active?

**Comment by Justinm8n** [comment]
Oh it fixed the problem, sorry. I thought I already had it active
