### ISSUE TITLE
Error on XIVLauncher

### ISSUE THREAD

**Issue by Javi-22** [goatcorp/FFXIVQuickLauncher#1547]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

_"We have also verified that SE didn’t break anything particularly important in the login/patching process, and are pleased to announce that you can use XIVLauncher to patch the game all speedy-like."_

I tried to both log in and update the game, and neither worked. I got either similar errors or the same exact error and am unable to do anything. I have also uninstalled XIVLauncher and reinstalled, showing me the same error message.

### Platform

Windows

### Relevant log output

```shell
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<>c__DisplayClass22_0.<TryLogin>b__1() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 177
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<Login>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 301<---


Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: GetLoginFunc/Task
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\SquareEnix\FINAL FANTASY XIV - A Realm Rebor
```

**Comment by NotNite** [comment]
Is your subscription currently active?

**Comment by Javi-22** [comment]
> Is your subscription currently active?

No. Would that be the reason?

**Comment by SyniRon** [comment]
> > Is your subscription currently active?
> 
> No. Would that be the reason?

See #1537

**Comment by Javi-22** [comment]
> > > Is your subscription currently active?
> > 
> > 
> > No. Would that be the reason?
> 
> See #1537

Thanks.
