### ISSUE TITLE
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified

### ISSUE THREAD

**Issue by Nikkicorrell** [goatcorp/FFXIVQuickLauncher#1565]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried to login.

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at XIVLauncher.Common.Util.PlatformHelpers.GetDiskFreeSpace(DirectoryInfo info) in C:\goatsoft\xl\XIVLauncher.Common\Util\PlatformHelpers.cs:line 150
   at XIVLauncher.Common.Game.Patch.PatchManager.<PatchAsync>d__38.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 122
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1392

Version: 6.4.1.0
Git Hash: 6.4.1-0-g21a73f3c
Context: HandlePatchAsync
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: F:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by w-marcossilva-2991** [comment]
I had the exact same problem. I'm using windows 10, my games instalation is in another drive, and steam recognizes and launches the game from there with no problems. Only the launcher has problems. If I remove and then reinstall the launcher, it starts the game once, but Dalamud is not injected. After that, it won't start anymore. Here's my log:

`2024-07-06 14:25:05.405 -03:00 [INF] Starting a session(v6.3.10.0 - 6.3.10-0-ge8e22c3)
2024-07-06 14:25:05.689 -03:00 [INF] Trying to set up Loc for language code pt
2024-07-06 14:25:05.729 -03:00 [INF] Starting update check...
2024-07-06 14:25:06.970 -03:00 [INF] MainWindow initialized.
2024-07-06 14:25:07.247 -03:00 [INF] [DUPDATE] Starting...
2024-07-06 14:25:07.649 -03:00 [INF] [DUPDATE] Using release version (10.0.0.0)
2024-07-06 14:25:07.968 -03:00 [INF] [DUPDATE] Now starting for .NET Runtime 8.0.0
2024-07-06 14:25:09.816 -03:00 [INF] TROUBLESHXLTING:eyJXaGVuIjoiMjAyNC0wNy0wNlQxNDoyNTowOS44MDM1MDI4LTAzOjAwIiwiSXNEeDExIjpmYWxzZSwiSXNBdXRvTG9naW4iOmZhbHNlLCJJc1VpZENhY2hlIjpmYWxzZSwiRGFsYW11ZEVuYWJsZWQiOnRydWUsIkRhbGFtdWRMb2FkTWV0aG9kIjowLCJEYWxhbXVkSW5qZWN0aW9uRGVsYXkiOjQwMDAuMCwiU3RlYW1JbnRlZ3JhdGlvbiI6ZmFsc2UsIkVuY3J5cHRBcmd1bWVudHMiOnRydWUsIkxhdW5jaGVyVmVyc2lvbiI6IjYuMy4xMC4wIiwiTGF1bmNoZXJIYXNoIjoiNi4zLjEwLTAtZ2U4ZTIyYzMiLCJPZmZpY2lhbCI6dHJ1ZSwiRHBpQXdhcmVuZXNzIjoxLCJQbGF0Zm9ybSI6MCwiT2JzZXJ2ZWRHYW1lVmVyc2lvbiI6IjIwMjQuMDcuMDYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDFWZXJzaW9uIjoiMjAyNC4wNi4xMi4wMDAwLjAwMDAiLCJPYnNlcnZlZEV4MlZlcnNpb24iOiIyMDI0LjA2LjE0LjAwMDAuMDAwMCIsIk9ic2VydmVkRXgzVmVyc2lvbiI6IjIwMjQuMDcuMDYuMDAwMC4wMDAwIiwiT2JzZXJ2ZWRFeDRWZXJzaW9uIjoiMjAyNC4wNy4wNi4wMDAwLjAwMDAiLCJCY2tNYXRjaCI6dHJ1ZSwiSW5kZXhJbnRlZ3JpdHkiOjV9
2024-07-06 14:25:10.108 -03:00 [INF] [DUPDATE] All set for 2024.06.18.0000.0000 with 10.0.0.0(8.0.0, 266)
2024-07-06 14:25:50.271 -03:00 [INF] XivGame::Login(steamServiceAccount:true, cache:false)
2024-07-06 14:25:54.371 -03:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:5
2024-07-06 14:25:54.401 -03:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyNC0wNy0wNlQxNDoyNTo1NC40MDA0NTI5LTAzOjAwIiwiSW5mbyI6IlN5c3RlbS5JTy5GaWxlTm90Rm91bmRFeGNlcHRpb246IE7Do28gZm9pIHBvc3PDrXZlbCBsb2NhbGl6YXIgbyBhcnF1aXZvICdGOlxcSm9nb3NcXHN0ZWFtYXBwc1xcY29tbW9uXFxGSU5BTCBGQU5UQVNZIFhJViBPbmxpbmVcXGJvb3RcXGZmeGl2bGF1bmNoZXIuZXhlJy5cclxuTm9tZSBkbyBhcnF1aXZvOiAnRjpcXEpvZ29zXFxzdGVhbWFwcHNcXGNvbW1vblxcRklOQUwgRkFOVEFTWSBYSVYgT25saW5lXFxib290XFxmZnhpdmxhdW5jaGVyLmV4ZSdcclxuICAgZW0gU3lzdGVtLklPLl9fRXJyb3IuV2luSU9FcnJvcihJbnQzMiBlcnJvckNvZGUsIFN0cmluZyBtYXliZUZ1bGxQYXRoKVxyXG4gICBlbSBTeXN0ZW0uSU8uRmlsZVN0cmVhbS5Jbml0KFN0cmluZyBwYXRoLCBGaWxlTW9kZSBtb2RlLCBGaWxlQWNjZXNzIGFjY2VzcywgSW50MzIgcmlnaHRzLCBCb29sZWFuIHVzZVJpZ2h0cywgRmlsZVNoYXJlIHNoYXJlLCBJbnQzMiBidWZmZXJTaXplLCBGaWxlT3B0aW9ucyBvcHRpb25zLCBTRUNVUklUWV9BVFRSSUJVVEVTIHNlY0F0dHJzLCBTdHJpbmcgbXNnUGF0aCwgQm9vbGVhbiBiRnJvbVByb3h5LCBCb29sZWFuIHVzZUxvbmdQYXRoLCBCb29sZWFuIGNoZWNrSG9zdClcclxuICAgZW0gU3lzdGVtLklPLkZpbGVTdHJlYW0uLmN0b3IoU3RyaW5nIHBhdGgsIEZpbGVNb2RlIG1vZGUsIEZpbGVBY2Nlc3MgYWNjZXNzLCBGaWxlU2hhcmUgc2hhcmUsIEludDMyIGJ1ZmZlclNpemUsIEZpbGVPcHRpb25zIG9wdGlvbnMsIFN0cmluZyBtc2dQYXRoLCBCb29sZWFuIGJGcm9tUHJveHksIEJvb2xlYW4gdXNlTG9uZ1BhdGgsIEJvb2xlYW4gY2hlY2tIb3N0KVxyXG4gICBlbSBTeXN0ZW0uSU8uRmlsZS5JbnRlcm5hbFJlYWRBbGxCeXRlcyhTdHJpbmcgcGF0aCwgQm9vbGVhbiBjaGVja0hvc3QpXHJcbiAgIGVtIFhJVkxhdW5jaGVyLkNvbW1vbi5HYW1lLkxhdW5jaGVyLkdldEZpbGVIYXNoKFN0cmluZyBmaWxlKSBuYSBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXEdhbWVcXExhdW5jaGVyLmNzOmxpbmhhIDYwMlxyXG4gICBlbSBYSVZMYXVuY2hlci5Db21tb24uR2FtZS5MYXVuY2hlci5HZXRCb290VmVyc2lvbkhhc2goRGlyZWN0b3J5SW5mbyBnYW1lUGF0aCkgbmEgQzpcXGdvYXRzb2Z0XFx4bFxcWElWTGF1bmNoZXIuQ29tbW9uXFxHYW1lXFxMYXVuY2hlci5jczpsaW5oYSAzNzBcclxuICAgZW0gWElWTGF1bmNoZXIuQ29tbW9uLkdhbWUuTGF1bmNoZXIuR2V0VmVyc2lvblJlcG9ydChEaXJlY3RvcnlJbmZvIGdhbWVQYXRoLCBJbnQzMiBleExldmVsLCBCb29sZWFuIGZvcmNlQmFzZVZlcnNpb24pIG5hIEM6XFxnb2F0c29mdFxceGxcXFhJVkxhdW5jaGVyLkNvbW1vblxcR2FtZVxcTGF1bmNoZXIuY3M6bGluaGEgMjg3XHJcbiAgIGVtIFhJVkxhdW5jaGVyLkNvbW1vbi5HYW1lLkxhdW5jaGVyLjxSZWdpc3RlclNlc3Npb24+ZF9fMjEuTW92ZU5leHQoKSBuYSBDOlxcZ29hdHNvZnRcXHhsXFxYSVZMYXVuY2hlci5Db21tb25cXEdhbWVcXExhdW5jaGVyLmNzOmxpbmhhIDQxOFxyXG4tLS0gRmltIGRvIHJhc3RyZWFtZW50byBkZSBwaWxoYSBkbyBsb2NhbCBhbnRlcmlvciBvbmRlIGEgZXhjZcOnw6NvIGZvaSBnZXJhZGEgLS0tXHJcbiAgIGVtIFN5c3RlbS5SdW50aW1lLkV4Y2VwdGlvblNlcnZpY2VzLkV4Y2VwdGlvbkRpc3BhdGNoSW5mby5UaHJvdygpXHJcbiAgIGVtIFN5c3RlbS5SdW50aW1lLkNvbXBpbGVyU2VydmljZXMuVGFza0F3YWl0ZXIuSGFuZGxlTm9uU3VjY2Vzc0FuZERlYnVnZ2VyTm90aWZpY2F0aW9uKFRhc2sgdGFzaylcclxuICAgZW0gWElWTGF1bmNoZXIuQ29tbW9uLkdhbWUuTGF1bmNoZXIuPExvZ2luPmRfXzE0Lk1vdmVOZXh0KCkgbmEgQzpcXGdvYXRzb2Z0XFx4bFxcWElWTGF1bmNoZXIuQ29tbW9uXFxHYW1lXFxMYXVuY2hlci5jczpsaW5oYSAyMDVcclxuLS0tIEZpbSBkbyByYXN0cmVhbWVudG8gZGUgcGlsaGEgZG8gbG9jYWwgYW50ZXJpb3Igb25kZSBhIGV4Y2XDp8OjbyBmb2kgZ2VyYWRhIC0tLVxyXG4gICBlbSBTeXN0ZW0uUnVudGltZS5FeGNlcHRpb25TZXJ2aWNlcy5FeGNlcHRpb25EaXNwYXRjaEluZm8uVGhyb3coKVxyXG4gICBlbSBTeXN0ZW0uUnVudGltZS5Db21waWxlclNlcnZpY2VzLlRhc2tBd2FpdGVyLkhhbmRsZU5vblN1Y2Nlc3NBbmREZWJ1Z2dlck5vdGlmaWNhdGlvbihUYXNrIHRhc2spXHJcbiAgIGVtIFhJVkxhdW5jaGVyLldpbmRvd3MuVmlld01vZGVsLk1haW5XaW5kb3dWaWV3TW9kZWwuPFRyeUxvZ2luVG9HYW1lPmRfXzIzLk1vdmVOZXh0KCkgbmEgRDpcXGFcXEZGWElWUXVpY2tMYXVuY2hlclxcRkZYSVZRdWlja0xhdW5jaGVyXFxzcmNcXFhJVkxhdW5jaGVyXFxXaW5kb3dzXFxWaWV3TW9kZWxcXE1haW5XaW5kb3dWaWV3TW9kZWwuY3M6bGluaGEgMzkyIiwiQ29udGV4dCI6IlN0YXJ0R2FtZSBmYWlsZWQuLi4gKExvZ2luU3RhdHVzPVRydWUpIn0=
2024-07-06 14:25:54.386 -03:00 [ERR] StartGame failed... (LoginStatus=true)
System.IO.FileNotFoundException: Não foi possível localizar o arquivo 'F:\Jogos\steamapps\common\FINAL FANTASY XIV Online\boot\ffxivlauncher.exe'.
Nome do arquivo: 'F:\Jogos\steamapps\common\FINAL FANTASY XIV Online\boot\ffxivlauncher.exe'
   em System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   em System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   em System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   em XIVLauncher.Common.Game.Launcher.GetFileHash(String file) na C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:linha 602
   em XIVLauncher.Common.Game.Launcher.GetBootVersionHash(DirectoryInfo gamePath) na C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:linha 370
   em XIVLauncher.Common.Game.Launcher.GetVersionReport(DirectoryInfo gamePath, Int32 exLevel, Boolean forceBaseVersion) na C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:linha 287
   em XIVLauncher.Common.Game.Launcher.<RegisterSession>d__21.MoveNext() na C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:linha 418
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em XIVLauncher.Common.Game.Launcher.<Login>d__14.MoveNext() na C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:linha 205
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryLoginToGame>d__23.MoveNext() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:linha 392
`
