### ISSUE TITLE
Unhandle Error countinous showing up everytime i try log in on FFXIV

### ISSUE THREAD

**Issue by padrejudas000** [goatcorp/FFXIVQuickLauncher#1569]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Just opened the XIV Launcher then hit launcher, but every time i keep getting the same error over and over

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at XIVLauncher.App.DalamudOverlayThreadStart() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:line 227
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Version: 6.4.1.0
Git Hash: 6.4.1-0-g21a73f3c
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by shadowkras** [comment]
Another year, and this error still plagues a lot of users.

**Comment by KazWolfe** [comment]
We finally managed to track down this error. It's related to Warsaw, an application used (seemingly most frequently) by Brazilian banks. Warsaw causes unexpected and strange behavior, with this being a side effect.

Users experiencing this problem will ultimately need to uninstall Warsaw, or not use XL. See #1718.

**Comment by reiichi001** [comment]
Also G-buster, which is another product by the same developers / replacement. (Warsaw and G-buster are almost exclusively used in Brazil, and they break other programs too).

It's basically the banking equivalent to kernel anti-cheat you find in other games.
