### ISSUE TITLE
Error when starting the game

### ISSUE THREAD

**Issue by guilhermemrk** [goatcorp/FFXIVQuickLauncher#217]
The launcher opens without a problem, when I press Login, these errors show up.
The game opens normally but I think the launcher's integrations fails to load.

Error 1:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at XIVLauncher.Windows.MainWindow.<StartGame>d__13.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 396
Version: 4.9.2.0
Git Hash: bfd5a4c
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online


Addons: []
```

Error 2
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Addon.AddonManager.StopAddons() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\AddonManager.cs:line 54
   at XIVLauncher.Windows.MainWindow.<StartGame>d__13.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 412
Version: 4.9.2.0
Git Hash: bfd5a4c
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online


Addons: []
```

**Comment by Aida-Enna** [comment]
Hey there! It's been a while since this was opened - Are you still having this issue?
