### ISSUE TITLE
Error while patching on 11/8

### ISSUE THREAD

**Issue by Shak14** [goatcorp/FFXIVQuickLauncher#256]
System.Net.Sockets.SocketException (0x80004005): Only one usage of each socket address (protocol/network address/port) is normally permitted
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchInstaller.cs:line 48
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 127
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 484
Version: 5.1.1.0
Git Hash: 807acc0
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? True
Language: English
Game path: E:\Program Files (x86)\FF14 Custom

Addons: []

**Comment by goaaats** [comment]
This happens when two instances of XL and the patcher are running.
We already have an issue for it and are looking into fixing it, thank you.
