### ISSUE TITLE
XIVLauncher Error - Game launches, but XIVL doesn't attach anything?

### ISSUE THREAD

**Issue by Rukongai** [goatcorp/FFXIVQuickLauncher#262]
The game works fine otherwise. Just no addon functionality. 

System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 49
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.1.1.0
Git Hash: 807acc0
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Rukongai** [comment]
Solution

I run 2 copies of FFXIV. The second is my market alt for reselling crafted items on other worlds.

By closing both copies of the game, the launcher was able to relaunch the game just fine and everything worked.
