### ISSUE TITLE
Cannot inject dalamud if another instance with dalamud injected is already open

### ISSUE THREAD

**Issue by Aida-Enna** [goatcorp/FFXIVQuickLauncher#268]
Usually, but not always, Dalamud will fail to inject into a second started instance of FFXIV. It will fail repeatedly until I close the already open instance, then I can open them both like normal. Here is the error:

```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 49
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.1.1.0
Git Hash: 807acc0
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: E:\Games\FINAL FANTASY XIV - A Realm Reborn


Addons: []
```

**Comment by goaaats** [comment]
I unified this issue into #285, thanks!
