### ISSUE TITLE
Launcher doesn't lauches game

### ISSUE THREAD

**Issue by rsod** [goatcorp/FFXIVQuickLauncher#270]
First, it asks to do an update:
![image](https://user-images.githubusercontent.com/5073202/91493015-47d8a780-e8bf-11ea-9afe-6856f5f72108.png)
If I refuse update, it just doesn't starts the game, if I agree to update it just shows this error:
```
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at XIVLauncher.Game.Patch.PatchManager..ctor(Repository repository, IEnumerable`1 patches, DirectoryInfo gamePath, DirectoryInfo patchStore, PatchInstaller installer) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 91
   at XIVLauncher.Windows.MainWindow.InstallGamePatch(LoginResult loginResult, Boolean gateStatus) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 404
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 484
Version: 5.1.1.0
Git Hash: 807acc0
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online


Addons: []
```

**Comment by rsod** [comment]
For some reason on first reinstall problem persisted, but on second installation it was gone. So it works now reliably and I can't reproduce it anymore, so I close the issue
