### ISSUE TITLE
launcher error

### ISSUE THREAD

**Issue by MyTechnoHunter** [goatcorp/FFXIVQuickLauncher#283]
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 386
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 132
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 456
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 386
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.1.1.0

**Comment by Aida-Enna** [comment]
Hey @MyTechnoHunter - Is this still an issue? It seems like it might have been a one-off issue with Github.

**Comment by CalionSilus** [comment]
When I first install xivlauncher setup on new Desktop, I saw message below capture. Please help

![image](https://user-images.githubusercontent.com/66424727/95059396-cbde4480-0733-11eb-886e-0f36d090960b.png)

System info
OS name:                 Microsoft Windows 10 Home
OS version:                 10.0.19041 N/A 빌드 19041
OS 제조업체:             Microsoft Corporation
OS 구성:                 독립 실행형 워크스테이션
OS 빌드 종류:            Multiprocessor Free
등록된 소유자:           HOME
등록된 조직:
제품 ID:                 00326-10046-50370-AA055
원래 설치 날짜:          2020-09-20, 오후 6:13:27
시스템 부트 시간:        2020-10-05, 오후 5:26:07
시스템 제조업체:         Micro-Star International Co., Ltd.
시스템 모델:             MS-7C94
시스템 종류:             x64-based PC
프로세서:                프로세서 1개 설치됨
                         [01]: AMD64 Family 23 Model 113 Stepping 0 AuthenticAMD ~3800Mhz
BIOS 버전:               American Megatrends Inc. 1.00, 2020-05-12
Windows 디렉터리:        C:\WINDOWS
시스템 디렉터리:         C:\WINDOWS\system32
부팅 장치:               \Device\HarddiskVolume2
시스템 로캘:             ko;한국어
입력 로캘:               ko;한국어
표준 시간대:             (UTC+09:00) 서울
총 실제 메모리:          32,716MB
사용 가능한 실제 메모리: 24,362MB
가상 메모리: 최대 크기:  37,580MB
가상 메모리: 사용 가능:  26,737MB
가상 메모리: 사용 중:    10,843MB
페이지 파일 위치:        C:\pagefile.sys
도메인:                  WORKGROUP
로그온 서버:             \\CALION-OFFICE
핫픽스:                  핫픽스 5개 설치됨
                         [01]: KB4576945
                         [02]: KB4561600
                         [03]: KB4570334
                         [04]: KB4577266
                         [05]: KB4571756
네트워크 카드:           NIC 4개 설치됨
                         [01]: Realtek PCIe 2.5GbE Family Controller
                               연결 이름: 이더넷 5
                               DHCP 사용: 예
                               DHCP 서버: 192.168.0.1
                               IP 주소
                               [01]: 192.168.0.131
                               [02]: fe80::8058:d53f:974a:5f82
                         [02]: TAP-Win32 Adapter V9
                               연결 이름: 이더넷 6
                               상태:      미디어 연결이 끊어짐
                         [03]: TAP-NordVPN Windows Adapter V9
                               연결 이름: 이더넷 7
                               상태:      미디어 연결이 끊어짐
                         [04]: Nlwt Tun
                               연결 이름: NordLynx
                               DHCP 사용: 아니요
                               IP 주소
                               [01]: 10.5.0.2
Hyper-V 요구 사항:       VM 모니터 모드 확장: 예
                         펌웨어에 가상화 사용: 예
                         두 번째 수준 주소 변환: 예
                         데이터 실행 방지 사용 가능: 예

**Comment by goaaats** [comment]
This is not a XIVLauncher issue, but an issue with your route to the SE login server.
A possible fix is using a VPN, mudfish or another DNS server.
