### ISSUE TITLE
GitHub TLS connection not working on wine

### ISSUE THREAD

**Issue by Bimahi** [goatcorp/FFXIVQuickLauncher#305]
XIV Launcher errors out on game launch with the following exception:
`System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess, Boolean doDownloads) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 95
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 51
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.1.1.0
Git Hash: 807acc0
Context: Unhandled
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? False
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []
`

Game then launches without error but dalamud plugin is not working.
OS: Linux running Proton 5.6

**Comment by kainz0r** [comment]
Getting the same error just starting today on two separate computers, as far as I know nothing was changed on either system.

Running on Manjaro Linux 5.9 kernel with Proton-5.8-GE; no updates or other changes I know of. Issue is not present on a Windows system. According to output.log the same version of xivlauncher-5.1.1.0-807acc0 succeeded yesterday with no issues.

**Comment by Sanaki** [comment]
Same issue here. Mint 19.3, Lutris, ge-protonified-4.10-x86_64. Reported it in discord yesterday as well, but I'm not sure they know how to approach this one at the moment.

**Comment by goaaats** [comment]
So this seems to be related to some change at GitHub related to the SLL cert they use.
A user in the discord remarked that it works fine on the [latest GE proton](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/5.9-GE-8-ST), so I'm not sure how to proceed here. It's certainly not an issue on Windows and I sadly don't have a Linux setup to test with at the moment.

One option would be to compile a build of XL that prints some better debug info about the SSL error.

**Comment by Bimahi** [comment]
For me, versions of proton GE past 5.7 have really bad frame drops in instances. I'd def be willing to test a version of xl with the better debug info.

**Comment by kainz0r** [comment]
Perhaps as an interim solution, you could disable the in-game plugin update checking/connectivity under the same update disable that XL_WINEONLINUX = true can toggle, and add in the additional debug logging for the SSL error?

Sadly although Proton-5.9-GE-8-ST works with whatever the new SSL requirements are, 5.9 isn't working on a couple of systems I'm testing from (unknown reasons), and it's also not working with CMTool on any system. I think it also might not be performing as well as the previously preferred versions, but it's kinda hard to capture evidence on that even with MangoHud graphing.

**Comment by Bimahi** [comment]
I can confirm 5.9 heavily underperforms in E8S, I vary between 144-100 using Proton 5.6 and tank down to 50-60 fps in 5.9.

**Comment by goaaats** [comment]
Seems like the wine version that causes issues has slightly different handling of the chosen security protocols than what Windows has.

Here's a version that might fix it, please give it a shot:
[xl_tls13.zip](https://github.com/goatcorp/FFXIVQuickLauncher/files/5538628/xl_tls13.zip)

**Comment by Bimahi** [comment]
Still errors out with the same error.

**Comment by kainz0r** [comment]
Same result here, here's my output.log from the attempt which shows the changed version:

```
2020-11-13 12:22:42.576 -06:00 [INF] Trying to set up Loc for culture en
2020-11-13 12:22:42.666 -06:00 [INF] XIVLauncher started as xivlauncher-5.1.1.0-807acc0-dirty
2020-11-13 12:22:42.784 -06:00 [INF] Loading MainWindow for account ''
2020-11-13 12:22:44.379 -06:00 [INF] MainWindow initialized.
2020-11-13 12:22:47.408 -06:00 [INF] CurrentAccount: *****-True-False
2020-11-13 12:22:55.571 -06:00 [INF] StartGame() called
2020-11-13 12:22:55.745 -06:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2020-11-13 12:22:55.745 -06:00 [INF] Cache is invalid or disabled, logging in normally.
2020-11-13 12:22:56.877 -06:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:3
2020-11-13 12:22:58.031 -06:00 [INF] XivGame::LaunchGame(steamIntegration:False, steamServiceAccount:False, args:)
2020-11-13 12:22:58.032 -06:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:272693816 ticks:272693816 key:272629760
2020-11-13 12:22:58.038 -06:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"f"
2020-11-13 12:22:59.531 -06:00 [INF] Starting PersistentAddon XIVLauncher in-game features
2020-11-13 12:23:00.652 -06:00 [ERR] Unhandled exception.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess, Boolean doDownloads) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 95
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 51
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by goaaats** [comment]
How about this one?

[xl_tls13_2.zip](https://github.com/goatcorp/FFXIVQuickLauncher/files/5538686/xl_tls13_2.zip)

**Comment by kainz0r** [comment]
Same for this one, here's the updated log output:

```
2020-11-13 12:38:27.196 -06:00 [INF] Trying to set up Loc for culture en
2020-11-13 12:38:27.288 -06:00 [INF] XIVLauncher started as xivlauncher-5.1.1.0-807acc0-dirty
2020-11-13 12:38:27.373 -06:00 [INF] Loading MainWindow for account ''
2020-11-13 12:38:29.210 -06:00 [INF] MainWindow initialized.
2020-11-13 12:38:33.495 -06:00 [INF] CurrentAccount: *****-True-False
2020-11-13 12:38:38.170 -06:00 [INF] StartGame() called
2020-11-13 12:38:38.373 -06:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2020-11-13 12:38:38.373 -06:00 [INF] Cache is invalid or disabled, logging in normally.
2020-11-13 12:38:39.475 -06:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:3
2020-11-13 12:38:40.697 -06:00 [INF] XivGame::LaunchGame(steamIntegration:False, steamServiceAccount:False, args:)
2020-11-13 12:38:40.698 -06:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:273636482 ticks:273636482 key:273612800
2020-11-13 12:38:40.703 -06:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"L"
2020-11-13 12:38:42.348 -06:00 [INF] Starting PersistentAddon XIVLauncher in-game features
2020-11-13 12:38:43.353 -06:00 [ERR] Unhandled exception.
System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess, Boolean doDownloads) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 95
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 51
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
```

**Comment by sangoku116** [comment]
I am having the same issue here on arch linux and zen kernel 5.9 with proton 5.5-GE-1

**Comment by goaaats** [comment]
I just refixed the fix, should be fine now.

**Comment by Sanaki** [comment]
The fix refix is confirmed fixed. Thanks!

**Comment by sangoku116** [comment]
I confirm it works on my end as well, thank you!
