### ISSUE TITLE
Cannot Boot QuickLauncher

### ISSUE THREAD

**Issue by MosImba** [goatcorp/FFXIVQuickLauncher#315]
This is the error I am receiving:

System.Net.WebException: The remote server returned an error: (504) Gateway Timeout.
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at XIVLauncher.Game.Launcher.CheckBootVersion(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 326
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 260
Version: 5.1.1.0
Git Hash: 807acc0
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: D:\Final Fantasy 14\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

How may I fix this? Thank you!

**Comment by goaaats** [comment]
The game is currently under maintenance: http://na.finalfantasyxiv.com/lodestone/news/detail/6a0586063843b8d2e21efcbc831b6dc3066587ad
