### ISSUE TITLE
Error and doesn't load with plugins

### ISSUE THREAD

**Issue by KhaozFrost** [goatcorp/FFXIVQuickLauncher#327]
after the latest patch 5.4 I get dced from the server; goto log back into the world and it random closes the whole client without even an error; then I open xivlauncher again, input everything and this gets thrown every time. 

System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 46
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.2.0.0
Git Hash: 7f46f54
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by AmenneHolelane** [comment]
The version of the launcher you're using is old, update please - there's a script included with lutris, if you're on Linux.

We don't support old versions.

**Comment by reiichi001** [comment]
Hello,

The error above looks like what happens when Dalamud does not exit cleanly. If the game crashes, you may need to go into the task manager and manually kill any processes named "xivlauncher.exe" to close them out.

Most likely, the initial crash is caused by a plugin that is failing to load or out of date as of 5.4. I would recommend manually clearing out your installedPlugins folder from `%AppData%\XIVLauncher\` with the game closed. Then start FFXIV again and reinstall from the available plugins list or consult the developers of any unsupported plugins for updates.

**Comment by Aida-Enna** [comment]
Closing due to inactivity.
