### ISSUE TITLE
getting this error

### ISSUE THREAD

**Issue by stewarthadley** [goatcorp/FFXIVQuickLauncher#330]
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.String.StartsWith(String value)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess, Boolean doDownloads) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 108
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 48
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.2.0.0
Git Hash: 7f46f54
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by reiichi001** [comment]
Hello,

It looks like the in-game addon failed to download or versioncheck. This could be caused by your antivirus removing it.

Please try:
1. whitelist `%AppData%\XIVLauncher\` 
2. Delete `%AppData%\XIVLauncher\addon\Hooks\`
3. Relaunch

If the issue persists, please let us know.

**Comment by stewarthadley** [comment]
deleting hooks folder fixed it. Thanks!
