### ISSUE TITLE
Error When Launching Game

### ISSUE THREAD

**Issue by V1B3Gaming** [goatcorp/FFXIVQuickLauncher#334]
System.AggregateException: One or more errors occurred. ---> System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 132
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 450
---> (Inner Exception #0) System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.2.0.0
Git Hash: 7f46f54
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by reiichi001** [comment]
Hello,

Is this issue still occurring?

If so, are you able to login with the official launcher to see if that's working? XIVLauncher should be using the same files to run a version check and if the normal launcher doesn't work, XIVLauncher will also fail.

**Comment by Aida-Enna** [comment]
Closing due to inactivity.
