### ISSUE TITLE
Start up errors

### ISSUE THREAD

**Issue by feliou** [goatcorp/FFXIVQuickLauncher#337]
Error 1:
System.ArgumentNullException: Value cannot be null.
Parameter name: source
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at XIVLauncher.Windows.MainWindow.<StartGameAndAddon>d__17.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 557
Version: 5.2.0.0
Git Hash: 7f46f54
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

Error 2:
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVLauncher.Addon.AddonManager.StopAddons() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\AddonManager.cs:line 54
   at XIVLauncher.Windows.MainWindow.<StartGameAndAddon>d__17.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 573
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__16.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 494
Version: 5.2.0.0
Git Hash: 7f46f54
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Aireil** [comment]
You can either delete the config file of the launcher `%AppData%\XIVLauncher\launcherConfigV3.json` or add the missing field in it `"AddonList": "[]"`

**Comment by Aida-Enna** [comment]
Closing due to inactivity.
