### ISSUE TITLE
Launcher error (2 instances)

### ISSUE THREAD

**Issue by em452e** [goatcorp/FFXIVQuickLauncher#343]
I get this error whenever launching my second instance of ffxiv: 

```
System.Threading.AbandonedMutexException: The wait completed due to an abandoned mutex.
   at System.Threading.WaitHandle.ThrowAbandonedMutexException()
   at System.Threading.WaitHandle.InternalWaitOne(SafeHandle waitableSafeHandle, Int64 millisecondsTimeout, Boolean hasThreadAffinity, Boolean exitContext)
   at System.Threading.WaitHandle.WaitOne(Int32 millisecondsTimeout, Boolean exitContext)
   at XIVLauncher.Dalamud.DalamudLauncher.DoWork(Object state) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 46
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart(Object obj)
Version: 5.2.0.0
Git Hash: 7f46f54
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online


Addons: []
```

Does it just not support multiple instances or am I doing something wrong?
It launches the game fine btw before quitting with the error, but plugins will not work in the second instance.
Also one instance is Windows version while the other is Steam.

**Comment by goaaats** [comment]
2 should be fine, this is a known bug - will look into it.

**Comment by em452e** [comment]
There was an update and I'm currently running 2 instances with no issue. It's safe to close this I think
