### ISSUE TITLE
Error when trying to download a new patch

### ISSUE THREAD

**Issue by Crazy6a3er** [goatcorp/FFXIVQuickLauncher#351]
When there is a new patch, this message will always pop out.
![image](https://user-images.githubusercontent.com/23329907/104313900-abccd700-5513-11eb-9cdf-096dfee5813e.png)

After clicking "Yes", it hits an error. So far the workaround is to use Official FFXIV launcher to download the new patch.
```
System.UnauthorizedAccessException: Access to the path 'C:\Users\ming_\AppData\Roaming\XIVLauncher\patches' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at XIVLauncher.Game.Patch.PatchManager..ctor(Repository repository, IEnumerable`1 patches, DirectoryInfo gamePath, DirectoryInfo patchStore, PatchInstaller installer) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 91
   at XIVLauncher.Windows.MainWindow.InstallGamePatch(LoginResult loginResult, Boolean gateStatus) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 414
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 494
Version: 5.2.1.0
Git Hash: 0fc3088
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []
```

**Comment by goaaats** [comment]
Try checking your antivirus

**Comment by Crazy6a3er** [comment]
> Try checking your antivirus

I have disabled all antivirus (Malwarebytes and Windows 10 Anti-Virus) and is still facing the same error.

**Comment by Crazy6a3er** [comment]
Hi all, I manage to fix it by changing the "Patch Download Directory". The reason why it was wrong was because I recently reinstalled Windows 10 and the path has been changed.
![image](https://user-images.githubusercontent.com/23329907/104324103-f48b8c80-5521-11eb-8f15-2a2490fb4981.png)
