### ISSUE TITLE
Error code

### ISSUE THREAD

**Issue by aaceace** [goatcorp/FFXIVQuickLauncher#361]
System.Net.WebException: The operation has timed out
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at XIVLauncher.Game.Launcher.CheckBootVersion(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 326
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 240
Version: 5.2.1.0
Git Hash: 0fc3088
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by goaaats** [comment]
Check your internet connection
