### ISSUE TITLE
launcher issues

### ISSUE THREAD

**Issue by AlexisBliss** [goatcorp/FFXIVQuickLauncher#368]
hey so i keep gettign booted formthe game consistentaly and when i did a check on my launcher i was given this 

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxivgame.ver' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\SettingsControl.xaml.cs:line 241
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxivgame.ver' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\SettingsControl.xaml.cs:line 241
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.2.1.0
Git Hash: 0fc3088
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

any help would be greatly apprieciated

**Comment by Aida-Enna** [comment]
That means something is locking the file it listed - Reboot your computer and try again.

**Comment by AlexisBliss** [comment]
ok so i did a restart and this is what i got again 
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxivgame.ver' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\SettingsControl.xaml.cs:line 241
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxivgame.ver' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\SettingsControl.xaml.cs:line 241
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.2.1.0
Git Hash: 0fc3088
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []

**Comment by Aida-Enna** [comment]
That's very weird - Try deleting the `C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\game\ffxivgame.ver` file manually and see if it lets you. If it does, try running the Launcher again. If not, there may be something weird going on with your system.

**Comment by AlexisBliss** [comment]
ok so i did the things you suggested but its still not workign i uninstalled the game and the launcher and ran re-installed the origanal laumcher and there is no issues with that on i then re-installed this launcher and then within 5 mins of a raid it boots me right out of the game

**Comment by reiichi001** [comment]
Can you please upload some logs to the GH issue or into the xivlauncher discord?

Please send us your **output.log** log file from `%appdata%\XIVLauncher\`
**DISCLAIMER**: This log will contain your ffxiv username[s]. If you're not comfortable posting that here, you can DM to a trusted dev/mod or open the file in a text editor to redact that information first.

Please send us your **dalamud.txt** log file from `%appdata%\XIVLauncher\addon\Hooks\` 
**DISCLAIMER**: This log will contain your computer username. If you're not comfortable posting that here, you can DM to a trusted dev/mod or open the file in a text editor to redact that information first.

**Comment by AlexisBliss** [comment]
ofc once i have finished in raid i will do thank you

**Comment by AlexisBliss** [comment]
everythign seems to be ok atm so i will close this for now thank you for the swift assistance
