### ISSUE TITLE
could not patch boot

### ISSUE THREAD

**Issue by splendiferachie** [goatcorp/FFXIVQuickLauncher#370]
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt64(String value, NumberStyles options, NumberFormatInfo numfmt)
   at XIVLauncher.Game.Patch.PatchList.PatchListParser.Parse(String list) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchList\PatchListParser.cs:line 23
   at XIVLauncher.Game.Launcher.CheckBootVersion(DirectoryInfo gamePath) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 333
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 240
Version: 5.2.1.0
Git Hash: 0fc3088
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by reiichi001** [comment]
Is the official launcher working for you?

**Comment by splendiferachie** [comment]
no... i probably should have checked first, really sorry to bother ;;

**Comment by reiichi001** [comment]
This helps us ensure it's not an issue caused by xivlauncher. Is this a new installation of FFXIV or does the official launcher give you any more information?

It's possible your antivirus may have removed some files if this is your first time using xivlauncher.

**Comment by splendiferachie** [comment]
the official launcher gives me 3 error codes, i think it's a problem with my internal ffxiv files. i've been using xivlauncher for a while, this afternoon while i was playing it was fine! i have a feeling it may be as you said - either my antivirus or a vpn issue with my router.

**Comment by Aida-Enna** [comment]
@splendiferachie Did you ever get this figured out?
