### ISSUE TITLE
XL on Wine cannot download game patches in version 5.3.0.0

### ISSUE THREAD

**Issue by reiichi001** [goatcorp/FFXIVQuickLauncher#389]
XL 5.3.0.0 Wine on Linux cannot download game patches. Also seems to have trouble making it past initial onboarding as it re-prompts each start.

System.Net.Sockets.SocketException (0x80004005): Unknown error (0x271d)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchInstaller.cs:line 70
   at XIVLauncher.Game.Patch.PatchManager.Start() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 136
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 328
Version: 5.3.0.0
Git Hash: 011a69b
Context: HandleBootCheck
OS: Linux (Windows 7 SP1 in Wine)
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by reiichi001** [comment]
It was a "port number used is too low" issue.
https://github.com/goatcorp/FFXIVQuickLauncher/pull/390 fixes it.
