### ISSUE TITLE
Error Report: XIVLauncher

### ISSUE THREAD

**Issue by Pneumonica** [goatcorp/FFXIVQuickLauncher#391]
Error was caused after it notified me I needed a patch to continue. I am running Kubuntu 20.04 and using Lutris. Error comes up repeatedly, and appears to cause the launcher to hang on a small window that says, "Patching through 0/2 updates." The window shows four bars with "download done" and one bar with "installing #0" that never seems to fill in. Error text follows.

```
System.Net.Sockets.SocketException (0x80004005): Unknown error (0x271d)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchInstaller.cs:line 70
   at XIVLauncher.Game.Patch.PatchManager.Start() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 136
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 570
Version: 5.3.0.0
Git Hash: 011a69b
Context: Login
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []
```

**Comment by goaaats** [comment]
This is already fixed, were just waiting to deploy it
