### ISSUE TITLE
XIVLauncher Error on Ubuntu 20.10 (Pop OS)

### ISSUE THREAD

**Issue by marklabrecque** [goatcorp/FFXIVQuickLauncher#393]
Context: This is after initial install. I have copied over the Final Fantasy XIV installed folder from my external drive and went through the XIVLauncher setup wizard to point it at that folder. The FFXIV needs an update from the SquareEnix servers, so XIVLauncher tries to fetch the update and this is where the following error shows up:

```
System.Net.Sockets.SocketException (0x80004005): Unknown error (0x271d)
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchInstaller.cs:line 70
   at XIVLauncher.Game.Patch.PatchManager.Start() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:line 136
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 570
Version: 5.3.0.0
Git Hash: 011a69b
Context: Login
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []
```

**Comment by goaaats** [comment]
Known issue, we already have a fix pending, will release soon.

#389
