### ISSUE TITLE
Error at login

### ISSUE THREAD

**Issue by nevoreko** [goatcorp/FFXIVQuickLauncher#430]
Hey I can't login on Fedora with Lutris with the error:
```
System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 136
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 516
---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 390
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 5.4.0.0
Git Hash: caa764d
Context: Login
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn


Addons: []
```

**Comment by reiichi001** [comment]
Fedora users need to downgrade their SSL/TLS settings as something is weird about how Wine handles them.

You will need to run `sudo update-crypto-policies --set LEGACY`, noting that this could potentially reduce security.

See https://github.com/goatcorp/FFXIVQuickLauncher/issues/360 for more detail.

**Comment by nevoreko** [comment]
> Fedora users need to downgrade their SSL/TLS settings as something is weird about how Wine handles them.
> 
> You will need to run `sudo update-crypto-policies --set LEGACY`, noting that this could potentially reduce security.
> 
> See #360 for more detail.

Thanks for the quick answer, it worked! Do you know in what sense it reduces security?

**Comment by reiichi001** [comment]
See this page for details. 
https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2

**Comment by nevoreko** [comment]
Thanks!
