### ISSUE TITLE
launcher error

### ISSUE THREAD

**Issue by beholding** [goatcorp/FFXIVQuickLauncher#434]
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:line 133
   at XIVLauncher.Addon.AddonManager.RunAddons(Process gameProcess, ILauncherSettingsV3 setting, List`1 addonEntries) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Addon\AddonManager.cs:line 42
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<StartGameAndAddon>d__18.MoveNext() in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:line 698
Version: 5.4.0.0
Git Hash: caa764d
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by goaaats** [comment]
Sounds like your antivirus, please check our FAQ or join our Discord.
If this is a bug, please write a real issue report([check the templates](https://github.com/goatcorp/FFXIVQuickLauncher/issues/new/choose)) and try again.
