### ISSUE TITLE
Steam integration is not working

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#477]
Might have broken with #458 

```
2021-07-10 13:20:23.043 -04:00 [INF] XivGame::LaunchGame(steamIntegration:True, steamServiceAccount:True, args:)
2021-07-10 13:20:23.047 -04:00 [ERR] Could not initialize Steam.
System.ArgumentNullException: Value cannot be null.
Parameter name: input
   at System.IO.BinaryReader..ctor(Stream input, Encoding encoding, Boolean leaveOpen)
   at SteamworksSharp.Native.Libs.LibUtils.ReadResourceBytes(Assembly assembly, String resourceName) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\SteamWorksSharp\Native\Libs\LibUtils.cs:line 11
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at SteamworksSharp.Native.SteamNative.WriteNativeLibrary() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\SteamWorksSharp\Native\SteamNative.cs:line 58
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 179
```

**Comment by RobertoJKN** [comment]
Hello, thank you for finding the issue so fast! I don't want to sound rude, but any ETA on a fix?
