### ISSUE TITLE
System.OutOfMemoryException: STATUS_NO_MEMORY

### ISSUE THREAD

**Issue by Fyea** [goatcorp/FFXIVQuickLauncher#480]
**Describe the bug here:**
My Dalamud won't inject in my game and it keeps giving me this error on the log.

**Steps to reproduce the bug:**

``Enable in-game functionality in the launcher``
``Launch the game``

**Expected behavior**
Game starts without error and inject the Dalamud

**Other information (*please* complete the following information):**
  Operating System: Windows 10, latest version
  XIVLauncher version: 6.0.4.0 (it is like this for some versions already, even before the 6.0)
  Launching as admin?:  No
  Using Steam?: Yes
  Addons/Plugins enabled: Yes

**Additional information**

1. If I open the game injecting SpecialK from Kaldaien, it doesn't give me this error, and for some reason the Dalamud injects as expected.

2. Log with the error:

```
2021-07-08 12:25:03.161 -03:00 [INF] --------------------------------------------------------------------------------
2021-07-08 12:25:03.169 -03:00 [INF] Initializing a session..
2021-07-08 12:25:03.173 -03:00 [INF] Starting a session..
2021-07-08 12:25:03.550 -03:00 [ERR] Tier 1 load failed.
System.OutOfMemoryException: STATUS_NO_MEMORY: Failed to allocate memory. (Code: 487)
   at EasyHook.LocalHook.Create(IntPtr InTargetProc, Delegate InNewProc, Object InCallback)
   at Dalamud.Hooking.Hook`1..ctor(IntPtr address, Delegate detour, Object callbackParam) in C:\goatsoft\companysecrets\dalamud\Hooking\Hook.cs:line 32
   at Dalamud.Game.Internal.Framework.HookVTable() in C:\goatsoft\companysecrets\dalamud\Game\Internal\Framework.cs:line 103
   at Dalamud.Game.Internal.Framework..ctor(SigScanner scanner, Dalamud dalamud) in C:\goatsoft\companysecrets\dalamud\Game\Internal\Framework.cs:line 86
   at Dalamud.Dalamud.LoadTier1() in C:\goatsoft\companysecrets\dalamud\Dalamud.cs:line 204
2021-07-08 12:25:03.553 -03:00 [INF] Trigger unload
2021-07-08 12:25:03.554 -03:00 [ERR] Plugin unload failed.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dalamud.Dalamud.DisposePlugins() in C:\goatsoft\companysecrets\dalamud\Dalamud.cs:line 399
2021-07-08 12:25:03.658 -03:00 [INF] Session has ended.
```
2. Log with SpecialK:
```
2021-07-11 17:38:34.830 -03:00 [INF] Initializing a session..
2021-07-11 17:38:34.835 -03:00 [INF] Starting a session..
2021-07-11 17:38:37.144 -03:00 [INF] [T1] Framework OK!
2021-07-11 17:38:37.146 -03:00 [INF] [T1] Framework ENABLE!
2021-07-11 17:38:37.327 -03:00 [INF] [T2] AntiDebug OK!
2021-07-11 17:38:37.331 -03:00 [INF] [T2] WinSock OK!
2021-07-11 17:38:37.331 -03:00 [INF] [T2] NH OK!
2021-07-11 17:38:37.725 -03:00 [INF] [T2] CS OK!
2021-07-11 17:38:37.734 -03:00 [INF] [T2] LOC OK!
2021-07-11 17:38:38.583 -03:00 [INF] [T2] IM OK!
2021-07-11 17:38:39.162 -03:00 [INF] Lumina is ready: G:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online\game\sqpack
2021-07-11 17:38:39.163 -03:00 [INF] [T2] Data OK!
2021-07-11 17:38:39.164 -03:00 [INF] [T2] SeString OK!
2021-07-11 17:38:39.168 -03:00 [INF] [T2] CM OK!
2021-07-11 17:38:39.184 -03:00 [INF] [T2] CH OK!
2021-07-11 17:38:39.184 -03:00 [INF] [T2] CS ENABLE!
2021-07-11 17:38:39.901 -03:00 [INF] [IM] Scene & ImGui setup OK!
2021-07-11 17:38:39.944 -03:00 [INF] [T3] START!
2021-07-11 17:38:39.945 -03:00 [INF] [T3] PREPO OK!
2021-07-11 17:38:39.953 -03:00 [INF] [T3] PRC OK!
2021-07-11 17:38:39.975 -03:00 [INF] Loading plugin at C:\Users\ikami\AppData\Roaming\XIVLauncher\devPlugins\Penumbra
2021-07-11 17:38:39.975 -03:00 [INF] Loading assembly at Penumbra.dll
2021-07-11 17:38:39.976 -03:00 [INF] Loading types for Penumbra, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
2021-07-11 17:38:40.903 -03:00 [INF] Loaded plugin: Penumbra
2021-07-11 17:38:40.903 -03:00 [INF] [T3] PM OK!
2021-07-11 17:38:40.937 -03:00 [INF] [DUI] Windows added
2021-07-11 17:38:40.937 -03:00 [INF] [T3] DUI OK!
2021-07-11 17:38:40.947 -03:00 [INF] Dalamud is ready.
```

**Comment by goaaats** [comment]
No clue what's going on here, must be an EasyHook issue - funny though re #457.

Will need to investigate, gonna keep this open.
