### ISSUE TITLE
Error while running integrity check

### ISSUE THREAD

**Issue by The-Snades** [goatcorp/FFXIVQuickLauncher#486]
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Incorrect function.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 98
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 232
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 234
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Incorrect function.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 98
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 232
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 234
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.IO.IOException: Incorrect function.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 98
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.CheckDirectory(DirectoryInfo directory, SHA1Managed sha1, String rootDirectory, Dictionary`2& results, IProgress`1 progress) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 127
   at XIVLauncher.Game.IntegrityCheck.<RunIntegrityCheckAsync>d__6.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.IntegrityCheck.<CompareIntegrityAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\IntegrityCheck.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass17_0.<<RunIntegrityCheck_OnClick>b__1>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 232<---
<---

Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: G:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

**Comment by reiichi001** [comment]
Hello!

Is this still happening for you on the current version of XIVLauncher? (6.0.6 as of writing)

**Comment by reiichi001** [comment]
Closing issue - no response
