### ISSUE TITLE
System.Net.Sockets.SocketException

### ISSUE THREAD

**Issue by jsquared71** [goatcorp/FFXIVQuickLauncher#499]
System.Net.Sockets.SocketException (0x80004005): An attempt was made to access a socket in a way forbidden by its access permissions
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at HttpServer.HttpListenerBase.Start(Int32 backlog)
   at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
   at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
   at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchInstaller.cs:line 71
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 129
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 660
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by reiichi001** [comment]
This is either your Antivirus and/or Firewall.

https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone

**Comment by jsquared71** [comment]
After putting the exceptions in my anti-virus and restarting, XIVLauncher works! Thank you for the help.
