### ISSUE TITLE
Crashed while AFK at Ul'Dah Aetheryte

### ISSUE THREAD

**Issue by Minalia** [goatcorp/FFXIVQuickLauncher#501]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at XIVLauncher.Util.GetDiskFreeSpace(String path) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Util.cs:line 169
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 114
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 339
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: G:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by Minalia** [comment]
Windows decided to stop recognizing the drive while I was playing...
