### ISSUE TITLE
System.Exception: ariaProcess has exited.

### ISSUE THREAD

**Issue by theapathyimp** [goatcorp/FFXIVQuickLauncher#507]
System.Exception: ariaProcess has exited.
   at XIVLauncher.Game.Patch.Acquisition.Aria.AriaHttpPatchAcquisition.<InitializeAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaHttpPatchAcquisition.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<InitializeAcquisition>d__31.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 160
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 140
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 660
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
This should not happen any longer.
