### ISSUE TITLE
I am having this launching problem and I have no idea how to fix it. I am completly new

### ISSUE THREAD

**Issue by Thornagar** [goatcorp/FFXIVQuickLauncher#517]
System.IO.FileNotFoundException: Could not load file or assembly 'AdysTech.CredentialManager, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
File name: 'AdysTech.CredentialManager, Version=1.8.0.0, Culture=neutral, PublicKeyToken=null'
   at XIVLauncher.Accounts.XivAccount.set_Password(String value)
   at XIVLauncher.Windows.MainWindow.PrepareLogin(Boolean autoLogin, Boolean startGame) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 442
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 356

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\steam libary\steamapps\common\FINAL FANTASY XIV Online

I get this message when I try to launch.

**Comment by reiichi001** [comment]
If XIVLauncher is missing a file, the most common culprit is your antivirus. You should [whitelist per the FAQ](https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone) and then do a [full uninstall](https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-uninstall-xiv-launcher) and reinstall of XIVLauncher. It might also help to [reset any saved credentials](https://goatcorp.github.io/faq/xl_troubleshooting#q-xiv-isnt-saving-my-new-password--how-do-i-clear-my-saved-password).

**Comment by reiichi001** [comment]
Closing issue - no response
