### ISSUE TITLE
Error while attempting to download a patch

### ISSUE THREAD

**Issue by icswcshadow** [goatcorp/FFXIVQuickLauncher#523]
I am getting an error every time XIVLauncher is asking me to download a patch.

> System.UnauthorizedAccessException: Access to the path 'C:\Users\Shadow\AppData\Local\Microsoft\Windows\Temporary Internet Files' is denied.
>    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
>    at System.IO.FileSystemEnumerableIterator`1.CommonInit()
>    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
>    at System.IO.DirectoryInfo.InternalGetFiles(String searchPattern, SearchOption searchOption)
>    at HttpServer.HttpServer.Init()
>    at HttpServer.HttpServer.Start(IPAddress address, Int32 port)
>    at ZetaIpc.Runtime.Server.IpcServer.Start(Int32 port)
>    at XIVLauncher.Game.Patch.PatchInstaller.StartIfNeeded() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchInstaller.cs:line 71
>    at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 129
>    at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 657
> Version: 6.0.6.0
> Git Hash: 6.0.6-0-gac7dd80
> Context: Login
> OS: Microsoft Windows NT 6.2.9200.0
> 64bit? True
> DX11? True
> Addons Enabled? True
> Auto Login Enabled? True
> Language: English
> LauncherLanguage: English
> Game path: D:\Steam\steamapps\common\FINAL FANTASY XIV Online

When pressing OK it shows me this and is not downloading at all:
![ss+(2021-08-26+at+03 28 12)](https://user-images.githubusercontent.com/38329334/130971182-b899c715-c5d1-44c8-bd2d-3cf68bdcab12.png)

**Comment by icswcshadow** [comment]
Just figured out this is actually a game patch, not launcher, so by downloading it through the normal launcher and then using XIVLauncher, everything works fine.
