### ISSUE TITLE
XIVLauncher Error

### ISSUE THREAD

**Issue by bubblesayoyo** [goatcorp/FFXIVQuickLauncher#525]
System.AggregateException: One or more errors occurred. ---> System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 407
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 125
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 586
---> (Inner Exception #0) System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 407
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
When the `Could not validate game version` error comes up, that typically means your game client installation has become corrupted. Did you happen to get a crash while patching/updating the game? 

And can we have you try to run an integrity report from XIVLauncher -> Settings -> Game

**Comment by reiichi001** [comment]
No response. Closing issue
