### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FinalFantasy548** [goatcorp/FFXIVQuickLauncher#528]
I keep getting the below error. Able to log in just fine with the normal launcher.

System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote name could not be resolved: 'patch-gamever.ffxiv.com'
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 403
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 125
   at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 586
---> (Inner Exception #0) System.Net.WebException: The remote name could not be resolved: 'patch-gamever.ffxiv.com'
   at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
   at System.Net.WebClient.UploadString(Uri address, String method, String data)
   at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 403
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Do you happen to use a VPN and/or Proxy service?

XIVLauncher should be using the same standard network connections as Windows and other programs, but the error above is a DNS issue. (XIVLauncher can't resolve the patch server URL to the IP address it's actually hosted on, which results in not being able to connect to it)

**Comment by FinalFantasy548** [comment]
My VPN (NordVPN) was inactive when initially launching. But after turning on the VPN, it launched the game just fine.
