### ISSUE TITLE
Error When Opening Launcher

### ISSUE THREAD

**Issue by harryz619** [goatcorp/FFXIVQuickLauncher#530]
System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Dalamud\DalamudLauncher.cs:line 133
   at XIVLauncher.Addon.AddonManager.RunAddons(Process gameProcess, ILauncherSettingsV3 setting, List`1 addonEntries) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Addon\AddonManager.cs:line 42
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.MainWindow.<StartGameAndAddon>d__20.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 786
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

**Comment by reiichi001** [comment]
Can you please verify that your FFXIV exe files are not set to run as the Administrator user? ...we see this most often with Steam installations.

You'll want to check the properties for:
- boot\ffxivboot.exe
- boot\ffxivboot64.exe
- boot\ffxivlauncher.exe
- boot\ffxivlauncher64.exe
- game\ffxiv.exe
- game\ffixv_dx11.exe

**Comment by reiichi001** [comment]
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue and we can help troubleshoot it.
