### ISSUE TITLE
Invalid window handle when starting the game.

### ISSUE THREAD

**Issue by CaptKelerick** [goatcorp/FFXIVQuickLauncher#534]
Hello,

First error was like the AV exception list, which it was solved. Now this is happening everytime i tried auto log-in or log in normally.

System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
   at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at XIVLauncher.App.Main()
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

**Comment by reiichi001** [comment]
Hello!

Is this still happening? Would you be able to to provide some logs (here or in our Discord server ideally).

Please provide the output.log and dalamud.log files from `%appdata%\xivlauncher`

**Comment by CaptKelerick** [comment]
> Hello!
> 
> Is this still happening? Would you be able to to provide some logs (here or in our Discord server ideally).
> 
> Please provide the output.log and dalamud.log files from `%appdata%\xivlauncher`

Posted in discord.
