### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by XArashiX** [goatcorp/FFXIVQuickLauncher#536]
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 270
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by jtuc** [comment]
This looks to be the same error I'm getting; same message, same line.
For me, the game still launches, but plugins are not injected. It only seems to happen around 50% of the time for me - possibly a race condition?

```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 270
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: E:\games\steam\steamapps\common\FINAL FANTASY XIV Online
```

**Comment by reiichi001** [comment]
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue or contact us in discord and we can help troubleshoot it.
