### ISSUE TITLE
XIV Launcher Error

### ISSUE THREAD

**Issue by SolyWyn** [goatcorp/FFXIVQuickLauncher#542]
hey I reinstalled the launcher today and when I go to play, it wants to update the new patch, but it keeps getting hung up on this:

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\patch\game\4e9a232b' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at XIVLauncher.Game.Patch.PatchManager.GetPatchFile(PatchListEntry patch) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 474
   at XIVLauncher.Game.Patch.PatchManager.<DownloadPatchAsync>d__33.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<>c__DisplayClass35_0.<<RunDownloadQueue>b__2>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 335
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn\patch\game\4e9a232b' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at XIVLauncher.Game.Patch.PatchManager.GetPatchFile(PatchListEntry patch) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 474
   at XIVLauncher.Game.Patch.PatchManager.<DownloadPatchAsync>d__33.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 182
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<>c__DisplayClass35_0.<<RunDownloadQueue>b__2>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 335<---

Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Can anyone help me figure out what is going wrong here?  Thanks

**Comment by reiichi001** [comment]
This is a windows permissions issue. XIVPatcher was unable to write to your FFXIV gamepath. 

If you already have a working install of ffxiv, then your gamepath has not been set correctly

**Comment by SolyWyn** [comment]
> 
> 
> This is a windows permissions issue. XIVPatcher was unable to write to your FFXIV gamepath.
> 
> If you already have a working install of ffxiv, then your gamepath has not been set correctly

Thank you for your quick reply.  Can you explain to me how to fix this though?  do I set the patch to install in the "game" folder in my Final Fantasy XIV A Realm Reborn folder?  or boot?  Thanks
