### ISSUE TITLE
Random error when opening the game

### ISSUE THREAD

**Issue by Joahkiin** [goatcorp/FFXIVQuickLauncher#548]
Hello! This error message shows up as soon as the game opens. It doesn't happen every time and it causes no in-game issues. It's not a big deal for me, it's just a little inconvenience.

The message:

> System.ComponentModel.Win32Exception (0x80004005): Invalid window handle
>    at MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
>    at System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at XIVLauncher.App.Main()
> Version: 6.0.6.0
> Git Hash: 6.0.6-0-gac7dd80
> Context: Unhandled
> OS: Microsoft Windows NT 6.2.9200.0
> 64bit? True
> DX11? True
> Addons Enabled? True
> Auto Login Enabled? False
> Language: English
> LauncherLanguage: English
> Game path: D:\Games\Steam Library\steamapps\common\FINAL FANTASY XIV Online

**Comment by Joahkiin** [comment]
I've noticed that [someone has the same error as I have.](https://github.com/goatcorp/FFXIVQuickLauncher/issues/534) Let me know if I should move my issue there instead.

So I decided to do a backup and removed everything from `%AppData%\XIVLauncher` and then reinstalled the launcher. Unfortunately, the error persisted. 😔

Here are my output.log and dalamud.log files:
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/7313794/output.log)
[dalamud.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/7313796/dalamud.log)
