### ISSUE TITLE
Just got this as I logged in after an update

### ISSUE THREAD

**Issue by DrDaph** [goatcorp/FFXIVQuickLauncher#556]
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.ComponentModel.Win32Exception: The operation completed successfully
   at MS.Win32.SafeNativeMethods.ReleaseCapture()
   at System.Windows.Window.ShowDialog()
   at XIVLauncher.Windows.CustomMessageBox.<>c__DisplayClass5_0.<Show>b__0() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\CustomMessageBox.xaml.cs:line 96
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at XIVLauncher.Windows.CustomMessageBox.Show(String text, String caption, MessageBoxButton buttons, MessageBoxImage image, Boolean showHelpLinks, Boolean showReportLinks) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\CustomMessageBox.xaml.cs:line 101
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 63
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.ComponentModel.Win32Exception (0x80004005): The operation completed successfully
   at MS.Win32.SafeNativeMethods.ReleaseCapture()
   at System.Windows.Window.ShowDialog()
   at XIVLauncher.Windows.CustomMessageBox.<>c__DisplayClass5_0.<Show>b__0() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\CustomMessageBox.xaml.cs:line 96
   at System.Windows.Threading.DispatcherOperation.InvokeDelegateCore()
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Windows.Threading.DispatcherOperation.Wait(TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.InvokeImpl(DispatcherOperation operation, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at XIVLauncher.Windows.CustomMessageBox.Show(String text, String caption, MessageBoxButton buttons, MessageBoxImage image, Boolean showHelpLinks, Boolean showReportLinks) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\CustomMessageBox.xaml.cs:line 101
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 63<---

Version: 6.0.9.0
Git Hash: 6.0.9-0-g5113f9e
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Hello! Is this still happening? 

If so, can we see your launcher log please?

It's the `output.log` file, which can be found in `%appdata%\xivlauncher`

**Comment by DrDaph** [comment]
It stopped after the next update, thanks!

Daph
