### ISSUE TITLE
Multiple Instances of XIV Causes Error with Log File Access

### ISSUE THREAD

**Issue by rathus** [goatcorp/FFXIVQuickLauncher#557]
With the new update, starting up a second copy of XIV for my musicians causes dalamud to throw an error about the process not being able to access dalamud.log.

This appears to be a recent change as there was no problem with this on the previous version I was using a few days ago.

```
---------------------------
XIVLauncher Error
---------------------------
Log cull threw an exception: The process cannot access the file 'C:\Users\Chris\AppData\Roaming\XIVLauncher\dalamud.log' because it is being used by another process.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)

   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)

   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)

   at Dalamud.EntryPoint.CullLogFile(String logPath, String oldPath, Int32 cullingFileSize) in C:\goatsoft\companysecrets\dalamud\EntryPoint.cs:line 166
---------------------------
OK   
---------------------------
```

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 6.0.9.0
  Launching as admin?: no
  Using Steam?: no

**Comment by reiichi001** [comment]
Hello! This is actually an issue for Dalamud.

Please submit it over there: https://github.com/goatcorp/Dalamud/issues
