### ISSUE TITLE
Plugins fail to install on linux within the lutris flatpak

### ISSUE THREAD

**Issue by juligreen** [goatcorp/FFXIVQuickLauncher#571]
**Describe the bug here:**
Plugin installation fails while using the [Lutris Flatpak](https://github.com/flathub/net.lutris.Lutris/) with the message "Failed to install plugin <plugin name>. Please restart your game and try again. ..." as can also be seen in the screenshot.

I attached the log that occurs when the plugin install fails.

I assume the issue is either a missing library in the flatpak or a missing wine dependency.

**Screenshots**

![image](https://user-images.githubusercontent.com/25890405/139117257-4b35fb65-8ade-43f8-9b44-21009ff20576.png)

**Logs**
```
2021-10-27 19:32:04.689 +02:00 [ERR] [PLUGINW] Plugin installer threw an unexpected error
System.Net.Http.HttpRequestException: Unknown error (0x2745) (us-central1-xl-functions.cloudfunctions.net:443)
 ---> System.Net.Sockets.SocketException (10053): Unknown error (0x2745)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Dalamud.Plugin.Internal.PluginManager.InstallPluginAsync(RemotePluginManifest repoManifest, Boolean useTesting, PluginLoadReason reason) in C:\goatsoft\companysecrets\dalamud\Plugin\Internal\PluginManager.cs:line 413
2021-10-27 19:32:04.691 +02:00 [INF] LASTEXCEPTION:eyJXaGVuIjoiMjAyMS0xMC0yN1QxOTozMjowNC42OTA2MTk3KzAyOjAwIiwiSW5mbyI6IlN5c3RlbS5OZXQuSHR0cC5IdHRwUmVxdWVzdEV4Y2VwdGlvbjogVW5rbm93biBlcnJvciAoMHgyNzQ1KSAodXMtY2VudHJhbDEteGwtZnVuY3Rpb25zLmNsb3VkZnVuY3Rpb25zLm5ldDo0NDMpXHJcbiAtLS0+IFN5c3RlbS5OZXQuU29ja2V0cy5Tb2NrZXRFeGNlcHRpb24gKDEwMDUzKTogVW5rbm93biBlcnJvciAoMHgyNzQ1KVxyXG4gICBhdCBTeXN0ZW0uTmV0LlNvY2tldHMuU29ja2V0LkF3YWl0YWJsZVNvY2tldEFzeW5jRXZlbnRBcmdzLlRocm93RXhjZXB0aW9uKFNvY2tldEVycm9yIGVycm9yLCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5Tb2NrZXRzLlNvY2tldC5Bd2FpdGFibGVTb2NrZXRBc3luY0V2ZW50QXJncy5TeXN0ZW0uVGhyZWFkaW5nLlRhc2tzLlNvdXJjZXMuSVZhbHVlVGFza1NvdXJjZS5HZXRSZXN1bHQoSW50MTYgdG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuU29ja2V0cy5Tb2NrZXQuPENvbm5lY3RBc3luYz5nX19XYWl0Rm9yQ29ubmVjdFdpdGhDYW5jZWxsYXRpb258MjgzXzAoQXdhaXRhYmxlU29ja2V0QXN5bmNFdmVudEFyZ3Mgc2FlYSwgVmFsdWVUYXNrIGNvbm5lY3RUYXNrLCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkh0dHBDb25uZWN0aW9uUG9vbC5EZWZhdWx0Q29ubmVjdEFzeW5jKFNvY2tldHNIdHRwQ29ubmVjdGlvbkNvbnRleHQgY29udGV4dCwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5Db25uZWN0SGVscGVyLkNvbm5lY3RBc3luYyhGdW5jYDMgY2FsbGJhY2ssIERuc0VuZFBvaW50IGVuZFBvaW50LCBIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdE1lc3NhZ2UsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICAtLS0gRW5kIG9mIGlubmVyIGV4Y2VwdGlvbiBzdGFjayB0cmFjZSAtLS1cclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkNvbm5lY3RIZWxwZXIuQ29ubmVjdEFzeW5jKEZ1bmNgMyBjYWxsYmFjaywgRG5zRW5kUG9pbnQgZW5kUG9pbnQsIEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0TWVzc2FnZSwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ29ubmVjdGlvblBvb2wuQ29ubmVjdEFzeW5jKEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0LCBCb29sZWFuIGFzeW5jLCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkh0dHBDb25uZWN0aW9uUG9vbC5DcmVhdGVIdHRwMTFDb25uZWN0aW9uQXN5bmMoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEJvb2xlYW4gYXN5bmMsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENvbm5lY3Rpb25Qb29sLkdldEh0dHBDb25uZWN0aW9uQXN5bmMoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEJvb2xlYW4gYXN5bmMsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENvbm5lY3Rpb25Qb29sLlNlbmRXaXRoUmV0cnlBc3luYyhIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdCwgQm9vbGVhbiBhc3luYywgQm9vbGVhbiBkb1JlcXVlc3RBdXRoLCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLlJlZGlyZWN0SGFuZGxlci5TZW5kQXN5bmMoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEJvb2xlYW4gYXN5bmMsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENsaWVudC5TZW5kQXN5bmNDb3JlKEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0LCBIdHRwQ29tcGxldGlvbk9wdGlvbiBjb21wbGV0aW9uT3B0aW9uLCBCb29sZWFuIGFzeW5jLCBCb29sZWFuIGVtaXRUZWxlbWV0cnlTdGFydFN0b3AsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBEYWxhbXVkLlBsdWdpbi5JbnRlcm5hbC5QbHVnaW5NYW5hZ2VyLkluc3RhbGxQbHVnaW5Bc3luYyhSZW1vdGVQbHVnaW5NYW5pZmVzdCByZXBvTWFuaWZlc3QsIEJvb2xlYW4gdXNlVGVzdGluZywgUGx1Z2luTG9hZFJlYXNvbiByZWFzb24pIGluIEM6XFxnb2F0c29mdFxcY29tcGFueXNlY3JldHNcXGRhbGFtdWRcXFBsdWdpblxcSW50ZXJuYWxcXFBsdWdpbk1hbmFnZXIuY3M6bGluZSA0MTMiLCJDb250ZXh0IjoiW1BMVUdJTlddIFBsdWdpbiBpbnN0YWxsZXIgdGhyZXcgYW4gdW5leHBlY3RlZCBlcnJvclxuU3lzdGVtLk5ldC5IdHRwLkh0dHBSZXF1ZXN0RXhjZXB0aW9uOiBVbmtub3duIGVycm9yICgweDI3NDUpICh1cy1jZW50cmFsMS14bC1mdW5jdGlvbnMuY2xvdWRmdW5jdGlvbnMubmV0OjQ0MylcclxuIC0tLT4gU3lzdGVtLk5ldC5Tb2NrZXRzLlNvY2tldEV4Y2VwdGlvbiAoMTAwNTMpOiBVbmtub3duIGVycm9yICgweDI3NDUpXHJcbiAgIGF0IFN5c3RlbS5OZXQuU29ja2V0cy5Tb2NrZXQuQXdhaXRhYmxlU29ja2V0QXN5bmNFdmVudEFyZ3MuVGhyb3dFeGNlcHRpb24oU29ja2V0RXJyb3IgZXJyb3IsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0LlNvY2tldHMuU29ja2V0LkF3YWl0YWJsZVNvY2tldEFzeW5jRXZlbnRBcmdzLlN5c3RlbS5UaHJlYWRpbmcuVGFza3MuU291cmNlcy5JVmFsdWVUYXNrU291cmNlLkdldFJlc3VsdChJbnQxNiB0b2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5Tb2NrZXRzLlNvY2tldC48Q29ubmVjdEFzeW5jPmdfX1dhaXRGb3JDb25uZWN0V2l0aENhbmNlbGxhdGlvbnwyODNfMChBd2FpdGFibGVTb2NrZXRBc3luY0V2ZW50QXJncyBzYWVhLCBWYWx1ZVRhc2sgY29ubmVjdFRhc2ssIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENvbm5lY3Rpb25Qb29sLkRlZmF1bHRDb25uZWN0QXN5bmMoU29ja2V0c0h0dHBDb25uZWN0aW9uQ29udGV4dCBjb250ZXh0LCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkNvbm5lY3RIZWxwZXIuQ29ubmVjdEFzeW5jKEZ1bmNgMyBjYWxsYmFjaywgRG5zRW5kUG9pbnQgZW5kUG9pbnQsIEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0TWVzc2FnZSwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIC0tLSBFbmQgb2YgaW5uZXIgZXhjZXB0aW9uIHN0YWNrIHRyYWNlIC0tLVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuQ29ubmVjdEhlbHBlci5Db25uZWN0QXN5bmMoRnVuY2AzIGNhbGxiYWNrLCBEbnNFbmRQb2ludCBlbmRQb2ludCwgSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3RNZXNzYWdlLCBDYW5jZWxsYXRpb25Ub2tlbiBjYW5jZWxsYXRpb25Ub2tlbilcclxuICAgYXQgU3lzdGVtLk5ldC5IdHRwLkh0dHBDb25uZWN0aW9uUG9vbC5Db25uZWN0QXN5bmMoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEJvb2xlYW4gYXN5bmMsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuSHR0cENvbm5lY3Rpb25Qb29sLkNyZWF0ZUh0dHAxMUNvbm5lY3Rpb25Bc3luYyhIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdCwgQm9vbGVhbiBhc3luYywgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ29ubmVjdGlvblBvb2wuR2V0SHR0cENvbm5lY3Rpb25Bc3luYyhIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdCwgQm9vbGVhbiBhc3luYywgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ29ubmVjdGlvblBvb2wuU2VuZFdpdGhSZXRyeUFzeW5jKEh0dHBSZXF1ZXN0TWVzc2FnZSByZXF1ZXN0LCBCb29sZWFuIGFzeW5jLCBCb29sZWFuIGRvUmVxdWVzdEF1dGgsIENhbmNlbGxhdGlvblRva2VuIGNhbmNlbGxhdGlvblRva2VuKVxyXG4gICBhdCBTeXN0ZW0uTmV0Lkh0dHAuUmVkaXJlY3RIYW5kbGVyLlNlbmRBc3luYyhIdHRwUmVxdWVzdE1lc3NhZ2UgcmVxdWVzdCwgQm9vbGVhbiBhc3luYywgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IFN5c3RlbS5OZXQuSHR0cC5IdHRwQ2xpZW50LlNlbmRBc3luY0NvcmUoSHR0cFJlcXVlc3RNZXNzYWdlIHJlcXVlc3QsIEh0dHBDb21wbGV0aW9uT3B0aW9uIGNvbXBsZXRpb25PcHRpb24sIEJvb2xlYW4gYXN5bmMsIEJvb2xlYW4gZW1pdFRlbGVtZXRyeVN0YXJ0U3RvcCwgQ2FuY2VsbGF0aW9uVG9rZW4gY2FuY2VsbGF0aW9uVG9rZW4pXHJcbiAgIGF0IERhbGFtdWQuUGx1Z2luLkludGVybmFsLlBsdWdpbk1hbmFnZXIuSW5zdGFsbFBsdWdpbkFzeW5jKFJlbW90ZVBsdWdpbk1hbmlmZXN0IHJlcG9NYW5pZmVzdCwgQm9vbGVhbiB1c2VUZXN0aW5nLCBQbHVnaW5Mb2FkUmVhc29uIHJlYXNvbikgaW4gQzpcXGdvYXRzb2Z0XFxjb21wYW55c2VjcmV0c1xcZGFsYW11ZFxcUGx1Z2luXFxJbnRlcm5hbFxcUGx1Z2luTWFuYWdlci5jczpsaW5lIDQxMyJ9

```

**Other information (*please* complete the following information):**
  Operating System: Arch Linux, but using the [Lutris Flatpak](https://github.com/flathub/net.lutris.Lutris/)
  XIVLauncher version:  6.0.9
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled: none

**Comment by reiichi001** [comment]
Hello!

We'd recommend using a native lutris installation as we don't have the means to test specific versions of Lutris, whether they're compiled from git, a snap package, or a flatpak. Based o the error,  you weren't able  to connect to the Google server we use to host plugin downloads. This could have been a regional ISP issue.

If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue or contact us in discord and we can help troubleshoot it.
