### ISSUE TITLE
Launcher does not handle 5xx errors appropriately

### ISSUE THREAD

**Issue by breadtk** [goatcorp/FFXIVQuickLauncher#593]
Hello,

I get an error saying XIVLauncher failed to check for updates when I open the program. I looked at [the FAQ entry](https://goatcorp.github.io/faq/xl_troubleshooting#q-i-get-an-error-saying-xivlauncher-failed-to-check-for-updates-when-i-open-the-program) and confirmed that I was **not** being throttled (`resources.core.remaining` was 58).

I checked the `output.log ` file at `%appdata%\xivlauncher` and saw there were 500s not being handled appropriately. Below you will find the relevant log lines.

I'm running the launcher with Wine version `lutris-6.10-7-x86_64`. When I wait a few minutes and try to launch the launcher again it works fine. Again, I'm assuming this isn't a throttle issue since Github should be returning 403s for throttling (see [this Github page](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting) on throttling)

```
...snip...
2021-11-27 13:42:32.534 -08:00 [INF] Trying to set up Loc for language code en
2021-11-27 13:42:32.635 -08:00 [INF] XIVLauncher started as xivlauncher-6.0.17.0-6.0.17-0-g99c3a9d
2021-11-27 13:42:32.635 -08:00 [INF] Starting update check...
2021-11-27 13:42:41.057 -08:00 [ERR] Update failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 31
2021-11-27 13:43:32.178 -08:00 [INF] Trying to set up Loc for language code en
2021-11-27 13:43:32.254 -08:00 [INF] XIVLauncher started as xivlauncher-6.0.17.0-6.0.17-0-g99c3a9d
2021-11-27 13:43:32.254 -08:00 [INF] Starting update check...
2021-11-27 13:43:43.257 -08:00 [ERR] Update failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 500 (Internal Server Error).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 31
2021-11-27 13:45:37.662 -08:00 [INF] Trying to set up Loc for language code en
2021-11-27 13:45:37.752 -08:00 [INF] XIVLauncher started as xivlauncher-6.0.17.0-6.0.17-0-g99c3a9d
2021-11-27 13:45:37.752 -08:00 [INF] Starting update check...
2021-11-27 13:45:46.472 -08:00 [ERR] Update failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 31
2021-11-27 13:47:17.952 -08:00 [INF] Trying to set up Loc for language code en
2021-11-27 13:47:18.028 -08:00 [INF] XIVLauncher started as xivlauncher-6.0.17.0-6.0.17-0-g99c3a9d
2021-11-27 13:47:18.028 -08:00 [INF] Starting update check...
2021-11-27 13:49:38.781 -08:00 [INF] Trying to set up Loc for language code en
2021-11-27 13:49:38.856 -08:00 [INF] XIVLauncher started as xivlauncher-6.0.17.0-6.0.17-0-g99c3a9d
2021-11-27 13:49:38.856 -08:00 [INF] Starting update check...
2021-11-27 13:49:46.709 -08:00 [ERR] Update failed
System.Net.Http.HttpRequestException: Response status code does not indicate success: 502 (Bad Gateway).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Squirrel.UpdateManager.<GitHubUpdateManager>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Updates.<Run>d__1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Updates.cs:line 31
...snip...
```

**Comment by reiichi001** [comment]
Github is having a major outage right now. https://www.githubstatus.com/incidents/r5qrpp2f5fc0

XIVLauncher, Dalamud, and Dalamud Plugins are all affected by it. You don't need to take any actions at this time until GitHub's fully operational again. 

If you continue to receive issues after their incident is resolved, please open a new issue here.

**Comment by reiichi001** [comment]
Reopened this issue because we can use it as the basis for related issues to the outage.

This could be handled more gracefully. 

Right now, our policy is to stop everything if XIVLauncher fails, as it often leads to more difficult to troubleshoot issues if we let a user launch anyways.

We could improve some of the error handling around GitHub experiencing issues like updating the wording on the error message, providing a link to the github ratelimit / status pages, etc.

**Comment by Deckerz** [comment]
Really I think if it fails it should prompt something like "XIVLauncher failed to check for updates, would you like the launch the game with dalamud/plugins disabled? Yes/No".

As some people just use XIVLauncher to load FFXIV since the main launcher is so bad and breaks randomly.

**Comment by goaaats** [comment]
We should definitely handle GitHub 500s different to other update failures.
