### ISSUE TITLE
Boot check dies

### ISSUE THREAD

**Issue by ascclemens** [goatcorp/FFXIVQuickLauncher#600]
I used official launcher to get the boot patch, but XL died trying to get it.

```
System.Exception: ariaProcess has exited.
   at XIVLauncher.Game.Patch.Acquisition.Aria.AriaHttpPatchAcquisition.<InitializeAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaHttpPatchAcquisition.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<InitializeAcquisition>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 146
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<HandleBootCheck>d__30.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 580
Version: 6.0.18.0
Git Hash: 6.0.18-0-g0b03476
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by reiichi001** [comment]
It's prolly SE's servers being bad. Couldn't reproduce consistently. Their download servers are probably already dying
