### ISSUE TITLE
aria fails to bind to port 65349 and crashes

### ISSUE THREAD

**Issue by hach-que** [goatcorp/FFXIVQuickLauncher#603]
When XIVLauncher tries to update the game, it has this exception:

```
System.Exception: ariaProcess has exited.
   at XIVLauncher.Game.Patch.Acquisition.Aria.AriaHttpPatchAcquisition.<InitializeAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaHttpPatchAcquisition.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<InitializeAcquisition>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 146
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<InstallGamePatch>d__22.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 340
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 236
Version: 6.1.0.0
Git Hash: 6.1.0-0-g44a7a29
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

In `output.log`, there is:

```
2021-12-03 23:52:30.907 +11:00 [INF] Trying to set up Loc for language code en
2021-12-03 23:52:30.997 +11:00 [INF] XIVLauncher started as xivlauncher-6.1.0.0-6.1.0-0-g44a7a29
2021-12-03 23:52:30.997 +11:00 [INF] Starting update check...
2021-12-03 23:52:35.021 +11:00 [INF] MainWindow initialized.
2021-12-03 23:52:35.210 +11:00 [INF] [DUPDATE] Starting...
2021-12-03 23:52:35.260 +11:00 [INF] [DUPDATE] Now starting for Dalamud 6.0.1.3
2021-12-03 23:52:35.265 +11:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.6
2021-12-03 23:52:35.362 +11:00 [INF] [DUPDATE] All set for 2021.08.17.0000.0000
2021-12-03 23:52:36.790 +11:00 [INF] StartLogin() called
2021-12-03 23:52:37.501 +11:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2021-12-03 23:52:37.501 +11:00 [INF] Cache is invalid or disabled, logging in normally.
2021-12-03 23:52:40.752 +11:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:1
2021-12-03 23:52:48.030 +11:00 [ERR] patchSuccess != true
2021-12-03 23:52:52.653 +11:00 [INF] StartLogin() called
2021-12-03 23:52:52.824 +11:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2021-12-03 23:52:52.824 +11:00 [INF] Cache is invalid or disabled, logging in normally.
2021-12-03 23:52:53.925 +11:00 [INF] OAuth login successful - playable:True terms:True region:3 expack:1
2021-12-03 23:52:56.663 +11:00 [INF] [PATCHERIPC] Starting patcher with 'XLPatchera13bae4a-eedb-4c2b-b584-62baf3efda7d'
2021-12-03 23:53:04.795 +11:00 [INF] [PATCHERIPC] IPC(1): {"$type":"XIVLauncher.PatchInstaller.PatcherIpcMessages.PatcherIpcEnvelope, XIVLauncher.PatchInstaller, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null","OpCode":0,"Data":"2021-12-03T23:53:04.6870173+11:00"}
2021-12-03 23:53:04.799 +11:00 [INF] [PATCHERIPC] GOT HELLO
2021-12-03 23:53:05.513 +11:00 [ERR] StartGame failed...
System.Exception: ariaProcess has exited.
   at XIVLauncher.Game.Patch.Acquisition.Aria.AriaHttpPatchAcquisition.<InitializeAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaHttpPatchAcquisition.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<InitializeAcquisition>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 166
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 146
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<InstallGamePatch>d__22.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 340
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 236
```

In `aria.log`, there is:

```
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
2021-12-03 23:56:00.478426 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 65349
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.

2021-12-03 23:56:00.479426 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
```

I have manually added a Windows Firewall exception to allow port 65349, but it didn't seem to make any difference. The local user is an Administrator (I still get the UAC prompt), but the machine is joined to Active Directory.

Also when XIVLauncher gets the `ariaProcess has exited` exception, the progress window just sits there forever and I have to terminate it from Task Manager.

**Comment by hach-que** [comment]
I haven't run into this issue since it was originally reported, so I think it can be safely closed.
