### ISSUE TITLE
ff14 launher crash

### ISSUE THREAD

**Issue by Codex100** [goatcorp/FFXIVQuickLauncher#604]
System.InvalidOperationException: Cannot process request because the process (15108) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 405
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 212
Version: 6.1.0.0
Git Hash: 6.1.0-0-g44a7a29
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\Pelit\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by TheGokki** [comment]
Similar here i guess:

```
System.InvalidOperationException: Cannot process request because the process (19036) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 405
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 212
Version: 6.1.0.0
Git Hash: 6.1.0-0-g44a7a29
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Final Fantasy XIV
```

**Comment by darrenburns** [comment]
Same issue here. Reinstalling the game fixed it for me, but then it started happening again the following day.

```
System.InvalidOperationException: Cannot process request because the process has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 405
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 212
Version: 6.1.0.0
Git Hash: 6.1.0-0-g44a7a29
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: Z:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

```

**Comment by Codex100** [comment]
it was an antivirus-related issue. Somehow the launcher got flagged but I got it working again later.
