### ISSUE TITLE
"Game exited prematurely" error now caught by NativeAclFix

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#611]
```
System.InvalidOperationException: Cannot process request because the process (260) has exited.
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.WaitForInputIdle(Int32 milliseconds)
   at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary2 envVars, Action1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 405
```

Regression from Dalamud OEP rewrite

**Comment by nitinkumar-c** [comment]
Try to restart

**Comment by LightspeedLife** [comment]
I'm getting the same error after a restart, in Linux with Lutris and Dalamund turned off.

**Comment by goaaats** [comment]
This specific issue should be resolved now.
