### ISSUE TITLE
Launcher error

### ISSUE THREAD

**Issue by crash1900** [goatcorp/FFXIVQuickLauncher#641]
System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.<RegisterSession>d__13.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Launcher.<Login>d__8.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 171
Version: 6.1.3.0
Git Hash: 6.1.3-0-gbd8da51
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by goaaats** [comment]
Was an issue with SE servers, should be good now.
