### ISSUE TITLE
System.Exception: Could not validate game version.

### ISSUE THREAD

**Issue by devyeen** [goatcorp/FFXIVQuickLauncher#644]
All I did was launch the program, though it was while my computer was just barely logged in, and perhaps Steam wasn't running yet, which is what my service account uses.

System.Exception: Could not validate game version.
   at XIVLauncher.Game.Launcher.<RegisterSession>d__13.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 301
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Launcher.<Login>d__8.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 111
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__21.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 171
Version: 6.1.3.0
Git Hash: 6.1.3-0-gbd8da51
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by ackwell** [comment]
Duplicate of #643. Issue is on SE's side, please check existing issues before opening another.

**Comment by devyeen** [comment]
Acknowledged.
