### ISSUE TITLE
Error upon login, just updated

### ISSUE THREAD

**Issue by nkmarras** [goatcorp/FFXIVQuickLauncher#650]
Just updating for Endwalker, DL the patch and got this error on login.

System.NullReferenceException: Object reference not set to an instance of an object.
  
 at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 375
  
 at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 196
  
 at XIVLauncher.Windows.ViewModel.MainWindowViewModel.StartGameAndAddon(LoginResult loginResult, Boolean gateStatus, Boolean isSteam) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 475
   
at System.Threading.Tasks.Task.Execute()
Version: 6.1.5.0
Git Hash: 6.1.5-0-g5094842
Context: StartGameAndAddon
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by goaaats** [comment]
I'm tracking this in #653
