### ISSUE TITLE
Issues with launching

### ISSUE THREAD

**Issue by saiz** [goatcorp/FFXIVQuickLauncher#660]
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'SavedStylesVersioned.$values[0].col', line 534, position 9.
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseProperty()
   at Newtonsoft.Json.JsonReader.Skip()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(JsonObjectContract contract, JsonProperty member, JsonReader reader, String memberName, Object o)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at XIVLauncher.Settings.DalamudSettings.GetSettings() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Settings\DalamudSettings.cs:line 19
   at XIVLauncher.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\NativeAclFix.cs:line 375
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, Action`1 beforeResume) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 196
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.StartGameAndAddon(LoginResult loginResult, Boolean gateStatus, Boolean isSteam) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 475
   at System.Threading.Tasks.Task.Execute()
Version: 6.1.8.0
Git Hash: 6.1.8-0-g6abeafc
Context: StartGameAndAddon
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by saiz** [comment]
I deleted %AppData%\XIVLauncher\Addon after this and restarted my pc but the launcher still is giving me issues

**Comment by reiichi001** [comment]
> I deleted %AppData%\XIVLauncher\Addon after this and restarted my pc but the launcher still is giving me issues

Did you check/adjust your antivirus exceptions? What antivirus program do you use?

The error above looks like corrupted settings. It may help to remove `%appdata%\xivlauncher\dalamudConfig.json`

**Comment by saiz** [comment]
I use Windows defender. Re-read the wiki and applied the steps. Thank you on the dalamudConfig.json tip. fixed the launcher
