### ISSUE TITLE
Game crashes immediately after launching.

### ISSUE THREAD

**Issue by rynejinn** [goatcorp/FFXIVQuickLauncher#661]
2021-12-20 12:12:59.536 -05:00 [INF] Trying to set up Loc for language code en
2021-12-20 12:12:59.748 -05:00 [INF] XIVLauncher started as xivlauncher-6.1.8.0-6.1.8-0-g6abeafc
2021-12-20 12:12:59.748 -05:00 [INF] Starting update check...
2021-12-20 12:13:06.555 -05:00 [ERR] Could not parse installed in-game plugins.
Newtonsoft.Json.JsonReaderException: Error reading JObject from JsonReader. Path '', line 0, position 0.
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   at XIVLauncher.Windows.SettingsControl.ReloadPluginList() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 436
2021-12-20 12:13:07.572 -05:00 [INF] MainWindow initialized.
2021-12-20 12:13:08.554 -05:00 [INF] [DUPDATE] Starting...
2021-12-20 12:13:08.652 -05:00 [INF] [DUPDATE] Now starting for Dalamud 6.2.0.7
2021-12-20 12:13:08.652 -05:00 [INF] [DUPDATE] Not found, redownloading
2021-12-20 12:13:10.140 -05:00 [INF] [DUPDATE] Download OK!
2021-12-20 12:13:10.140 -05:00 [INF] [DUPDATE] Now starting for .NET Runtime 5.0.6
2021-12-20 12:13:10.293 -05:00 [INF] [DUPDATE] All set for 2021.11.28.0000.0000
2021-12-20 12:13:11.421 -05:00 [INF] StartLogin() called
2021-12-20 12:13:12.125 -05:00 [INF] XivGame::Login(steamServiceAccount:False, cache:False)
2021-12-20 12:13:12.125 -05:00 [INF] Cache is invalid or disabled, logging in normally.
2021-12-20 12:13:13.307 -05:00 [INF] OAuth login successful - playable:True terms:True region:2 expack:4
2021-12-20 12:13:14.549 -05:00 [INF] XivGame::LaunchGame(steamIntegration:False, steamServiceAccount:False, args:)
2021-12-20 12:13:14.552 -05:00 [INF] ArgumentBuilder::DeriveKey() rawTickCount:10052234 ticks:10052234 key:10027008
2021-12-20 12:13:14.562 -05:00 [INF] ArgumentBuilder::BuildEncrypted() checksum:"C"
2021-12-20 12:13:14.588 -05:00 [INF] [HOOKS] DalamudLauncher::Run(gp:F:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn, cl:"English", d:{2}
2021-12-20 12:13:14.631 -05:00 [INF] [HOOKS] Started dalamud!
2021-12-20 12:13:23.149 -05:00 [INF] Game has exited.
2021-12-20 12:13:23.150 -05:00 [INF] Stopping addons...

I made sure the folders were whitelisted.
I deleted the Hooks folder.
I made sure my .NET and Visual C++ were up to date.
I updated my video drivers.

I cannot find a fix. Please help.

**Comment by reiichi001** [comment]
What antivirus program do you use?

**Comment by rynejinn** [comment]
> What antivirus program do you use?

Just Windows Defender. I added the launcher folder as an exclusion, then when that didn't work, I disabled virus protection.

**Comment by rynejinn** [comment]
Just reinstalled FFXIV on a new drive and reinstalled xivlauncher, still having the same problem.
