### ISSUE TITLE
Launcher crashes on patching if port is in use

### ISSUE THREAD

**Issue by nathanctech** [goatcorp/FFXIVQuickLauncher#686]
I recently encountered an issue where the port the launcher wanted to use was reserved by Hyper-V so I was unable to finish patching:

```
2022-01-04 12:14:43.171 -05:00 [INF] [PATCHERIPC] GOT HELLO
2022-01-04 12:14:43.913 -05:00 [ERR] StartGame failed...
System.Exception: ariaProcess has exited.
   at XIVLauncher.Game.Patch.Acquisition.Aria.AriaHttpPatchAcquisition.<InitializeAsync>d__4.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaHttpPatchAcquisition.cs:line 71
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.<InitializeAcquisition>d__39.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Patch.PatchManager.Start() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\PatchManager.cs:line 152
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<InstallGamePatch>d__23.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 446
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__22.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 250
```

Relevant entry in aria.log:

```

2022-01-04 12:14:43.565602 [ERROR] [MultiUrlRequestInfo.cc:297] Exception caught
Exception: [DownloadEngineFactory.cc:219] errorCode=1 Failed to setup RPC server.
2022-01-04 12:19:35.356934 [ERROR] [HttpListenCommand.cc:112] IPv4 RPC: failed to bind TCP port 65349
Exception: [SocketCore.cc:312] errorCode=1 Failed to bind a socket, cause: An attempt was made to access a socket in a way forbidden by its access permissions.
```

Issue to verify this was indeed the cause:

```
C:\WINDOWS\system32>netsh interface ipv4 show excludedportrange protocol=tcp

Protocol tcp Port Exclusion Ranges

Start Port    End Port
----------    --------
        80          80
       443         443
      5341        5341
      5357        5357
      5426        5426
     50000       50059     *
     50258       50357
     50458       50557
     50558       50657
     50858       50957
     54235       54235
     54236       54236
     56226       56325
     61428       61527
     61619       61718
     61719       61818
     61977       62076
     65274       65373
```

The port is indeed in the exclusion range. Restarting the Hyper-V service causes it to grab a different set of ports which allowed the launcher to function. Perhaps there could be a check to verify the port isn't in use? I'd imagine this is a pretty rare edge case.

**Comment by goaaats** [comment]
We are indeed checking for open ports: https://github.com/goatcorp/FFXIVQuickLauncher/blob/7995728355038841e974e31dee42e4e97bf7d239/src/XIVLauncher/Util.cs#L220-L251

We pretty much start looking right at the end(65349), since lots of Linux distributions seem to reserve big port ranges as well. Maybe we can tweak that a little.

**Comment by nathanctech** [comment]
Makes me wonder if `GetActiveTcpListeners` doesn't take reserved port ranges into account since they're technically not actively being used, just reserved by Windows. I've had other applications with the same issue in the past which is what made me look for the problem to start with.

**Comment by goaaats** [comment]
Let's see if https://github.com/goatcorp/FFXIVQuickLauncher/commit/5e6bca684a96a201a3b3605baaac96634e175821 does anything to resolve the issues, should be in the next update

**Comment by goaaats** [comment]
Hey, feel free to give this prerelease a spin, might fix it: https://github.com/goatcorp/FFXIVQuickLauncher/releases/tag/6.1.14

**Comment by nathanctech** [comment]
I'll grab it, can't test it for certain until there's another patch. I'll keep you posted.

**Comment by nathanctech** [comment]
Works great.
