### ISSUE TITLE
[BUG] Error crashes XIVLauncher after moving FFXIV to a different drive

### ISSUE THREAD

**Issue by XArashiX** [goatcorp/FFXIVQuickLauncher#726]
This error shows up and crashes the client when logging in.

`System.IO.IOException: A device which does not exist was specified.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at System.IO.File.InternalReadAllBytes(String path, Boolean checkHost)
   at XIVLauncher.Game.Launcher.GetFileHash(String file) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 422
   at XIVLauncher.Game.Launcher.GetBootVersionHash(DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 250
   at XIVLauncher.Game.Launcher.GetVersionReport(DirectoryInfo gamePath, Int32 exLevel, Boolean forceBaseVersion) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 222
   at XIVLauncher.Game.Launcher.<RegisterSession>d__13.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 288
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Game.Launcher.<Login>d__8.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<LoginToGame>d__30.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 233
Version: 6.2.0.0
Git Hash: 6.2.0-0-ge9d67e7
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: F:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
`

**Comment by XArashiX** [comment]
I found the reason.
It was nothing to do with XIVLauncher or FFXIV.. likely anyways.

I recently bought Samsung 980 PRO EVO's M.2 NVMe drives, one without the "pro" and one pro. The pro version has a 8GB pcie4 speed while the non pro runs on pcie3 at 4GB as supported by my hardware.
I moved my game onto the NVMe for the sake of speed, which is the F drive.

Well, when this all happened, I went to dig around my FFXIV folder to see if deleting the actual game and reinstalling it would help.. and I realized some of the folders in my FFXIV folder, only some of them, were not opening and telling me with a windows error saying that it was unavailable;
`"xxx directory" is not accessible, a device which does not exist was specified`
I went to go check the software for the drivers for these drives to see if I could see if it recognized the drive or is throwing any red flags, because it also monitors them.
Any tab on the software said there was a unknown error, so I thought my drive was faulty for a moment.
Just restarted my PC, the drive was recognized completely, and FFXIV finally continued on patching.

But do note.. when I reinstalled XIVLauncher, it said that permissions (admin, ect) were different than what it should be and if I should change it; so of course I hit yes. From there, after I hit login, it gave me the same error.

I would check into how this error can come into play on NVMe drives if that makes any difference. Otherwise, it's a hardware issue, not with XIVLauncher or FFXIV.

**Comment by goaaats** [comment]
Nice to hear that it works, will close this.
