### ISSUE TITLE
[Linux] System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.

### ISSUE THREAD

**Issue by cptn-cosmo** [goatcorp/FFXIVQuickLauncher#733]
Hi, I am trying to install FFXIV once again on my Archlinux PC from lutris:

After going through the config options and entering username & password (I don't get asked for OTP code even though i checked the box for it) I immediately get this error message:

```
System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.Show()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<HandleBootCheck>d__45.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1129

Version: 6.2.2.0
Git Hash: 6.2.2-0-g928d28f
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

Kernel: 5.16.12-arch1-1 
DE: Plasma 5.24.2 
CPU: AMD Ryzen 9 3900XT (24) @ 3.800GHz 
GPU: NVIDIA GeForce RTX 3090 
Memory: 2240MiB / 64291MiB 
Wine: lutris-7.1-x86_64

**Comment by goaaats** [comment]
This should be fixed now
