### ISSUE TITLE
Verifier patch sources key not found

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#740]
```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__69.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 261
```
Non-steam, all expacks installed + on accoun

https://github.com/goatcorp/FFXIVQuickLauncher/blob/73ff3630686e7c0d910af55212c9cbcf293161ca/src/XIVLauncher.Common/Game/Patch/PatchVerifier.cs#L261

**Comment by wolfcomp** [comment]
Further info on what is causing the issue.
```
System.InvalidOperationException: Key "ex0:D2022.01.18.0000.0000.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__70.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 269```

It's interesting that there is a `D` in the patch number as that seems what is causing the issue.

**Comment by wolfcomp** [comment]
Actually looking at it now, I can see the file in the patch folder for caching the downloads I have set up, so it's interesting that it can't find it at all.
