### ISSUE TITLE
Repair problem

### ISSUE THREAD

**Issue by Shirieyn** [goatcorp/FFXIVQuickLauncher#759]
Hello there. I had some issue regarding me getting dc'd everytime. When I did a repair check, this appeared:

System.Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 181
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 229
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 378
---> (Inner Exception #0) System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 181
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 229
   at System.Threading.Tasks.Task.Execute()<---

   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__70.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 243

Version: 6.2.16.0
Git Hash: 6.2.16-0-gd87aeff
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: F:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
Tracking in #783
