### ISSUE TITLE
Integrity check issue

### ISSUE THREAD

**Issue by Spectro** [goatcorp/FFXIVQuickLauncher#768]
System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Window.GetWindow(DependencyObject dependencyObject)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 295
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.DependencyObject.GetValue(DependencyProperty dp)
   at System.Windows.Window.GetWindow(DependencyObject dependencyObject)
   at XIVLauncher.Windows.SettingsControl.<>c__DisplayClass18_0.<RunIntegrityCheck_OnClick>b__2(Task`1 task) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:line 295
   at System.Threading.Tasks.Task.Execute()<---

Version: 6.2.18.0
Git Hash: 6.2.18-0-gecfe220
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
This should be fixed now
