### ISSUE TITLE
Lutis Launcher error when installing game from scratch

### ISSUE THREAD

**Issue by thesnowfury** [goatcorp/FFXIVQuickLauncher#782]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

installed launcher from Lutris, all ok. Launched and fresh Garuda install and error'd when trying to download game files:

An error in XIVLauncher occured: Path not found

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

lutris 7.1

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): Path not found
   at XIVLauncher.Common.Util.GetDiskFreeSpace(DirectoryInfo info) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Util.cs:line 142
   at XIVLauncher.Common.Game.Patch.PatchManager.<PatchAsync>d__36.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 115
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__34.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1124

Version: 6.2.20.0
Git Hash: 6.2.20-0-g1080756
Context: HandlePatchAsync
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by goaaats** [comment]
Please update the launcher and try again
