### ISSUE TITLE
Failed to repair game files

### ISSUE THREAD

**Issue by CherrieP** [goatcorp/FFXIVQuickLauncher#783]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Its been a while since I last launched FFXIV using the quick launcher. Probably had installed a few mods around but after coming back to FFXIV now it crashes upon loading the world. Did integrity check and says files need repair and I ran the repair game files and it threw these errors.

### Platform

Windows

### Relevant log output

```shell
System.Exception: System.AggregateException: One or more errors occurred. ---> System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 174
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 232
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<VerifyFiles>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.WorkerSubprocessBody.<<-ctor>b__6_0>d.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 378
---> (Inner Exception #0) System.IO.IOException: Data error (cyclic redundancy check).

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.ReadCore(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.FileStream.Read(Byte[] array, Int32 offset, Int32 count)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchPartLocator.Verify(Stream stream, Boolean seek) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchPartLocator.cs:line 174
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchInstaller.<>c__DisplayClass22_3.<VerifyFiles>b__6() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchInstaller.cs:line 232
   at System.Threading.Tasks.Task.Execute()<---

   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<WaitForResult>d__17.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 162
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Common.Patching.IndexedZiPatch.IndexedZiPatchIndexRemoteInstaller.<VerifyFiles>d__20.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Patching\IndexedZiPatch\IndexedZiPatchIndexRemoteInstaller.cs:line 202
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__71.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 281

Version: 6.2.21.0
Git Hash: 6.2.21-0-gc98a432
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by Soreepeong** [comment]
This looks like your disk might be faulty. Have you tried checking disk for errors? Right click on the disk with XIV installation, Properties, and in one of the tabs there should be Check for errors or something like that.

**Comment by CherrieP** [comment]
> This looks like your disk might be faulty. Have you tried checking disk for errors? Right click on the disk with XIV installation, Properties, and in one of the tabs there should be Check for errors or something like that.

Using Windows scan revealed nothing, I will try to install in a different drive and see.
![image](https://user-images.githubusercontent.com/66919422/159825843-8a67e317-3f20-4906-accf-5c9ea6e8b17b.png)
