### ISSUE TITLE
Weird launcher crash on FFXIV

### ISSUE THREAD

**Issue by samsterpiece** [goatcorp/FFXIVQuickLauncher#794]
System.ComponentModel.Win32Exception (0x80004005): The system cannot find the path specified
   at XIVLauncher.Common.Util.GetDiskFreeSpace(DirectoryInfo info) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Util.cs:line 142
   at XIVLauncher.Common.Game.Patch.PatchManager.<PatchAsync>d__37.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher.Common\Game\Patch\PatchManager.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryHandlePatchAsync>d__34.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1139

Version: 6.2.22.0
Git Hash: 6.2.22-0-g4d5554b
Context: HandlePatchAsync
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
Use the "bug report" template

**Comment by samsterpiece** [comment]
Where? My apologies, I clicked on bug report on launcher and it redirected me to here.

**Comment by reiichi001** [comment]
> Where? My apologies, I clicked on bug report on launcher and it redirected me to here.

![image](https://user-images.githubusercontent.com/10376708/162087023-4d8c5064-8487-433f-8fa0-f05ee44e672c.png)

When you click on the "new issue" button, it should come up. The template information helps us help you without having to ask a bunch of extra followup questions for every opened issue.

**Comment by goaaats** [comment]
You can click on "issues" and "Create new", then choose "bug report" - sorry, we need to update our links
