### ISSUE TITLE
Unexpected error during after the 6.1 update

### ISSUE THREAD

**Issue by OttoOtteist** [goatcorp/FFXIVQuickLauncher#815]
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by OttoOtteist** [comment]
Update completed successfully, started the game, saw menu, exited the game, launcher reports the error

**Comment by goaaats** [comment]
Known issue, doesn't actually matter/break anything, we'll fix it later today
