### ISSUE TITLE
i was just trying to close the game and this error showed up

### ISSUE THREAD

**Issue by Zxeh** [goatcorp/FFXIVQuickLauncher#816]
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

idk know what this means but ill leave this here

**Comment by Zxeh** [comment]
oh this is already a known issue my b
