### ISSUE TITLE
Unexpected error has occurred

### ISSUE THREAD

**Issue by YehnBeep** [goatcorp/FFXIVQuickLauncher#834]
The launcher said "please report this error", so, here it is:

![image](https://user-images.githubusercontent.com/86855173/162974756-4561e91b-525f-450a-b4ec-75f984b248bd.png)

```
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

(Note: Despite addons being 'enabled', they weren't really since they haven't been updated yet. Also no other third party tools/mods/etc were in use - just a fresh update to 6.1 with only QuickLauncher being used)

**Comment by wolfcomp** [comment]
Duplicate of #815
