### ISSUE TITLE
Error upon shutting down ffxiv

### ISSUE THREAD

**Issue by Hapseleg** [goatcorp/FFXIVQuickLauncher#860]
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602
   
Not sure why it even mentions the D:\ drive as it has nothing to do with ffxiv or ffxivlauncher

**Comment by goaaats** [comment]
Should be fixed now, please restart XIVLauncher and update.
