### ISSUE TITLE
Error to report

### ISSUE THREAD

**Issue by PookieChu** [goatcorp/FFXIVQuickLauncher#872]
This is what the quick launcher told me to report

System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by elizeuW** [comment]
how to restart xiv launcher??

**Comment by goaaats** [comment]
Should be fixed now, please restart XIVLauncher and update.
