### ISSUE TITLE
FFXIV Launcer

### ISSUE THREAD

**Issue by Runandhide56** [goatcorp/FFXIVQuickLauncher#877]
System.InvalidOperationException: Process was not started by this object, so requested information cannot be determined.
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_ExitCode()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by Runandhide56** [comment]
This error appears after closing out of the game

**Comment by Delta87** [comment]
In this log, i see you use an older version. Try to use the updated version 6.2.29.0

**Comment by lmcintyre** [comment]
Should be fixed now, please restart XIVLauncher and update.
