### ISSUE TITLE
Dalamud crash on exiting FF14 while plugin icons are loading

### ISSUE THREAD

**Issue by darknite323** [goatcorp/FFXIVQuickLauncher#955]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

1. Login to FF14
2. Open plugins list
3. Exit FF14 while plugins list is loading icons (Esc > Exit game)
4. Game will then crash with the following error
![unknown](https://user-images.githubusercontent.com/49840343/168224280-1083caf1-d26f-4233-a8f4-d6a58ed704c1.png)
Issue was reproducible

### Platform

Windows

### Relevant log output

```shell
2022-05-13 10:24:35.158 +10:00 [INF] Framework::Destroy!
2022-05-13 10:24:35.848 +10:00 [FTL] Unhandled exception on AppDomain
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Dalamud.Interface.Internal.Windows.PluginImageCache.DownloadTask() in C:\goatsoft\companysecrets\dalamud\Interface\Internal\Windows\PluginImageCache.cs:line 237
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
2022-05-13 10:24:35.849 +10:00 [INF]
```

**Comment by NotNite** [comment]
Closing due to inactivity. If this is still happening, please make an issue on [goatcorp/Dalamud](https://github.com/goatcorp/Dalamud).
