### ISSUE TITLE
[Flatpak] XIVLauncher fails to check for updates at start, dalamud doesn't start

### ISSUE THREAD

**Issue by DukeValentine** [goatcorp/FFXIVQuickLauncher#960]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Even after uninstalling and doing everything from scratch, dalamud doesn't start. There's also another seemingly unrelated error when checking for updates for xivlauncher.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

flatpak 1.0.0.7  a4e4d1e

### Relevant log output

```shell
[16:58:25 ERR] Could not check version
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 5 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at XIVLauncher.Core.UpdateCheck.CheckForUpdate() in C:/goatsoft/xl/XIVLauncher.Core/UpdateCheck.cs:line 16


[17:01:19 INF] OAuth login successful - playable:True terms:True region:2 expack:4
[17:01:20 INF] [HOOKS] DalamudLauncher::HoldForUpdate(gp:$HOME/.xlcore/ffxiv)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/linux-x64/native/libglfw.so.3 (9E3137144F68B9E9793F4C7AD5B1BEA7)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/linux-x64/native/libSDL2-2.0.so (99B95A708381FC66AB2370E45A260527)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/linux-x64/native/libstbi.so (0945355ED59677D06E3E88F48101BB26)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/osx-x64/native/libglfw.3.dylib (1E30FAB2F0C40E82290AD4B0BF14A880)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/osx-x64/native/libSDL2-2.0.dylib (AAC958490586C67395F0A90903AE3747)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/osx-x64/native/libstbi.dylib (0B84B0A6A80178266018081C3CAB68E6)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/unix/lib/netcoreapp3.0/System.Drawing.Common.dll (6DDDA9858492A7D5887112FD98BA4D59)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win/lib/netcoreapp3.0/System.Drawing.Common.dll (86268518C164BDD38217DCD8E74A2543)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/cimgui.dll (72A5F81E7D141AC350DE3D80555CEDC4)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/cimguizmo.dll (F236F6320E07B1F597A52CEBF6CD5634)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/cimnodes.dll (6886385014C6B887357D4C6E0F47314D)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/cimplot.dll (743E4F46CD2414B2A15DADF3FE1E4E71)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/glfw3.dll (0515F263F8ACE4BA1DB8AADA30AF87D5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/minhook.x64d.dll (54C9C9AF7BD808BB7CCEF4F003051F5A)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/SDL2.dll (7A11CBCF3D011D61DFC45EEEA0197839)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/stbi.dll (32E0A20B753C874E73D4E53ACCEC7D6D)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x64/native/stbi.lib (927C214DE576219E1F80DBE7798A0502)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x86/native/glfw3.dll (93B194178AEF1070C2FD183BB820F40D)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/runtimes/win-x86/native/SDL2.dll (FC9437F416F54994C83E9403BD861107)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/CheapLoc.dll (A889B7561AD4B1C74419AE53135F0DDE)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Costura.dll (65700FF9C600CE4D2E89B8638513F725)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Boot.dll (B4C8CD0BD672633AB8FE2A94B90A9129)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.deps.json (9B62CAE78CDF763B296F02E04334AD18)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.dll (C73B2CBD8EF02AE4A213D5C0AEE04FF1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.deps.json (104251936F51AB22DDA5FAD4CB29FD52)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.dll (5D7B701437B202C6A795CAA9676B3D88)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.exe (A241167FC7FDEDF73DAA9794A9B0F752)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.runtimeconfig.dev.json (86F563FDEA16F201FBCEBD6EAE6894F2)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.runtimeconfig.json (5BE8F94351C3768D669294BC4A627DA9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.Injector.xml (6A848FF0D3F0B49721473E03AD2BF2C3)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.runtimeconfig.dev.json (86F563FDEA16F201FBCEBD6EAE6894F2)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.runtimeconfig.json (D77831B18631BADC582E0D924241B0A2)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Dalamud.xml (4CFE1FE41F33D12E169B173C4FFF85D7)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/FASM-LICENSE.TXT (ECEA1D10811221D5F0A3E96F9C38E2C7)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/FASM.DLL (793AB4CD7A8D490412747DCD2BED25EC)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/FASMX64.DLL (818EF3928DB004EF6FC84FC6CDD48A97)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/FFXIVClientStructs.dll (F585F15A88B484FF7EEBECAD577B6827)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Iced.dll (EE697D219B58B91FE6CA6046C13F378A)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/ImGui.NET.dll (877912012349C6CAB2AA011290B35A7E)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/ImGuiScene.dll (0D0BDAA299A3B79511F576CD4C3055C1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/JetBrains.Annotations.dll (FAAB370045A87C53A6995FBD35F4D82E)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Lumina.dll (6A7666AD9C200A88597F4F80C3B37A7A)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Lumina.Excel.dll (68723EE34CC388F594F9AD821B9BF9A3)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Microsoft.Bcl.HashCode.dll (613AB56061ADF2284E047025207467E0)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Microsoft.DotNet.PlatformAbstractions.dll (00AB0F02B1114C57C758F5AD595224F1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Microsoft.Extensions.DependencyModel.dll (F39BC76C10CFEA478C936FC4521A9FC9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/MinSharp.dll (C5A02648B291B3574EBC3ACE6CFD9BB5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Mono.Cecil.dll (7C40214D60B54749A1A7F79EA6F62BAC)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Mono.Cecil.Mdb.dll (0C4EC4EB146BFE047755669C8060A967)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Mono.Cecil.Pdb.dll (743102D277A8754DC74F7644E03A8956)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Mono.Cecil.Rocks.dll (FE8C2B2EEF6E5E7284DC9B522A7BE468)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/MonoMod.RuntimeDetour.dll (902F9708500C77C154C0C2983FD2CEA2)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/MonoMod.Utils.dll (262AE62C0EF760AA062186560DA85DAE)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/nethost.dll (012081214FE71F0F6ADCD9F4A71B2B00)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Newtonsoft.Json.dll (916D32B899F1BC23B209648D007B99FD)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PeNet.Asn1.dll (13277F0BF9D56C0615296AA3C4792B2C)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PeNet.dll (44B99BADBB59494BCE3B6A4B95377DA8)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.AdvApi32.dll (34EE461D05B403C3A15D0DEC32A3788C)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.BCrypt.dll (FD07758EE1440491F22923084109FF26)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Cabinet.dll (333D950E3804735DA60CC41D614C63E2)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.CfgMgr32.dll (768BE7CC18EDCF78B296A72ABE891691)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Crypt32.dll (E7B00B0851738F4A7F2C6D37DAA973B4)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.DbgHelp.dll (E701136169620D20E3A70B560DE20E44)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.DwmApi.dll (ACF223CC8962404056648815B486F7D9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Gdi32.dll (69FF434826F98582CE44D3136ECFFACB)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Hid.dll (2E7A41257F8AD9B26073181F450CD8E5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.ImageHlp.dll (79BE816E8D86EA66489D7780DD675D49)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.IPHlpApi.dll (E949FA3326D1BA8872B179AB4EE49D38)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Kernel32.dll (234E15B122ED430DE99490CA1A204958)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Magnification.dll (C9EA3D34F506741ECC044DB19C151F09)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Msi.dll (69EE50CE2DA6B55755E52589F49A7EBC)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.NCrypt.dll (DA1DE76C14D99370CA3BEF19DC299B15)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.NetApi32.dll (AE79F9FA2E3864A5E0642AE4622ECDC5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.NewDev.dll (B3E1992105D986EF9C5C8E4B630FBB07)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.NTDll.dll (3F6BDF840EB27DD0FD9EB8071822183A)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Ole32.dll (3C49FB100B60519FFE725BCD12A538F6)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Psapi.dll (A7683EE4B880227F01C8AE632A892B9E)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.SetupApi.dll (1B7AE321185D0081D1759A9AD829F9BA)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.SHCore.dll (F27E7F063D51480F6D2294C903E4A606)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Shell32.dll (F71A1BCAF6478190691170DAEA77722F)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.User32.dll (8BEDE38311ED4F27127290B81B8079FD)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Userenv.dll (FEB7BCA90B8C905EC2F4BB0789847131)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.UxTheme.dll (8E683C016250CB719FDB9AAAFC22B3C5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Windows.Core.dll (90015440A44935208FFEA9BF61740651)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.Windows.ShellScalingApi.dll (F351B34B8C9183A51CADFDC279357C49)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.WinUsb.dll (9EB8A0280F2848D1A32B560A939F7336)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/PInvoke.WtsApi32.dll (341C94455D2E5893DBE4293D4D67AA4D)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Assembler.dll (C3D4B0A58258C4FEC7425F997320335D)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Assembler.targets (CC22CB0A353E2136EE9E6E96DB9F7164)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Hooks.Definitions.dll (75D96E99B5B254E665650C4AA2828E8F)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Hooks.dll (49720DD4F9388E75384CCD46E6271545)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Memory.Buffers.dll (A329185EEEB57F9CAF67D6362604ECB1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Reloaded.Memory.dll (44CAD4BAD6E2FDE73BCEC5A1DB9F6122)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SDL2-CS.config (65557595FD5DF55D93B2BF881DE62C3A)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SDL2-CS.dll (049EE80E7CA4EA66AB037B22E150A732)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Serilog.dll (181F3E3D0C509566283156816EB317CA)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Serilog.Sinks.Async.dll (3106495323806F04C7837F30B1937D39)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Serilog.Sinks.Console.dll (464F86757541FC0D1B1A1B1124FED46C)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Serilog.Sinks.File.dll (E5AE6947F5EF06D6A52A86D07CEBCB3B)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SharpDisasm.dll (C09A0B3E41B8D13D8B0FF8F3D72B064B)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SharpDX.Direct3D11.dll (D2C094FEF2DF16D0FE0E538F4179FDA1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SharpDX.dll (6C00B8BE8FB6FF838C79C9DE405DB1F5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SharpDX.DXGI.dll (FACCD233E453D81A69C5081971031ED9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/SharpDX.Mathematics.dll (627AA0022B8549C41DC65777CEC20F30)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.Core.dll (B68191524395A1A200E668FB7722EB30)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.GLFW.dll (FA158408831CA3B3A9BCDB5ADED20C8E)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.Maths.dll (C9B9FF599E789D8AEC49E85DDCED1A1E)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.OpenGL.dll (5CAEF87F2B3A920F28B255E5442CA01F)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.SDL.dll (7F4F0250947EC2A5CA5E51BF5E8D4BC1)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.Windowing.Common.dll (C1EC1EDC12583BD7F261D0EF764544C9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.Windowing.Glfw.dll (A90DDB9755E4159F355E057149787351)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Silk.NET.Windowing.Sdl.dll (8E8DD33C9F719106C920641563613E76)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/StbiSharp.dll (E74B723FBB51F705C02A351B06C90F07)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/System.Drawing.Common.dll (81322ED16B5B8CC51936161EF92889C5)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/System.Reflection.MetadataLoadContext.dll (5675DBCB2208324B6CB8D2D334682132)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/System.Security.Cryptography.Pkcs.dll (8950E01996A37E808BE3F39063C37BF9)
[17:02:40 VRB] [DUPDATE] Integrity check OK for$HOME.xlcore/dalamud/Hooks/6.4.0.9/Validation.dll (B2E7F6E81AB0DCF99FC04497A525C145)
[17:02:40 INF] [DUPDATE] Now starting for .NET Runtime 5.0.6
[17:02:40 VRB] [DASSET] Starting asset download,
[17:04:20 ERR] [DUPDATE] Asset ensurement error, bailing out...
System.Net.WebException: The operation has timed out.
   at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at XIVLauncher.Common.Dalamud.AssetManager.CheckAssetRefreshNeeded(DirectoryInfo baseDir) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/AssetManager.cs:line 146
   at XIVLauncher.Common.Dalamud.AssetManager.EnsureAssets(DirectoryInfo baseDir) in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/AssetManager.cs:line 47
   at XIVLauncher.Common.Dalamud.DalamudUpdater.UpdateDalamud() in C:/goatsoft/xl/XIVLauncher.Common/Dalamud/DalamudUpdater.cs:line 228
```

**Comment by goaaats** [comment]
Seems like your internet is spotty? I can't really do much about this on my side, sorry

**Comment by DukeValentine** [comment]
I don't have issues playing the game, or updating it/my system, so it would be odd for only with dalamud for it to become unstable.

**Comment by DukeValentine** [comment]
Is there anyway I can set dalamud up manually then?

**Comment by reiichi001** [comment]
> Is there anyway I can set dalamud up manually then?

You kinda need XIVLauncher for that. And if the assets aren't downloading correctly, you most likely are having connection issues reaching the servers that host those files to start.

You could try some of the network troubleshooting bandaids from <https://goatcorp.github.io/faq/xl_troubleshooting#q-the-official-launcher-isnt-working--xivlauncher-failed-to-check-for-updates--patch-files-could-not-be-verified> to see if they might help.

**Comment by DukeValentine** [comment]
I just tested on my windows install, dalamud started without a problem. Does it work differently on windows?

**Comment by reiichi001** [comment]
> I just tested on my windows install, dalamud started without a problem. Does it work differently on windows?

It could be a SSL/TLS issue. The assets all come from the same place, so it could be more of a configuration issue on your Linux install than an ISP issue. Do you happen to be a member of our discord? We could try doing some more troubleshooting there.

Can you also see if you're able to access the following on Linux?
<https://kamori.goats.dev/Dalamud/Asset/Meta> (this is what's failing)
<https://raw.githubusercontent.com/goatcorp/DalamudAssets/master/asset.json>  (this is the un-proxied version of the above)
<https://kamori.goats.dev/Plugin/PluginMaster> (this is something else on our proxy)

**Comment by DukeValentine** [comment]
I was able to access all links on the first file, and the couple I tested on the other two worked fine

**Comment by DukeValentine** [comment]
I'll be joining the discord later to help troubleshoot the issue then

**Comment by Plumpkrow** [comment]
> Seems like your internet is spotty? I can't really do much about this on my side, sorry

I used Nord VPN on a usb tethered phone hotspot and it began to work fine. Not sure if this could be a universal band aid to advertise
