### ISSUE TITLE
Got the following error today after the launcher updated

### ISSUE THREAD

**Issue by Krojack** [goatcorp/FFXIVQuickLauncher#971]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Launched the QuickLauncher... it updated and restarted showing the update notes.
I then entered my OTP and logged into the game. When the "SE" logo appeared I got this popup from QuickLauncher with the error.

The game didn't exit or crash. I still entered the game and everything seems to still be working including Dalamud.

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Cannot retrieve process identifier from the process handle. ---> System.ComponentModel.Win32Exception: Unknown error (0xc0000008)
   --- End of inner exception stack trace ---
   at System.Diagnostics.NtProcessManager.GetProcessIdFromHandle(SafeProcessHandle processHandle)
   at System.Diagnostics.Process.EnsureState(State state)
   at System.Diagnostics.Process.get_Id()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 1064

Version: 6.2.34.0
Git Hash: 6.2.34-0-gf42cb20
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: M:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by goaaats** [comment]
Does this always happen when you start the game?

**Comment by Krojack** [comment]
Just logged out and back in 2 times and no error... Maybe a one time thing I guess. First error I ever got so thought I should post it.

**Comment by NotNite** [comment]
Closing due to inactivity. If you're still having issues, please reopen this issue.
